In [4]:

from langchain_community.tools import TavilySearchResults

tavily_search = TavilySearchResults(
    max_results=5
)


res = tavily_search.invoke({"query": "2025 한국 경제 전망"})
for r in res:
    print(r)

C:\Users\pc04-06\AppData\Local\Temp\ipykernel_16188\517479136.py:3: LangChainDeprecationWarning: The class `TavilySearchResults` was deprecated in LangChain 0.3.25 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-tavily package and should be used instead. To use it run `pip install -U :class:`~langchain-tavily` and import as `from :class:`~langchain_tavily import TavilySearch``.
  tavily_search = TavilySearchResults(


{'title': '2025년 한국 경제 전망(수정) - 현대경제연구원', 'url': 'https://hri.co.kr/upload/board/2887055909_vDf0PB9V_20250507061207.pdf', 'content': "2025년 한국 경제 전망(수정) 25 < 현대경제연구원의 2025년 한국 경제 전망표 (2025년 4월) > 구 분 2023 2024 2025(E) 상반 하반 연간 상반 하반 연간 국 민 계 정 경제성장률 (%) 1.4 2.8 1.3 2.0 0.4 0.9 0.7 민간소비 (%) 1.8 1.0 1.3 1.1 0.6 1.2 0.9 건설투자 (%) 1.5 0.4 △6.1 △3.0 △10.0 △2.0 △6.1 설비투자 (%) 1.1 △1.8 5.1 1.6 4.0 △1.5 1.2 대 외 거 래 경상수지 (억 달러) 355 402 589 990 260 230 490 무역수지 (억 달러) △103 230 289 518 148 128 276 수출증가율 (%) △7.5 9.1 7.2 8.1 △4.3 △3.7 △4.0 수입증가율 (%) △12.1 △6.4 3.4 △1.7 △2.0 1.0 △0.5 소비자물가상승률 (%) 3.6 2.8 1.8 2.3 2.0 1.5 1.7 실업률 (%) 2.7 3.1 [...] < 현대경제연구원의 2025년 한국 경제 전망표 (2025년 4월) > 구 분 2023 2024 2025(E) 상반 하반 연간 상반 하반 연간 국 민 계 정 경제성장률 (%) 1.4 2.8 1.3 2.0 0.4 0.9 0.7 민간소비 (%) 1.8 1.0 1.3 1.1 0.6 1.2 0.9 건설투자 (%) 1.5 0.4 △6.1 △3.0 △10.0 △2.0 △6.1 설비투자 (%) 1.1 △1.8 5.1 1.6 4.0 △1.5 1.2 대 외 거 래 경상수지 (억 달러) 355 402 589 990 260 230 490 무역수지 (억 달러) △103 230 289 518 148 128 276 수출증가율 (%) △7.5 9.1 7.2 8.1 

### C:\Users\pc04-06\AppData\Local\Temp\ipykernel_16244\517479136.py:3: LangChainDeprecationWarning: The class `TavilySearchResults` was deprecated in LangChain 0.3.25 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-tavily package and should be used instead. To use it run `pip install -U :class:`~langchain-tavily` and import as `from :class:`~langchain_tavily import TavilySearch``.
  tavily_search = TavilySearchResults(
{'title': '2025년 한국 경제 전망(수정) - 현대경제연구원', 'url': 'https://hri.co.kr/upload/board/2887055909_vDf0PB9V_20250507061207.pdf', 'content': "2025년 한국 경제 전망(수정) 25 < 현대경제연구원의 2025년 한국 경제 전망표 (2025년 4월) > 구 분 2023 2024 2025(E) 상반 하반 연간 상반 하반 연간 국 민 계 정 경제성장률 (%) 1.4 2.8 1.3 2.0 0.4 0.9 0.7 민간소비 (%) 1.8 1.0 1.3 1.1 0.6 1.2 0.9 건설투자 (%) 1.5 0.4 △6.1 △3.0 △10.0 △2.0 △6.1 설비투자 (%) 1.1 △1.8 5.1 1.6 4.0 △1.5 1.2 대 외 거 래 경상수지 (억 달러) 355 402 589 990 260 230 490 무역수지 (억 달러) △103 230 289 518 148 128 276 수출증가율 (%) △7.5 9.1 7.2 8.1 △4.3 △3.7 △4.0 수입증가율 (%) △12.1 △6.4 3.4 △1.7 △2.0 1.0 △0.5 소비자물가상승률 (%) 3.6 2.8 1.8 2.3 2.0 1.5 1.7 실업률 (%) 2.7 3.1 [...] < 현대경제연구원의 2025년 한국 경제 전망표 (2025년 4월) > 구 분 2023 2024 2025(E) 상반 하반 연간 상반 하반 연간 국 민 계 정 경제성장률 (%) 1.4 2.8 1.3 2.0 0.4 0.9 0.7 민간소비 (%) 1.8 1.0 1.3 1.1 0.6 1.2 0.9 건설투자 (%) 1.5 0.4 △6.1 △3.0 △10.0 △2.0 △6.1 설비투자 (%) 1.1 △1.8 5.1 1.6 4.0 △1.5 1.2 대 외 거 래 경상수지 (억 달러) 355 402 589 990 260 230 490 무역수지 (억 달러) △103 230 289 518 148 128 276 수출증가율 (%) △7.5 9.1 7.2 8.1 △4.3 △3.7 △4.0 수입증가율 (%) △12.1 △6.4 3.4 △1.7 △2.0 1.0 △0.5 소비자물가상승률 (%) 3.6 2.8 1.8 2.3 2.0 1.5 1.7 실업률 (%) 2.7 3.1 2.5 2.8 3.3 3.4 3.3 [...] 2025년 한국 경제 전망(수정) 24 실업률 2.8% ⇨ 3.3% (2024) (2025) - 실업률은 '24년 2.8%에서 '25년 3.3%로 높아질 것으로 전망 ․ 전반적인 경제 상황 침체의 영향으로 고용창출력이 크게 약화되면서 실업 률이 크게 높아질 것으로 전망됨 ․ 특히, 불황 국면에서 기업들이 경력자를 선호하는 구인 특성을 보인다는 점을 고려할 때, 청년층 실업 문제가 심각한 수준에 이를 가능성이 높다고 판단됨 취업자수증감 16만명 ⇨ 15만명 (2024) (2025) - 신규취업자수전년동기대비 취업자수증감은 '24년 16만 명에서 '25년 15만 명으로 소폭 감소할 전망 ․ 상·하반기별로 보면 상반기에는 16만 명, 하반기에는 14만 명 수준을 기 록할 것으로 예상됨 ․ 신규취업자수의 감소 폭이 크지 않은 이유는 최근의 고용 시장 상황에서 찾아볼 수 있는데, 제조업이나 건설업에서의 고임금자가 서비스업 내 저임 금 업종으로 전환되면서 신규 일자리 숫자 자체가 크게", 'score': 0.942002}
{'title': '2025년 수정 경제전망', 'url': 'https://www.kif.re.kr/kif4/publication/pub_detail?mid=21&nid=199&sid=199&vid=7465&cno=349465&pn=1', 'content': '금융브리프\n   경제전망\n   금융연구\n   한국경제의 분석\n   종간간행물\n\n### KIF 인기 연구자료\n\n   KIF이슈리포트 주요국의 전자금융거래 규제 및 시사점 : 사업자 분류 및 관련 주요 개념을 중심으로\n   금융브리프 영국 국채시장 불안 사례의 배경과 시사점\n   KIF이슈리포트 그린핀테크(Green FinTech) 국내외 사례와 정책적 시사점\n\n### 경제전망\n\n특별호\n\n링크 복사 출력\n\n##### 2025년 수정 경제전망\n\n국내 실물경제, 통화/금리/물가\n\nImage 1\n\n저자\nKIF\n\n페이지 수 _160_\n\n   바로보기\n   다운로드\n\n   요약\n   목차\n\nⅠ. 2025년 경제전망\n\n1. 경제성장\n\n▣ 2025년 우리 경제의 실질 국내총생산(GDP)은 0.8% 성장할 것으로 전망\n\n ∙대내외 불확실성 확대로 민간소비 회복이 둔화되고 누적된 수주 부진의 영향으로 건설투자가 크게 부진한 가운데 미국 관세 인상 여파로 수출도 위축되면서 성장이 둔화될 전망 [...] ▣ 2025년 고용률은 62.7%를 기록할 전망\n\n ∙고용률은 기업 경영 여건의 악화 및 내수 부진의 지속에도 불구하고 60세 이상 고령층의 견조한 노동시장 진입으로 전년도 수준을 유지할 전망\n\n ∙실업률은 전년대비 소폭 상승한 2.9%를 기록할 것으로 예상\n\n ∙취업자 수는 약 8만명 증가하여 전년대비 증가세가 둔화될 전망\n\n3. 물가 및 시장금리 \n\n▣ 소비자물가상승률은 상반기 2.0%, 하반기 1.9%로 연간으로는 2.0%를 기록할 전망\n\n ∙내수 부진 지속, 수출 감소 등으로 경제성장률이 크게 낮아지는 가운데 글로벌 경기침체 우려에 따른 유가 등 원자재가격 하락으로 물가는 하향 안정세를 유지할 것으로 전망\n\n ∙지정학적 위험 및 관세 협상 관련 불확실성 확대, 연준 금리인하 지연 등으로 인한 원/달러 환율 상승 가능성은 물가에 상방 압력으로 작용할 것으로 예상\n\n▣ 국고채 3년물의 연평균 금리는 2.3%로 전년 대비 상당폭 하락할 전망 [...] 제 II 장 2025년 국·내외 경제여건 \n\n1. 해외경제여건 \n\n2. 국내경제여건 \n\n3. 주요 고려사항 \n\n제 III 장 2025년 경제전망 \n\n1. 2025년 국내경제전망 \n\n2. 종합평가 및 정책제언\n\n###### 관련자료\n\n   보고서\n   정기간행물\n\n   통화/금리/물가우리나라의 소비행태 변화와 인플레이션KIF연구보고서 장민 2024-12   \n   해외경제,국내 실물경제,계량분석/모형글로벌 VAR 모형을 활용한 대외충격 효과 분석 및 경제전망KIF연구보고서 김현태 2024-12   \n   국내 실물경제,고용/임금,계량분석/모형우리나라 이민정책의 현황, 평가분석 및 향후과제KIF Working Paper 강종구, 류상철, 안희욱, 이중식 2024-11', 'score': 0.90771407}
{'title': "산업연구원, 2025년 한국 경제성장률 1.0%로 '뚝'…위기의 징후인가?", 'url': 'https://www.incheon.go.kr/moo/MOO020101/3014715', 'content': '#### 산업연구원, 2025년 한국 경제성장률 1.0%로 ‘뚝’…위기의 징후인가?\n\n작성자 이솔은\n\n 작성일 2025-05-27\n\n2025년 5월 27일, 산업연구원(KIET)은 한국의 경제에 대한 우려 섞인 전망을 내놓았다.\n\n기존 2.1%로 예상되던 2025년 실질 GDP 성장률이 단 1.0%로 하향 조정된 것이다.\n\n이는 팬데믹 이후 회복세에 있던 한국 경제가 다시 둔화 국면에 접어들었음을 보여주는 신호로 해석된다.\n\n보고서에 따르면 상반기 성장률은 0.5%에 불과했고, 하반기에도 1.4% 수준에 머물 것으로 보인다.\n\n산업연은 이번 성장률 하향 조정의 주요 원인으로 ▲미국의 보호무역 강화에 따른 수출 부진 ▲국내 소비 위축 ▲설비 투자 감소 등을 꼽았다.\n\n가장 큰 타격을 입은 것은 수출 산업이다.\n\n전년 대비 수출은 약 2% 가까이 감소하며 6,706억 달러에 그칠 것으로 예측된다.', 'score': 0.9047265}
{'title': '수정, 2025년 8월 - KDI 한국개발연구원 - 연구 - 경제전망', 'url': 'https://www.kdi.re.kr/research/economy', 'content': '□ 2025년 원유 도입단가(두바이유 기준)는 수요 부진에 기인하여 2024년(배럴당 80 달러)보다 낮은 69달러를 기록한 후 2026년에는 66달러로 소폭 하락할 것으로 전제\n\n   □ 실질실효환율로 평가한 원화가치는 최근 수준에서 큰 변동이 없을 것으로 전제\n\n2. 2025~26년 국내경제 전망\n\n   □ 우리 경제는 2025년에 건설업 부진과 통상 여건 악화로 0.8% 성장하는 데 그친 후,2026년에는 통상분쟁의 여파에도 불구하고 완만한 내수 회복으로 1.6% 성장할 전망 [...] 우리 경제는2025년에 건설업 부진과 통상 여건 악화로 0.8% 성장하는 데 그친 후,2026년에는 통상분쟁의 여파에도 불구하고 완만한 내수 회복으로 1.6% 성장할 전망 [...] · 금년 우리 경제의 잠재성장률은 1%대 후반으로 추정되며, 2040년대에는 잠재성장률이 0% 내외까지 하락할 전망\n    · 따라서 진입장벽과 노동시장 경직성을 완화하는 등 생산성 개선을 위한 노력이 필요\n    · 이와 함께 거시정책 기조도 이러한 잠재성장률 하락 추세를 감안하여 설정할 필요\n\nⅡ. 2025~26년 국내경제 전망\n\n1. 대외여건에 대한 주요 전제\n\n   □ 2025~26년 세계경제는 국제 무역이 위축됨에 따라 성장세가 약화될 것으로 전제\n\n    · 최근 IMF는 미국의 보호무역주의가 초래한 통상환경 악화로 2025년 세계경제가 2024년(3.3%)보다 낮은 2.8%의 성장률을 기록한 후, 2026년에도 3.0% 성장에 그칠 것으로 전망\n    · 미국 관세정책은 기본관세 10%와 현재의 품목별 관세율이 향후에도 지속될 것으로 전제', 'score': 0.89053273}
{'title': '경제전망보고서(2025년 2월)', 'url': 'https://www.bok.or.kr/portal/bbs/P0002359/view.do?nttId=10089959&oldMenuNo=201150&menuNo=200066&programType=newsData&depth=200066&relate=Y', 'content': '안녕하십니까, 저는 한국은행 조사국 국제종합팀에서 근무하고 있는 이택민 과장이라고 합니다. 오늘 이렇게 귀한 시간 내서 참석해 주셔서 정말 감사드립니다. 오늘 저와 최영우 과장님이 발표를 할 내용은 한국은행이 금년 2월 말에 발표한 경제전망 보고서를 기반으로 하고 있고요. 2025년 세계 경제와 우리나라 경제 전망에 대해서 말씀드리도록 하겠습니다.\n\n[Contents] (p.2)\n\n1번 대내외 여건 점검 파트가 일종의 전반부로 제가 발표할 내용이고요, 이어서 2번 거시 경제 전망 파트가 후반부에서 최영우 과장님께서 발표하실 내용입니다. 먼저 대내외 여건 점검 파트가 무엇인지에 대해 말씀을 드릴게요. 한국은행 경제전망은 조건부 전망입니다. 이를 간단하게 말씀드리면 우리나라 한국 경제에 영향을 미칠 수 있는 주요 여건들을 살펴보고, 앞으로 어떻게 흘러갈 것인지 전제를 합니다. 이러한 전제를 기반으로 해서 앞으로 한국 경제가 어떻게 될 것이라는 것을 다음 파트에서 전망하는 것입니다. [...] 봤던 것보다 내년에도 그만큼 좀 보수적으로 지금 경기를 좀 보고 계시는 건지. 그걸 좀 알고 싶고. 아까 총재님께서 1.8% 우리 실력이라고 말씀을 하시긴 하셨는데, 내년에 1.8% 이지만 올해 1.4%잖아요. 보통 이제 경기라는 게 한참 또 나빴으면 돌아올 때가 있고 하면서 가야 되는 건데. 올해 1.4 하고 내년 1.8이고 그러면 내후년에 좋아져서 그러면 다시 1.8이 되는 것인지. 그러니까 결과적으로 이런 관세 문제나 이런 것들이 좀 해결이 되면 한국 경제가 그만큼 잠재성장으로 돌아갈 수 있을 정도로 좀 더 성장할 수 있는 것인지. 그런 부분에서 좀 의견 부탁드립니다.', 'score': 0.8732259}

In [5]:
from IPython.display import JSON
JSON(res).data

[{'title': '2025년 한국 경제 전망(수정) - 현대경제연구원',
  'url': 'https://hri.co.kr/upload/board/2887055909_vDf0PB9V_20250507061207.pdf',
  'content': "2025년 한국 경제 전망(수정) 25 < 현대경제연구원의 2025년 한국 경제 전망표 (2025년 4월) > 구 분 2023 2024 2025(E) 상반 하반 연간 상반 하반 연간 국 민 계 정 경제성장률 (%) 1.4 2.8 1.3 2.0 0.4 0.9 0.7 민간소비 (%) 1.8 1.0 1.3 1.1 0.6 1.2 0.9 건설투자 (%) 1.5 0.4 △6.1 △3.0 △10.0 △2.0 △6.1 설비투자 (%) 1.1 △1.8 5.1 1.6 4.0 △1.5 1.2 대 외 거 래 경상수지 (억 달러) 355 402 589 990 260 230 490 무역수지 (억 달러) △103 230 289 518 148 128 276 수출증가율 (%) △7.5 9.1 7.2 8.1 △4.3 △3.7 △4.0 수입증가율 (%) △12.1 △6.4 3.4 △1.7 △2.0 1.0 △0.5 소비자물가상승률 (%) 3.6 2.8 1.8 2.3 2.0 1.5 1.7 실업률 (%) 2.7 3.1 [...] < 현대경제연구원의 2025년 한국 경제 전망표 (2025년 4월) > 구 분 2023 2024 2025(E) 상반 하반 연간 상반 하반 연간 국 민 계 정 경제성장률 (%) 1.4 2.8 1.3 2.0 0.4 0.9 0.7 민간소비 (%) 1.8 1.0 1.3 1.1 0.6 1.2 0.9 건설투자 (%) 1.5 0.4 △6.1 △3.0 △10.0 △2.0 △6.1 설비투자 (%) 1.1 △1.8 5.1 1.6 4.0 △1.5 1.2 대 외 거 래 경상수지 (억 달러) 355 402 589 990 260 230 490 무역수지 (억 달러) △103 230 289 518 148 128 276 수출증가율 (%) △7.5 9.1 7.2

### [{'title': '2025년 한국 경제 전망(수정) - 현대경제연구원',
  'url': 'https://hri.co.kr/upload/board/2887055909_vDf0PB9V_20250507061207.pdf',
  'content': "2025년 한국 경제 전망(수정) 25 < 현대경제연구원의 2025년 한국 경제 전망표 (2025년 4월) > 구 분 2023 2024 2025(E) 상반 하반 연간 상반 하반 연간 국 민 계 정 경제성장률 (%) 1.4 2.8 1.3 2.0 0.4 0.9 0.7 민간소비 (%) 1.8 1.0 1.3 1.1 0.6 1.2 0.9 건설투자 (%) 1.5 0.4 △6.1 △3.0 △10.0 △2.0 △6.1 설비투자 (%) 1.1 △1.8 5.1 1.6 4.0 △1.5 1.2 대 외 거 래 경상수지 (억 달러) 355 402 589 990 260 230 490 무역수지 (억 달러) △103 230 289 518 148 128 276 수출증가율 (%) △7.5 9.1 7.2 8.1 △4.3 △3.7 △4.0 수입증가율 (%) △12.1 △6.4 3.4 △1.7 △2.0 1.0 △0.5 소비자물가상승률 (%) 3.6 2.8 1.8 2.3 2.0 1.5 1.7 실업률 (%) 2.7 3.1 [...] < 현대경제연구원의 2025년 한국 경제 전망표 (2025년 4월) > 구 분 2023 2024 2025(E) 상반 하반 연간 상반 하반 연간 국 민 계 정 경제성장률 (%) 1.4 2.8 1.3 2.0 0.4 0.9 0.7 민간소비 (%) 1.8 1.0 1.3 1.1 0.6 1.2 0.9 건설투자 (%) 1.5 0.4 △6.1 △3.0 △10.0 △2.0 △6.1 설비투자 (%) 1.1 △1.8 5.1 1.6 4.0 △1.5 1.2 대 외 거 래 경상수지 (억 달러) 355 402 589 990 260 230 490 무역수지 (억 달러) △103 230 289 518 148 128 276 수출증가율 (%) △7.5 9.1 7.2 8.1 △4.3 △3.7 △4.0 수입증가율 (%) △12.1 △6.4 3.4 △1.7 △2.0 1.0 △0.5 소비자물가상승률 (%) 3.6 2.8 1.8 2.3 2.0 1.5 1.7 실업률 (%) 2.7 3.1 2.5 2.8 3.3 3.4 3.3 [...] 2025년 한국 경제 전망(수정) 24 실업률 2.8% ⇨ 3.3% (2024) (2025) - 실업률은 '24년 2.8%에서 '25년 3.3%로 높아질 것으로 전망 ․ 전반적인 경제 상황 침체의 영향으로 고용창출력이 크게 약화되면서 실업 률이 크게 높아질 것으로 전망됨 ․ 특히, 불황 국면에서 기업들이 경력자를 선호하는 구인 특성을 보인다는 점을 고려할 때, 청년층 실업 문제가 심각한 수준에 이를 가능성이 높다고 판단됨 취업자수증감 16만명 ⇨ 15만명 (2024) (2025) - 신규취업자수전년동기대비 취업자수증감은 '24년 16만 명에서 '25년 15만 명으로 소폭 감소할 전망 ․ 상·하반기별로 보면 상반기에는 16만 명, 하반기에는 14만 명 수준을 기 록할 것으로 예상됨 ․ 신규취업자수의 감소 폭이 크지 않은 이유는 최근의 고용 시장 상황에서 찾아볼 수 있는데, 제조업이나 건설업에서의 고임금자가 서비스업 내 저임 금 업종으로 전환되면서 신규 일자리 숫자 자체가 크게",
  'score': 0.942002},
 {'title': '2025년 수정 경제전망',
  'url': 'https://www.kif.re.kr/kif4/publication/pub_detail?mid=21&nid=199&sid=199&vid=7465&cno=349465&pn=1',
  'content': '금융브리프\n   경제전망\n   금융연구\n   한국경제의 분석\n   종간간행물\n\n### KIF 인기 연구자료\n\n   KIF이슈리포트 주요국의 전자금융거래 규제 및 시사점 : 사업자 분류 및 관련 주요 개념을 중심으로\n   금융브리프 영국 국채시장 불안 사례의 배경과 시사점\n   KIF이슈리포트 그린핀테크(Green FinTech) 국내외 사례와 정책적 시사점\n\n### 경제전망\n\n특별호\n\n링크 복사 출력\n\n##### 2025년 수정 경제전망\n\n국내 실물경제, 통화/금리/물가\n\nImage 1\n\n저자\nKIF\n\n페이지 수 _160_\n\n   바로보기\n   다운로드\n\n   요약\n   목차\n\nⅠ. 2025년 경제전망\n\n1. 경제성장\n\n▣ 2025년 우리 경제의 실질 국내총생산(GDP)은 0.8% 성장할 것으로 전망\n\n ∙대내외 불확실성 확대로 민간소비 회복이 둔화되고 누적된 수주 부진의 영향으로 건설투자가 크게 부진한 가운데 미국 관세 인상 여파로 수출도 위축되면서 성장이 둔화될 전망 [...] ▣ 2025년 고용률은 62.7%를 기록할 전망\n\n ∙고용률은 기업 경영 여건의 악화 및 내수 부진의 지속에도 불구하고 60세 이상 고령층의 견조한 노동시장 진입으로 전년도 수준을 유지할 전망\n\n ∙실업률은 전년대비 소폭 상승한 2.9%를 기록할 것으로 예상\n\n ∙취업자 수는 약 8만명 증가하여 전년대비 증가세가 둔화될 전망\n\n3. 물가 및 시장금리 \n\n▣ 소비자물가상승률은 상반기 2.0%, 하반기 1.9%로 연간으로는 2.0%를 기록할 전망\n\n ∙내수 부진 지속, 수출 감소 등으로 경제성장률이 크게 낮아지는 가운데 글로벌 경기침체 우려에 따른 유가 등 원자재가격 하락으로 물가는 하향 안정세를 유지할 것으로 전망\n\n ∙지정학적 위험 및 관세 협상 관련 불확실성 확대, 연준 금리인하 지연 등으로 인한 원/달러 환율 상승 가능성은 물가에 상방 압력으로 작용할 것으로 예상\n\n▣ 국고채 3년물의 연평균 금리는 2.3%로 전년 대비 상당폭 하락할 전망 [...] 제 II 장 2025년 국·내외 경제여건 \n\n1. 해외경제여건 \n\n2. 국내경제여건 \n\n3. 주요 고려사항 \n\n제 III 장 2025년 경제전망 \n\n1. 2025년 국내경제전망 \n\n2. 종합평가 및 정책제언\n\n###### 관련자료\n\n   보고서\n   정기간행물\n\n   통화/금리/물가우리나라의 소비행태 변화와 인플레이션KIF연구보고서 장민 2024-12   \n   해외경제,국내 실물경제,계량분석/모형글로벌 VAR 모형을 활용한 대외충격 효과 분석 및 경제전망KIF연구보고서 김현태 2024-12   \n   국내 실물경제,고용/임금,계량분석/모형우리나라 이민정책의 현황, 평가분석 및 향후과제KIF Working Paper 강종구, 류상철, 안희욱, 이중식 2024-11',
  'score': 0.90771407},
 {'title': "산업연구원, 2025년 한국 경제성장률 1.0%로 '뚝'…위기의 징후인가?",
  'url': 'https://www.incheon.go.kr/moo/MOO020101/3014715',
  'content': '#### 산업연구원, 2025년 한국 경제성장률 1.0%로 ‘뚝’…위기의 징후인가?\n\n작성자 이솔은\n\n 작성일 2025-05-27\n\n2025년 5월 27일, 산업연구원(KIET)은 한국의 경제에 대한 우려 섞인 전망을 내놓았다.\n\n기존 2.1%로 예상되던 2025년 실질 GDP 성장률이 단 1.0%로 하향 조정된 것이다.\n\n이는 팬데믹 이후 회복세에 있던 한국 경제가 다시 둔화 국면에 접어들었음을 보여주는 신호로 해석된다.\n\n보고서에 따르면 상반기 성장률은 0.5%에 불과했고, 하반기에도 1.4% 수준에 머물 것으로 보인다.\n\n산업연은 이번 성장률 하향 조정의 주요 원인으로 ▲미국의 보호무역 강화에 따른 수출 부진 ▲국내 소비 위축 ▲설비 투자 감소 등을 꼽았다.\n\n가장 큰 타격을 입은 것은 수출 산업이다.\n\n전년 대비 수출은 약 2% 가까이 감소하며 6,706억 달러에 그칠 것으로 예측된다.',
  'score': 0.9047265},
 {'title': '수정, 2025년 8월 - KDI 한국개발연구원 - 연구 - 경제전망',
  'url': 'https://www.kdi.re.kr/research/economy',
  'content': '□ 2025년 원유 도입단가(두바이유 기준)는 수요 부진에 기인하여 2024년(배럴당 80 달러)보다 낮은 69달러를 기록한 후 2026년에는 66달러로 소폭 하락할 것으로 전제\n\n   □ 실질실효환율로 평가한 원화가치는 최근 수준에서 큰 변동이 없을 것으로 전제\n\n2. 2025~26년 국내경제 전망\n\n   □ 우리 경제는 2025년에 건설업 부진과 통상 여건 악화로 0.8% 성장하는 데 그친 후,2026년에는 통상분쟁의 여파에도 불구하고 완만한 내수 회복으로 1.6% 성장할 전망 [...] 우리 경제는2025년에 건설업 부진과 통상 여건 악화로 0.8% 성장하는 데 그친 후,2026년에는 통상분쟁의 여파에도 불구하고 완만한 내수 회복으로 1.6% 성장할 전망 [...] · 금년 우리 경제의 잠재성장률은 1%대 후반으로 추정되며, 2040년대에는 잠재성장률이 0% 내외까지 하락할 전망\n    · 따라서 진입장벽과 노동시장 경직성을 완화하는 등 생산성 개선을 위한 노력이 필요\n    · 이와 함께 거시정책 기조도 이러한 잠재성장률 하락 추세를 감안하여 설정할 필요\n\nⅡ. 2025~26년 국내경제 전망\n\n1. 대외여건에 대한 주요 전제\n\n   □ 2025~26년 세계경제는 국제 무역이 위축됨에 따라 성장세가 약화될 것으로 전제\n\n    · 최근 IMF는 미국의 보호무역주의가 초래한 통상환경 악화로 2025년 세계경제가 2024년(3.3%)보다 낮은 2.8%의 성장률을 기록한 후, 2026년에도 3.0% 성장에 그칠 것으로 전망\n    · 미국 관세정책은 기본관세 10%와 현재의 품목별 관세율이 향후에도 지속될 것으로 전제',
  'score': 0.89053273},
 {'title': '경제전망보고서(2025년 2월)',
  'url': 'https://www.bok.or.kr/portal/bbs/P0002359/view.do?nttId=10089959&oldMenuNo=201150&menuNo=200066&programType=newsData&depth=200066&relate=Y',
  'content': '안녕하십니까, 저는 한국은행 조사국 국제종합팀에서 근무하고 있는 이택민 과장이라고 합니다. 오늘 이렇게 귀한 시간 내서 참석해 주셔서 정말 감사드립니다. 오늘 저와 최영우 과장님이 발표를 할 내용은 한국은행이 금년 2월 말에 발표한 경제전망 보고서를 기반으로 하고 있고요. 2025년 세계 경제와 우리나라 경제 전망에 대해서 말씀드리도록 하겠습니다.\n\n[Contents] (p.2)\n\n1번 대내외 여건 점검 파트가 일종의 전반부로 제가 발표할 내용이고요, 이어서 2번 거시 경제 전망 파트가 후반부에서 최영우 과장님께서 발표하실 내용입니다. 먼저 대내외 여건 점검 파트가 무엇인지에 대해 말씀을 드릴게요. 한국은행 경제전망은 조건부 전망입니다. 이를 간단하게 말씀드리면 우리나라 한국 경제에 영향을 미칠 수 있는 주요 여건들을 살펴보고, 앞으로 어떻게 흘러갈 것인지 전제를 합니다. 이러한 전제를 기반으로 해서 앞으로 한국 경제가 어떻게 될 것이라는 것을 다음 파트에서 전망하는 것입니다. [...] 봤던 것보다 내년에도 그만큼 좀 보수적으로 지금 경기를 좀 보고 계시는 건지. 그걸 좀 알고 싶고. 아까 총재님께서 1.8% 우리 실력이라고 말씀을 하시긴 하셨는데, 내년에 1.8% 이지만 올해 1.4%잖아요. 보통 이제 경기라는 게 한참 또 나빴으면 돌아올 때가 있고 하면서 가야 되는 건데. 올해 1.4 하고 내년 1.8이고 그러면 내후년에 좋아져서 그러면 다시 1.8이 되는 것인지. 그러니까 결과적으로 이런 관세 문제나 이런 것들이 좀 해결이 되면 한국 경제가 그만큼 잠재성장으로 돌아갈 수 있을 정도로 좀 더 성장할 수 있는 것인지. 그런 부분에서 좀 의견 부탁드립니다.',
  'score': 0.8732259}]

In [6]:
from tavily import TavilyClient

client = TavilyClient()

content = client.search(
    "2025년 한국 경제 전망",  
    search_depth="advanced",
    include_raw_content=True,
)

JSON(content).data

{'query': '2025년 한국 경제 전망',
 'follow_up_questions': None,
 'answer': None,
 'images': [],
 'results': [{'url': 'https://hri.co.kr/upload/board/2887055909_vDf0PB9V_20250507061207.pdf',
   'title': '2025년 한국 경제 전망(수정) - 현대경제연구원',
   'content': "2025년 한국 경제 전망(수정) 25 < 현대경제연구원의 2025년 한국 경제 전망표 (2025년 4월) > 구 분 2023 2024 2025(E) 상반 하반 연간 상반 하반 연간 국 민 계 정 경제성장률 (%) 1.4 2.8 1.3 2.0 0.4 0.9 0.7 민간소비 (%) 1.8 1.0 1.3 1.1 0.6 1.2 0.9 건설투자 (%) 1.5 0.4 △6.1 △3.0 △10.0 △2.0 △6.1 설비투자 (%) 1.1 △1.8 5.1 1.6 4.0 △1.5 1.2 대 외 거 래 경상수지 (억 달러) 355 402 589 990 260 230 490 무역수지 (억 달러) △103 230 289 518 148 128 276 수출증가율 (%) △7.5 9.1 7.2 8.1 △4.3 △3.7 △4.0 수입증가율 (%) △12.1 △6.4 3.4 △1.7 △2.0 1.0 △0.5 소비자물가상승률 (%) 3.6 2.8 1.8 2.3 2.0 1.5 1.7 실업률 (%) 2.7 3.1 [...] < 현대경제연구원의 2025년 한국 경제 전망표 (2025년 4월) > 구 분 2023 2024 2025(E) 상반 하반 연간 상반 하반 연간 국 민 계 정 경제성장률 (%) 1.4 2.8 1.3 2.0 0.4 0.9 0.7 민간소비 (%) 1.8 1.0 1.3 1.1 0.6 1.2 0.9 건설투자 (%) 1.5 0.4 △6.1 △3.0 △10.0 △2.0 △6.1 설비투자 (%) 1.1 △1.8 5.1 1.6 4.0 △1.5 1.2 대 외 거 래

### {'query': '2025년 한국 경제 전망',
 'follow_up_questions': None,
 'answer': None,
 'images': [],
 'results': [{'url': 'https://hri.co.kr/upload/board/2887055909_vDf0PB9V_20250507061207.pdf',
   'title': '2025년 한국 경제 전망(수정) - 현대경제연구원',
   'content': "2025년 한국 경제 전망(수정) 25 < 현대경제연구원의 2025년 한국 경제 전망표 (2025년 4월) > 구 분 2023 2024 2025(E) 상반 하반 연간 상반 하반 연간 국 민 계 정 경제성장률 (%) 1.4 2.8 1.3 2.0 0.4 0.9 0.7 민간소비 (%) 1.8 1.0 1.3 1.1 0.6 1.2 0.9 건설투자 (%) 1.5 0.4 △6.1 △3.0 △10.0 △2.0 △6.1 설비투자 (%) 1.1 △1.8 5.1 1.6 4.0 △1.5 1.2 대 외 거 래 경상수지 (억 달러) 355 402 589 990 260 230 490 무역수지 (억 달러) △103 230 289 518 148 128 276 수출증가율 (%) △7.5 9.1 7.2 8.1 △4.3 △3.7 △4.0 수입증가율 (%) △12.1 △6.4 3.4 △1.7 △2.0 1.0 △0.5 소비자물가상승률 (%) 3.6 2.8 1.8 2.3 2.0 1.5 1.7 실업률 (%) 2.7 3.1 [...] < 현대경제연구원의 2025년 한국 경제 전망표 (2025년 4월) > 구 분 2023 2024 2025(E) 상반 하반 연간 상반 하반 연간 국 민 계 정 경제성장률 (%) 1.4 2.8 1.3 2.0 0.4 0.9 0.7 민간소비 (%) 1.8 1.0 1.3 1.1 0.6 1.2 0.9 건설투자 (%) 1.5 0.4 △6.1 △3.0 △10.0 △2.0 △6.1 설비투자 (%) 1.1 △1.8 5.1 1.6 4.0 △1.5 1.2 대 외 거 래 경상수지 (억 달러) 355 402 589 990 260 230 490 무역수지 (억 달러) △103 230 289 518 148 128 276 수출증가율 (%) △7.5 9.1 7.2 8.1 △4.3 △3.7 △4.0 수입증가율 (%) △12.1 △6.4 3.4 △1.7 △2.0 1.0 △0.5 소비자물가상승률 (%) 3.6 2.8 1.8 2.3 2.0 1.5 1.7 실업률 (%) 2.7 3.1 2.5 2.8 3.3 3.4 3.3 [...] 2025년 한국 경제 전망(수정) 24 실업률 2.8% ⇨ 3.3% (2024) (2025) - 실업률은 '24년 2.8%에서 '25년 3.3%로 높아질 것으로 전망 ․ 전반적인 경제 상황 침체의 영향으로 고용창출력이 크게 약화되면서 실업 률이 크게 높아질 것으로 전망됨 ․ 특히, 불황 국면에서 기업들이 경력자를 선호하는 구인 특성을 보인다는 점을 고려할 때, 청년층 실업 문제가 심각한 수준에 이를 가능성이 높다고 판단됨 취업자수증감 16만명 ⇨ 15만명 (2024) (2025) - 신규취업자수전년동기대비 취업자수증감은 '24년 16만 명에서 '25년 15만 명으로 소폭 감소할 전망 ․ 상·하반기별로 보면 상반기에는 16만 명, 하반기에는 14만 명 수준을 기 록할 것으로 예상됨 ․ 신규취업자수의 감소 폭이 크지 않은 이유는 최근의 고용 시장 상황에서 찾아볼 수 있는데, 제조업이나 건설업에서의 고임금자가 서비스업 내 저임 금 업종으로 전환되면서 신규 일자리 숫자 자체가 크게",
   'score': 0.9459663,
   'raw_content': "25-07(통권 986호) 2025.04.30 2025년 한국 경제 전망(수정) - 2025년 경제성장률, 1.0%p 하향조정한 0.7% 목 차 ■ 2025년 한국 경제 전망(수정) - 2025년 경제성장률, 1.0%p 하향조정한 0.7% Executive Summary ······················································································ⅰ 1. 대외 경제 환경 변화···················································································1 2. 최근 한국 경제 경기 동향··········································································8 3. 한국 경제 전망··························································································16 4. 시사점········································································································26 \x01 \x01 \x01 \x01 \x01 \x01 \x01 \x01 \x01 \x01 \x01 \x01 \x01 \x01 \x01 \x01 \x01 \x01 \x01 \x01 \x01 \x01 □ 비상업 목적으로 본 보고서에 있는 내용을 인용 또는 전재할 경우 내용의 출처를 명시 하면 자유롭게 인용할 수 있으며, 보고서 내용에 대한 문의는 아래와 같이 하여 주시 기 바랍니다.\n□ 경 제 연 구 실 : 주 원 경제연구실장 (2072-6235, juwon@hri.co.kr) 이부형 동향분석팀장 (2072-6306, leebuh@hri.co.kr) 이택근 연구위원 (2072-6366, tklee@hri.co.kr) 신지영 연구위원 (2072-6240, jyshin@hri.co.kr) 노시연 연구위원 (2072-6248, syroh@hri.co.kr) v EXECUTIVE SUMMARY i Executive Summary □2025년 한국 경제 전망(수정) - 2025년 경제성장률, 1.0%p 하향조정한 0.7% ￭ 한국 경제 수정 전망의 배경 현대경제연구원은 '25년 한국 경제성장률에 대하여 지난 전망치 1.7%('24년 12월 전망 시점)에서 0.7%로 1.0%p 하향조정하였다. 하향조정의 가장 큰 이유는 소비와 투자의 내수 불황이 장기화되는 가운데, 경기 선행지표들의 뚜렷한 반등 신호를 포 착할 수 없기 때문이다. 또한, 향후 대외 불확실성(트럼프 관세 인상 정책의 파급 영향)의 부정적 영향이 나타날 것이기 때문에, 이제부터 수출 경기 침체가 본격화될 가능성이 높다고 분석된다. 나아가 '24년 2분기부터 시작된 불황이 만 1년 동안이나 지속 중인 상황임에도, 경기 부양을 위한 적극적인 정책적 대응이 보이지 않는다는 점까지 고려할 때, 한국 경제에 대해 긍정적 시각을 가지기 어렵다고 판단된다. 향후 한국 경제는 수출 경기와 내수 경기가 동반 침체되는 ‘절대 수요 부족’ 국 면에 직면할 것이며, 이에 따라 「기업 실적 악화 → 고용 시장 냉각 → 소비 침체 → 시장 수요 위축 → 기업 실적 악화」의 경기 악순환에 빠질 가능성이 우려된다. 내수 부문은 고금리에 따르는 소비자 실질구매력의 정체와 성장과 고용에 대한 국 민경제적 영향이 매우 높은 건설투자의 침체로, 민간 부문 스스로의 회복력이 거의 고갈된 상황이다. 과거의 경험상 한국 경제가 불황 국면에서 탈출하는 전형적인 경 로는 수출 경기 호조가 내수 회복으로 이어지는 것이나, 올해 교역 환경의 급격한 악화로 수출의 경제 성장 견인력을 기대하기 어렵다고 판단된다. 따라서 기본 시나리오 하에서는 '25년 한국 경제의 0%대의 초 저성장 국면 탈출은 불가능해 보이며, 긍정적 시나리오상 ① 교역 환경의 주목할만한 개선이 이루어지 거나 ② 적극적인 경기부양책이 대응될 경우 1%대 초반의 성장률을 달성할 여지는 있다고 판단된다.\n￭ 한국 경제 수정 전망 ① 경제 성장 GDP증가율 2.0% ⇨ 0.7% (2024) (2025) 한국 경제는 '24년 내수 침체 속 수출 호조 국면에서 '25년에는 내수와 수출이 모 EXECUTIVE SUMMARY ii 두 침체되는 국면으로의 진입이 전망된다. '25년 연간 경제성장률은 1% 미만을 기 록할 가능성이 높으며, 예상치 못한 대내외 경제 충격이 발생할 경우 특정 분기의 추가적인 역성장의 출현도 가능한 상황이다. 참고로 '60년 이후 66년 동안 낮은 순서대로 연간 경제성장률을 살펴보면, '98년 (△4.9%), '80년(△1.5%), '20년(△0.7%)에 이어 '25년(연구원 전망치 0.7%)이 네 번째 에 해당된다. < 1960년 이후 낮은 순서 기준 연간 경제성장률 > 자료: 한국은행. 특히, 수출과 내수가 뚜렷한 반등의 계기를 만들지 못하면서 민간경제주체들의 심 리 회복도 기대할 수 없어 장기불황 시대가 시작될 가능성도 배제하기 어렵다고 판 단된다. 이에 따라 '25년 경제성장률은 '24년의 2.0%보다 크게 낮은 0.7%를 기록할 것으로 전망된다. '25년 성장률은 잠재성장률 수준인 2% 내외에 크게 못 미치는 0.7%로 예상되며, 기존 '24년 12월 전망치인 1.7%에서 1.0%p 하향조정한 것이다. 다 만, '24년의 상고하저 영향으로 상반기 경제성장률은 전년동기대비 0.4%, 하반기 경 제성장률은 0.9%의 상저하고의 추세를 보일 것으로 예상된다.\n② 내수 민간소비증가율 1.1% ⇨ 0.9% (2024) (20254) 높은 물가 수준·고금리로 인한 실질구매력의 정체와 더불어, 경제 상황 악화에 따른 소득 부진으로 소비 심리가 개선되기 어렵다고 판단된다. 가계의 현재 경기 판단이나 향후 경기 상황에 대한 전망을 보여주는 CSI는 여전히 정체되는 모습을 보이고 있다. '25년 전반적인 소비 여건을 보면, 실물 경제 펀더멘틀에 비해 높은 EXECUTIVE SUMMARY iii 금리와 물가, 근로/사업소득의 정체 등으로 '24년에 비해 개선되지 못할 것으로 예 상된다. 즉, 민간의 자생적 소비 회복력은 매우 취약한 상황이며, 민간소비의 침체 를 정부소비 확대로 보완하지 않는 이상 절대적인 시장 수요 부족에 직면할 것으로 전망된다. 이에 따라 '25년 민간소비증가율은 '24년1.1%에서 낮아진 0.9%를 기록할 것으로 전망된다. 다만, '25년 민간소비의 추세는 하반기 불확실성의 완화 또는 민 간 주체들의 불확실성에 대한 내성 강화로, 상저하고의 모습일 것으로 보이며 상반 기 전년동기대비 0.6%, 하반기 1.2%로 예상된다.\n설비투자증가율 1.6% ⇨ 1.2% (2024) (2025) 대내외 시장 불확실성으로 투자 여건이 크게 개선되지 않을 것으로 보이나, 디지 털 전환 및 그린 전환 등 신산업 투자 수요 등은 확대될 것으로 전망된다. 기업 심 리의 침체 국면이 장기화되는 가운데, 자본 조달 비용의 급증, 자본재 가격 상승 등 의 영향으로 투자 여력도 취약한 상황이다. 특히, 통상 환경의 악화(관세 전쟁), 해 외시장 불확실성(미국 경기 하강, 중국 회복 지연) 등에 따른 글로벌 시장의 수요 침체로 제조업의 생산 설비 확대 동기가 높지 않을 것으로 예상된다. 다만, DT(AI, 데이터센터), GT(신재생에너지 인프라) 등의 신산업 투자 수요는 지속될 것으로 보 인다. 이에 따라 '25년 설비투자증가율은 '24년의 1.6%보다 낮아진 1.2%를 기록할 것으로 전망된다. 설비투자증가율은 상반기에 전년동기대비 4.0%를 유지하다가, 하 반기에 들어 역(逆) 기저효과가 작용하면서 △1.5%에 그칠 것으로 예상된다.\n건설투자증가율 △3.0% ⇨ △6.1% (2024) (2025) 건설수주 침체의 장기화가 건설투자의 부진으로 이어질 것으로 보이나, 하반기 시 장 여건이 다소 개선되면서 투자가 미약한 반등을 보일 것으로 기대된다. 부문별로 보면 토목SOC 분야의 경우 '25년 정부 예산에서의 재정투자 규모가 25.4조 원으로 '24년 26.4조 원 대비 3.8% 감소하였다. 특히, 건설투자의 약 75%를 차지하는 건 축·건물건설 분야의 경우, 공급 측면에서 고물가에 따른 공사비와 고금리로 인한 금융조달비용이 급등한 상황이고, 수요 측면에서도 경제적·제도적 요인으로 부동 산 시장 활성화가 어려운 상황이다. 나아가 건축·건물건설투자의 선행지표인 건축 허가 및 착공 면적이 큰 폭으로 감소했기 때문에, 향후 업황 불황 국면이 장기화될 가능성이 매우 높다고 판단된다. 이에 따라 '25년 건설투자증가율은 '24년의 △3.0% 에 이어 △6.1%를 기록할 것으로 전망된다. 상반기와 하반기 모두 감소세를 지속할 것이나, 하반기에는 기저효과의 영향으로 감소폭이 다소 축소될 가능성이 존재한다.\nEXECUTIVE SUMMARY iv ③ 대외 거래 수출증가율 8.1% ⇨ △4.0% (2024) (2025) 수출증가율은 '24년 8.1%에서 '25년 △4.0%의 감소세로의 전환이 전망된다. 상·하 반기별로도 연중 내내 감소세를 벗어나기 어려워 보이며, 미국과 중국 시장에 대한 의존도가 높은 수출 산업일수록 실적의 부침이 상대적으로 심할 것으로 판단된다. 다만, 향후 한국에 부과된 상호관세 협상의 결과와 미·중 간 관세 전쟁의 향방에 따라, 하반기 수출 경기의 방향성이 결정될 것으로 예상된다.\n수입증가율 △1.7% ⇨ △0.5% (2024) (2025) 수입증가율은 '24년 △1.7%에서 '25년 △0.5%의 감소세가 이어질 전망이다. 상·하 반기별로 보면 상반기 전년동기대비 △2.0%, 하반기 1.0%로 예상된다. 내수 침체로 수입재에 대한 수요가 위축되면서 상반기에는 감소세를 기록할 것으로 보이나, 하 반기에 들어 다소의 경기 반등과 기저효과의 영향으로 소폭 증가세로 전환될 가능 성이 존재한다.\n무역수지 518억 달러 ⇨ 276억 달러 (2024) (2025) 수출 경기 침체가 장기화되는 가운데, 수출 감소 폭이 수입 감소 폭보다 커, 무역 수지 흑자는 '24년 518억 달러에서 '25년 276억 달러로 축소될 전망된다. '25년 상반 기 무역수지는 148억 달러를 기록할 것으로 보이며, 하반기에 들어서는 수입이 다 소 증가하면서 128억 달러 수준으로 감소할 것으로 예상된다. 한편, 가능성은 높지 않으나, 하반기에 수출 경기가 반등할 수 있는 여건이 조성된다면 무역수지 흑자 규모가 예상치를 상회할 수도 있다.\n경상수지 990억 달러 ⇨ 490억 달러 (2024) (2025) 경상수지는 '24년 990억 달러에서 '25년 490억 달러로 크게 낮아질 것이다. '25년 상반기 경상수지는 260억 달러를 기록할 것으로 보이며, 하반기에 들어서는 그보다 낮은 230억 달러가 예상된다. 경상수지 흑자 규모의 감소는 주로 재화 교역에서 상 품수지(무역수지) 흑자 규모가 감소하는 영향 때문이다.\nEXECUTIVE SUMMARY v ④ 물가 및 고용 소비자물가상승률 2.3% ⇨ 1.7% (2024) (2025) 공급측 인플레이션 압력의 약화가 지속되는 가운데, 경기 침체에 따른 수요측 인 플레이션 압력도 낮아질 것으로 전망된다. 국제 유가, 국제 원자재 가격이 글로벌 시장 수요 하락으로 낮은 수준을 기록할 것으로 보여 공급측 물가 상승 압력의 완 화가 기대된다. 한편, 수입물가를 높이는 원인 중 하나인 원/달러 환율은 높은 수준 을 유지할 것으로 예상된다. 또한, 0%대의 극심한 침체 국면이 이어지면서 기대인 플레이션 심리(수요측 인플레이션 압력)가 약화되어, 전반적인 인플레이션 압력은 낮아질 가능성이 존재한다. 다만, 주요 원자재 수출 지역에서의 전쟁, 수출 규제 확 산 등의 예기치 못한 글로벌 공급망 불안 이슈가 발생할 경우 공급측 인플레이션 압력이 다시 높아질 가능성도 배제하기 어렵다. 이에 따라 소비자물가상승률은 '24 년 2.3%에서 '25년 1.7%로 낮아질 전망이다. '25년 상반기에는 2% 내외 수준을 보일 것으로 예상되나, 하반기에 들어 1%대의 물가상승률이 예상된다.\n실업률 2.8% ⇨ 3.3% (2024) (2025) 실업률은 '24년 2.8%에서 '25년 3.3%로 높아질 전망이다. 전반적인 경제 상황 침체 의 영향으로 경제의 고용창출력이 크게 약화되면서 실업률이 크게 높아질 것으로 전망된다. 특히, 불황 국면에서 기업들이 경력자를 선호하는 구인 특성을 보인다는 점을 고려할 때, 청년층 실업 문제가 심각한 수준에 이를 가능성이 높아 보인다.\n취업자수증감 16만명 ⇨ 15만명 (2024) (2025) 신규취업자수(전년동기대비 취업자수증감)는 '24년 16만 명에서 '25년 15만 명으로 소폭 감소할 전망이다. 상·하반기별로 보면 상반기에는 16만 명, 하반기에는 14만 명 수준을 기록할 것으로 예상된다. 신규취업자수의 감소 폭이 크지 않은 이유는 최근의 고용 시장 상황에서 찾아볼 수 있는데, 제조업이나 건설업에서의 고임금자 가 서비스업 내 저임금 업종으로 전환되면서 전체 신규 일자리 숫자 자체가 크게 변화하지 않은 영향인 것으로 판단된다.\n￭ 시사점 한국 경제가 대내외 불확실성을 극복하고 성장률 0%대의 경제 위기 국면 탈출에 성공하기 위해서는, 첫째, 사상 네 번째의 성장 쇼크를 극복하기 위해, 현 상황에 EXECUTIVE SUMMARY vi 대한 위기 의식을 가지고 보다 적극적인 경기 부양 정책 기조로의 전환이 절실하 다. 둘째, 트럼프 2기 행정부의 관세정책 변화 양상 및 주요국과의 협상 프로세스 등에 대한 모니터링 강화를 통해 국익 최대화를 위한 협상 전략을 수립하는 한편, 통상전략 전반의 재점검 및 보완책 마련 등을 통해 피해 최소화 및 수출 경쟁력 유지를 꾀해야 한다. 셋째, 정책 이니셔티브 발현을 통해 민간투자를 기반으로 한 고용 및 소득 확충을 유도하는 한편, 이것이 소비 확대로 이어질 수 있는 경제 선 순환 구조를 확립해야 한다. 넷째, 경기 침체기와 미래 불확실성 고조기에 가장 큰 타격을 받을 수 있는 취약 계층에 대한 적절한 사회 안전망을 제공하여 사회 양극 화가 고착화되는 것을 막아야 한다. 다섯째, 사회통합을 기반으로 경제·사회의 역 동성 복원 노력을 통해 중장기적으로 한국 경제가 지속 성장할 수 있는 기반을 확 보해야 한다.\n< 현대경제연구원의 2025년 한국 경제 전망표 (2025년 4월) > 구 분 2023 2024 2025(E) 상반 하반 연간 상반 하반 연간 국 민 계 정 경제성장률 (%) 1.4 2.8 1.3 2.0 0.4 0.9 0.7 민간소비 (%) 1.8 1.0 1.3 1.1 0.6 1.2 0.9 건설투자 (%) 1.5 0.4 △6.1 △3.0 △10.0 △2.0 △6.1 설비투자 (%) 1.1 △1.8 5.1 1.6 4.0 △1.5 1.2 대 외 거 래 경상수지 (억 달러) 355 402 589 990 260 230 490 무역수지 (억 달러) △103 230 289 518 148 128 276 수출증가율 (%) △7.5 9.1 7.2 8.1 △4.3 △3.7 △4.0 수입증가율 (%) △12.1 △6.4 3.4 △1.7 △2.0 1.0 △0.5 소비자물가상승률 (%) 3.6 2.8 1.8 2.3 2.0 1.5 1.7 실업률 (%) 2.7 3.1 2.5 2.8 3.3 3.4 3.3 취업자수 증감 (만 명) 33 22 10 16 16 14 15 2025년 한국 경제 전망(수정) 1 1. 대외 경제 환경 변화 ① 세계 경제 전망 ¡ (세계 경제) 트럼프 관세 정책의 영향으로 세계 경제의 저성장 국면으로의 진입과 교역 환경의 악화가 전망 - '25년 세계 경제의 성장 속도는 글로벌 통상 환경 악화로 '24년보다 크게 하 락할 것으로 전망되며, 이에 따라 교역증가율도 크게 하락할 것으로 전망 ․ IMF 4월 전망에 따르면 '25년 세계 경제성장률은 2.8%로 '24년의 3.3%에서 크게 하락할 것으로 전망함 ․ 또한, '25년경제성장률은 지난 1월전망치3.3%에서 0.5%p 하향조정한 것임 - 한편, '25년 국제교역 환경은 트럼프 통상정책의 영향으로 크게 악화되면서 글로벌 교역 증가율이 매우 낮은 수준을 기록할 것으로 전망 ․ 선진국의 수입 수요가 정체되는 가운데, 신흥국 및 개발도상국 수입 수요 증가율이 크게 하락하면서 세계 교역증가율이 낮은 수준에 머물 것으로 예상됨 ․ IMF 4월 전망 통계 기준으로 상품 교역증가율은 '24년 2.5%에서 '25년 1.3%로 하락할 전망임 < 세계 경제성장률 전망 > < 국제 교역(상품) 증가율 전망 > 자료: IMF WEO(April 2025).\n자료: IMF WEO(April 2025).\n2025년 한국 경제 전망(수정) 2 ¡ (선진국) 미국 경제의 경기 하강이 예상되는 가운데, 유로존은 경기 회복이 지연되면서 0%대의 성장률을 기록할 전망 - (미국) 트럼프 관세 정책 발 경기 둔화 또는 침체의 가능성이 높아 잠재성장 률에 미치지 못하는 저성장 국면에 진입할 것으로 예상 ․ IMF는 최근 '25년 미국 경제성장률을 '24년2.8%보다 크게 낮은 1.8%로 예 측하였는데, 주요 IB 전망치는 평균 1.2%로 더 부정적인 시각을 보임 ․ 한편, 최근 주요 기관들의 미국의 경기 침체 확률이 높아지는 모습을 보이 고 있는데, 그 가능성은 향후 트럼프 행정부가 확정하는 관세 인상 정책의 강도에 달려 있다고 판단됨 - (유로존) 저성장에 따른 기저효과가 작용할 것으로 보이나, 글로벌 관세 전쟁 의 격화로 0%대의 낮은 경제성장률을 기록할 것으로 전망 ․ '25년 유로존 경제성장률은 '24년 수준0.9%과 비슷한 0.8%에 그칠 것으로 예상되며, 역내 주요 경제권인 독일0.0%, 프랑스0.6%, 이탈리아0.4%의 저성 장이 지속될 것으로 예상됨 ․ 다만, 독일의 대규모 재정 부양책에 따른 부채 브레이크(Schuldenbremse) 완화, 인프라 투자를 위한 5,000억 유로의 기금 신설 등을 포함한 헌법 개 정을 발표한 점과 유로존 내 다른 국가들과는 달리 스페인이 양호한 경제 흐름성장률 2.5%을 보이는 점은 경기 상방 요인으로 작용할 전망임 < 미국 경제성장률 추이 및 전망 > < 유로존 경제성장률 추이 및 전망 > 자료: IMF WEO(April 2025), Bloomberg1).\n자료: IMF WEO(April 2025).\n1) IB는 JP Morgan, Morgan Stanley, Fitch 3사 평균 전망치.\n2025년 한국 경제 전망(수정) 3 ¡ (신흥시장 및 개도국) '25년 전반적인 신흥시장 경제 상황은 '24년보다 둔화 될 것으로 예상되나, 각국의 내수 경제가 미국 관세 정책의 악영향을 상쇄하 는 정도에 따라 차이가 있을 전망 - (중국) 외수 경기가 크게 위축될 것으로 보이는 가운데 정부의 경기 부양책 규모에 따라 경제 성장 속도가 결정될 것으로 전망 ․ 재정 적자율 목표 GDP 대비 4% 상향, 소비 진작 특별행동 방안 추진 등 정부의 적극적인 내수 부양책이 대외 여건 악화로 인한 경기 하방 압력을 일부분 상쇄할 것으로 예상됨 ․ 단, 주택 시장 침체, 디플레이션물가 하락 등은 여전히 내수 회복의 제약 요인으로 작용할 가능성이 높아 정부 목표치 5% 달성 가능성은 불확실함 - (인도) 우호적이지 않은 대외 여건 속에서도 민간 소비가 확대되며 안정적인 성장세를 유지할 전망 ․ 글로벌 불확실성 확대 등에도 농촌 지역을 중심으로 소비가 확대되며 다 른 경제권에 비해 상대적으로 양호한 성장률을 기록할 것으로 예상됨 ․ 제조업 기반 투자, 인프라 확대를 위한 정부의 재정정책 및 세제 개편 등 도 안정적인 경제 성장에 기여할 것으로 보이며, 이에 인도 정부는 6% 후 반대의 경제성장률을 전망함 < 중국 경제성장률 추이 및 전망 > < 인도 경제성장률 추이 및 전망 > 자료: IMF WEO(April 2025).\n자료: IMF WEO(April 2025).\n2025년 한국 경제 전망(수정) 4 - (ASEAN) 미국의 관세 인상 정책으로 인한 타격이 큰 지역 중 하나로 뚜렷한 성장 둔화세를 보일 전망 ․ 미국은 ASEAN의 주요 수출 시장으로 캄보디아49%, 베트남46%, 태국36% 등 주요 ASEAN 국가에 적용된 상호관세율은 ASEAN의 전반적인 수출 경 기에 타격을 줄 것으로 예상됨 ․ 또한, 중국과의 경제 및 공급망 협력 수준이 높다는 점, 미국으로 수출되 지 못한 중국산 제품이 역내로 유입되며 자국 산업이 위축될 가능성이 높 다는 점 등도 경기 둔화세를 심화시키는 요인임 ․ 한편, 물가 안정세, 관광 산업의 회복세 등은 경기 하방 압력을 다소 완화 할 것으로 기대됨 < IMF의 주요국 경제성장률 전망(%) > 구 분 2022 2023 2024 2025(E) 세계 경제성장률 3.6 3.5 3.3 2.8 선진국 2.9 1.7 1.8 1.4 미 국 2.5 2.9 2.8 1.8 유로지역 3.5 0.4 0.9 0.8 신흥국 및 개발도상국 4.1 4.7 4.3 3.7 아시아신흥국 4.7 6.1 5.3 4.5 중 국 3.1 5.4 5.0 4.0 인 도 7.6 9.2 6.5 6.2 ASEAN5 5.5 4.1 4.6 4.0 중남미 4.2 2.4 2.4 2.0 중동 및 중앙아시아 5.5 2.2 2.4 3.0 동유럽 0.5 3.6 3.4 2.1 사하라 이남 아프리카 4.1 3.6 4.0 3.8 세계 교역량증가율 5.7 1.0 3.8 1.7 자료: IMF WEO(April, 2025).\n2025년 한국 경제 전망(수정) 5 ② 주요 가격 변수 동향과 전망 ¡ (금리) 미 FED의 금리 인하 시기의 불확실성이 여전히 존재하는 가운데, 이 에 따라 다른 중앙은행들의 금리 인하 속도가 빠르지 않을 가능성 상존 - 최근 미 FED는 관세 인상에 따른 물가 불안을 우려하는 시각이 지배적이나, 미국 실물 경제의 침체 가능성도 제기되는 상황이기 때문에 금리 인하 속도 에 대한 시장의 컨센서스가 확고하지 않은 상황 ․ 이미 빠른 금리 인하에 나선 ECB의 경우 추가적인 인하 폭이 크지 않을 가능성이 있으며, BOJ는 완만한 인상 추세를 유지할 것으로 전망됨 ․ 한편, 경화硬貨, hard currency국이 아닌 한국의 입장에서는 환율 불안 이슈 로 BOK의 금리 인하 속도를 FED에 맞추는 전략을 취할 것으로 판단됨 < FED-FOMC 점도표 > < IB의 주요국 정책금리 전망 > 2024 2025(E) Q4 Q1 Q2 Q3 Q4 FED (%) 4.50 4.50 4.50 4.25 4.00 BOJ (%) 0.25 0.50 0.50 0.75 0.75 ECB (%) 3.15 2.65 2.15 2.15 2.15 BOK (%) 3.00 2.75 2.50 2.25 2.25 자료: FOMC(December 2024 & March 2025).\n자료: Bloomberg.\n¡ (환율) 달러화 가치 하락이 전망되는 가운데 국내 정치 불확실성 해소로 하 반기로 갈수록 원화 약세가 완화할 것으로 기대 - 글로벌 달러화 약세 전환으로 원/달러 환율은 소폭 하락할 것으로 예상 ․ 달러화 가치는 트럼프 2기 행정부 출범 이후 관세 인상 등 정책 불확실성 확대에 따른 美 경기둔화 우려, 금리 인하 등으로 약세가 전망됨 2025년 한국 경제 전망(수정) 6 ※ 달러인덱스(IB, 4월): 106.7 ('25.Q1) → 103.0 (Q2) → 102.0 (Q3) → 100.9 (Q4) ․ 원화는 달러화 약세 전환이 전망되는 가운데 하반기 이후 정치적 불확실 성이 해소됨에 따라 약세가 완화할 것으로 기대됨 ․ 단, 내·외수 경기 동시 악화로 인한 펀더멘털 우려 지속, 원화와 동조성 이 높은 위안화 약세 지속 등 하방 요인이 상존함에 따라 4분기 기준 원/ 달러 환율은 1,400원대 초중반 수준으로, 하락 폭은 크지 않을 전망임 < 최근 원/달러 환율 추이 > < IB 주요 환율 전망 > 2024 2025(E) Q4 Q1 Q2 Q3 Q4 달러/유로 1.04 1.08 1.09 1.10 1.11 엔/달러 157 150 146 144 142 위안/달러 7.30 7.26 7.35 7.35 7.35 원/달러 1,479 1,474 1,463 1,455 1,440 자료: 한국은행.\n자료: Bloomberg.\n¡ (국제 유가 및 원자재가) '25년 국제 유가는 '24년 대비 하락세가 전망되며, 국제 원자재 가격은 부문별 차별화 전망 - 국제 유가는 트럼프 2기 행정부의 고강도 관세 정책에 따른 수요 둔화 우려 확대로 배럴당 60달러대 후반대 수준 전망 ․ 미국이 시장 예상을 상회하는 고율의 관세 정책을 발표함에 따라 세계 수 요 둔화 우려가 확대되면서 수요측 하방 압력이 크게 높아질 것으로 보임 ․ 공급 측면에서도 OPEC+가 4월부터 감산을 완화하며 하방 압력이 확대되 었으나, 최근 보상 감산 계획생산 쿼터 초과 생산 국가에 대한 추가 감산 조치이 발표되면서 향후 실질적인 공급 확대 여부에 대해서는 불확실성이 상존함 ․ 한편, 달러화 약세, 미국의 對이란 제재 강화, 지정학 리스크 지속 등 상방 요인의 혼재로 큰 폭의 하락세는 제한적일 것으로 전망됨 2025년 한국 경제 전망(수정) 7 < 세계 주요국 원유 소비량 (2023년, 1,000배럴/日) > < 국제 유가 전망 > 순위 국가 소비량 점유율 World 100,221 100.0% 1 US 18,984 18.9% 2 China 16,577 16.5% 3 India 5,446 5.4% 4 Saudi 4,052 4.0% 5 Russia 3,635 3.6% 6 Japan 3,366 3.4% 7 Korea 2,797 2.8% 8 Brazil 2,567 2.6% 9 Canada 2,351 2.3% 10 Mexico 1,962 2.0% 자료: British Petroleum.\n자료: Bloomberg. - 글로벌 시장 수요 둔화 우려로 에너지 및 광물 등 상품가격은 하락할 것으로 예상되나, 이상 기후로 음식료·농산물 등의 가격은 불확실성이 높은 상황 ․ 美 관세정책에 따른 세계 경제 성장 둔화가 전망됨에 따라 원유 등 에너 지와 구리 등 광물 가격은 하락할 것으로 전망되는 한편, 작황 악화 등의 영향으로 음식료·농산물 가격의 불안정성은 지속될 것으로 예상됨 ․ 한편, 관세정책의 변동성이 매우 높아 세계 수요와 원자재 가격 향방에 대 한 불확실성이 상존하는 가운데, 교역 환경 악화에 따른 글로벌 공급망 훼 손 등으로 원자재 가격이 상승할 가능성도 배제할 수 없음 < 농산물 및 광물 원자재 가격 지수 추이 > < 항목별 원자재 가격 지수 전망 > 자료: 주: 현대경제연구원.\nWorld Bank Commodity Price Data를 이 용한 지수화.\n자료: IMF WEO(April 2025).\n2025년 한국 경제 전망(수정) 8 2. 최근 한국 경제 경기 동향 ① 경기(경제성장률) ¡ (역성장 현실화) 한국 경제는 1분기 현재 경기지수 상 반등하는 모습이나, 내 수와 수출이 모두 크게 침체되면서 경기 회복의 가능성은 희박한 상황 - '25년 1분기 경제성장률속보치은 전기비 △0.2%, 전년동기대비로도 △0.1%의 역(逆)성장을 기록 ․ 한편, '25년 1분기에 민간소비전기비△0.1%, 설비투자△2.1%, 건설투자△3.2%, 수출△1.1% 등 모든 수요 부문이 감소세를 기록함 - 다만, 동행지수순환변동치와 선행지수순환변동치가 2개월 연속 상승세를 보 이고 있어, 1분기 경기 저점 형성의 가능성이 다소 높아지는 것으로 판단 ․ 현 경기상황을 보여주는 동행지수순환변동치는 3월 현재 98.8p로 1월 이후 상승세를 지속 중임 ※ 동행지수순환변동치: '24년 12월 98.8p, '25년 1월 98.4p, 2월 98.5p, 3월 98.8p ․ 또한, 미래 경기 방향을 예고하는 선행지수순환변동치도 3월 현재 100.6p 로 1월 이후 상승세를 이어감 ※ 선행지수순환변동치: '24년 12월 100.7p, '25년 1월 100.3p, 2월 100.4p, 3월 100.6p < 분기 경제성장률 > < 경기 동행 및 선행지수 순환변동치 > 자료: 한국은행.\n자료: 통계청.\n2025년 한국 경제 전망(수정) 9 ② 내수 ¡ (민간소비) 가계 심리 냉각과 실질 구매력 약화에 따른 전방위적인 소비 침 체가 장기화 - 재화 중심의 소비 지표인 3월 소매판매는 전월비로는 감소하였으나 전년동월 비 기준으로는 증가 ․ 소매판매 전월비 증가율은 2월 1.9%의 증가세에서 3월에 △0.3%의 감소세 로 전환됨 ※ 소매판매액지수 증가율(MoM): '24년 11월 △0.7%, 12월 0.5%, '25년 1월 △ 0.6%, 2월 1.9%, 3월 △0.3% ※ 소매판매액지수 증가율(YoY): '24년 11월 △2.6%, 12월 △2.1%, '25년 1월 0.2%, 2월 △1.8%, 3월 1.5% - 소비 항목별로 1년 전에 비해 준내구재가 감소하였으나, 내구재와 비내구재 는 증가세를 기록 ․ 3월 중 내구재 소비는 전년동월비 1.3%의 증가세를 기록하였으며, 비내구 재도 소비도 0.6%의 증가세를 기록함 ※ 내구재소매판매액지수 증가율(YoY): '24년 11월 △6.2%, 12월 △6.6%, '25년 1 월 △8.9%, 2월 14.1%, 3월 4.3% ※ 비내구재판매액지수 증가율(YoY): '24년 11월 △1.7%, 12월 △0.7%, '25년 1월 4.6%, 2월 △6.9%, 3월 0.6% < 소매판매액지수 증가율 > < 상품군별 소매판매액지수 증가율 > 자료: 통계청.\n자료: 통계청.\n2025년 한국 경제 전망(수정) 10 ¡ (설비투자) 고금리에 따른 자금조달비용 급증, 내외수 시장 불확실성 등으로 투자 침체가 지속 - 3월 설비투자는 주력 부문인 ICT 투자가 크게 감소하면서 전체 설비투자의 침체를 유발 ․ 3월 설비투자지수 증가율은 2월 전월비 21.3%의 증가세에서 △0.9%의 감 소세로 전환됨 ※ 설비투자지수 증가율(MoM): '24년 11월 △1.7%, 12월 7.2%, '25년 1월 △ 17.2%, 2월 21.3%, 3월 △0.9% ․ 특히, 설비투자의 핵심인 3월 ICT투자가 전월비 기준으로 △7.9%의 감소세 를 기록함 ※ ICT설비투자지수 증가율(MoM): '24년 11월 △0.4%, 12월 4.0%, '25년 1월 △ 8.0%, 2월 6.7%, 3월 △7.9% - 한편, 설비투자 선행지표인 자본재수입액증가율과 국내기계수주액증가율은 올해 들어 기저효과의 영향으로 상승세를 지속 중 ․ 자본재수입액은 최근 기저효과가 작용하면서 증가율 상승세가 지속 중임 ※ 자본재수입액증가율(YoY): 1월 0.5%, 2월 10.9%, 3월 25.2% ․ 국내기계수주액 증가율도 1월 이후 3개월 연속 증가세를 기록함 ※ 국내기계수주액증가율(YoY)2): 1월 18.6%, 2월 2.0%, 3월 14.8% < 설비투자지수 증가율 > < 국내기계수주액 및 자본재수입액 증가율 > 자료: 통계청.\n자료: 통계청, 한국무역협회.\n2) 국내기계수주액(선박·선박용내연기관제외) 증가율의 실제치이며, 그림은 3개월 이동평균치.\n2025년 한국 경제 전망(수정) 11 ¡ (건설투자) 동행지표인 건설기성액과 선행지표인 건설수주액이 모두 감소세 를 시현 - 동행지표인 건설기성은 민간부문이 크게 침체되어 감소세를 기록 ․ 3월 건설기성액 증가율전년동월비은 14.0%로 '24년 5월 이후 11개월 연속 감소세를 지속 중임 ※ 건설기성 증가율(YoY): '24년 11월 △11.3%, 12월 △6.2%, '25년 1월 △ 26.7%, 2월 △19.5%, 3월 △14.0% ․ 공공 부문이 소폭 증가세를 보였으나, 민간 부문은 감소세를 지속함 ※ 공공건설기성 증가율(YoY): '24년 11월 1.2%, 12월 △2.7%, '25년 1월 △ 8.2%, 2월 △11.0%, 3월 0.7% ※ 민간건설기성 증가율(YoY): '24년 11월 △13.8%, 12월 △6.0%, '25년 1월 △ 29.5%, 2월 △21.3%, 3월 △17.5% - 향후 건설 경기를 예고하는 건설수주액선행지표은 3월에 들어 민간 부문이 소폭 반등하였으나 공공 부문이 큰 폭으로 침체 ․ 건설수주증가율은 2월 전년동월비 1.8%의 증가세에서 3월에 △8.7%의 감 소세로 전환됨 ※ 건설수주 증가율(YoY): '24년 11월 67.9%, 12월 △12.5%, '25년 1월 △15.5%, 2월 1.8%, 3월 △8.7% ※ 공공건설수주 증가율(YoY): '24년 11월 207.7%, 12월 △51.9%, '25년 1월 △ 8.5%, 2월 △15.6%, 3월 △39.9% ※ 민간건설수주 증가율(YoY): '24년 11월 25.8%, 12월 37.8%, '25년 1월 △ 17.1%, 2월 8.7%, 3월 3.9% < 발주자별 건설기성액 증가율 > < 발주자별 건설수주액 증가율 > 자료: 통계청.\n자료: 통계청.\n2025년 한국 경제 전망(수정) 12 ③ 대외 거래 ¡ (수출입) 수출 경기가 약화되는 가운데, 내수 부진으로 수입 물량은 감소세를 기록 - 올해 들어 수출 경기 둔화 추세가 나타나고 있어, 비록 2월과 3월 수출증가 율이 플러스를 기록하고 있으나 향후 감소세로의 전환 가능성이 높다고 판단 ․ 2월과 3월 수출증가율은 각각 전년동월대비 0.7% 및 3.1%로 플러스를 기 록하였으나, 1월△10.1%까지 고려한 1분기 수출증가율은 전년동기대비 △ 2.1%의 감소세를 보임 ※ 수출액 증가율: '24년 12월 6.6%, '25년 1월 △10.1%, 2월 0.7%, 3월 3.1% ․ 한편, 3월 통계 기준으로 중국 시장에 대한 수출이 감소세를 기록하고 있 으며, 대미 수출은 증가세를 보였지만 관세 인상 조치를 앞둔 기업들의 선 제적 수출 물량 확대 전략에 기인한 바가 크다고 생각됨 - 3월 수입증가율은 소폭 플러스를 기록하였으나, 내수 부진으로 국내 수요가 위축되면서 물량 기준으로는 감소세를 기록 ․ 3월 수입액은 전년동월대비 2.3% 증가하였으나, 수입물량은 전년동월대비 △5.2%의 감소세를 기록함 ※ 수입액 증가율: '24년 12월 3.3%, '25년 1월 △6.4%, 2월 0.2%, 3월 2.3% ․ 수입물량은 '24년 11월 이후 '25년 3월까지 5개월 연속 감소세를 지속중임 < 월별 수출증가율 > < 월별 수입증가율 > 자료: 한국무역협회, 산업통상자원부.\n자료: 한국무역협회, 산업통상자원부.\n2025년 한국 경제 전망(수정) 13 ¡ (무역수지 및 경상수지) 경상수지 흑자가 이어지고 있으나, 무역수지 흑자 규 모가 감소하면서 경상수지 흑자 규모도 축소 - (무역수지) 수출 경기 둔화의 영향으로 무역수지 흑자 규모가 감소하는 추세 ․ 1년 전에 비해 수입이 소폭 감소하면서 무역수지 흑자를 증가시키는 요인 으로 작용하였으나, 수출이 더 크게 감소하면서 무역 흑자 규모는 축소되 는 모습임 ․ 무역수지는 '23년 6월 이후 '25년 3월'25년 1월 제외까지 흑자 기조를 이어 가고 있으며, 올해 1~3월 누계 흑자 규모는 약 73억 달러월평균 약 24억 달 러임 ※ 무역수지: '24년 12월 65억 달러, '25년 1월 △18억 달러, 2월 42억 달러, 3월 50억 달러 - (경상수지) 서비스수지의 적자에도 무역수지상품수지가 흑자를 기록하면서 경 상수지는 흑자를 시현 ․ 경상수지는 '23년 5월 이후 흑자를 지속하고 있으며, 올해 들어서 월평균 약 50.6억 달러의 흑자를 기록함 ※ 경상수지: '24년 12월 123.7억 달러, '25년 1월 29.4억 달러, 2월 71.8억 달러 ․ 다만, '25년 1~2월 현재 서비스수지 적자의 약 59%를 차지하는 여행수지 적자가 높은 수준을 지속하면서, 전체 서비스수지는 적자가 지속됨 ※ 서비스수지: '24년 12월 △21.1억 달러, '25년 1월 △20.6억 달러, 2월 △ 32.1억 달러 < 월간 무역수지 추이 > < 월간 경상수지 추이 > 자료: 관세청.\n자료: 한국은행.\n2025년 한국 경제 전망(수정) 14 ④ 물가 및 고용 ¡ (물가) 소비자물가 상승률이 2%대 초반의 비교적 안정된 수준을 유지하는 가 운데, 최근에 들어 수입물가와 생산자물가 상승률이 하락하면서 공급측 인플 레이션 압력이 완화되는 것으로 판단 - 최근 수입물가와 생산자물가 상승률이 감소하는 추세가 지속 ․ 3월 수입물가 상승률은 고환율로 인한 상승 압력이 있으나, 국제유가가 크 게 하락하면서 2월 전년동월대비 4.3%에서 3월에 3.4%로 하락함 ※ 수입물가상승률(YoY): '24년 12월 6.8%, '25년 1월 6.5%, 2월 4.3%, 3월 3.4% ․ 3월 생산자물가상승률은 공산품 물가 상승 폭이 크지 않은 가운데, 농림수 산품 물가가 하락하면서 2월 전년동월비 1.5%에서 3월에 1.3% 하락함 ※ 생산자물가상승률(YoY): '24년 12월 1.7%, '25년 1월 1.8%, 2월 1.5%, 3월 1.3% - 소비자물가가 2% 수준의 상승률을 기록 중이며 근원물가도 비교적 안정 ․ 3월 소비자물가상승률은 농축수산물전년동월대비0.9%과 공업제품1.7% 이 안 정되었으나, 서비스2.3% 상승률이 다소 높아 2월에 이어 2%대를 유지함 ※ 소비자물가상승률(YoY): '24년 12월 1.9%, '25년 1월 2.2%, 2월 2.0%, 3월 2.1% ․ 일시적 변동 요인을 제외한 3월 근원물가상승률은 1.9%로 2월보다 높아짐 ※ 근원물가상승률(YoY): '24년 12월 1.8%, '25년 1월 1.9%, 2월 1.8%, 3월 1.9% < 생산자물가 및 수입물가 상승률 > < 소비자물가 및 근원물가 상승률 > 자료: 한국은행.\n주: 전년동월비 기준.\n자료: 통계청.\n주: 근원물가는 식료품 및 에너지 제외 기준.\n2025년 한국 경제 전망(수정) 15 ¡ (고용) 실업률이 다소 높아지는 가운데, 제조업 및 건설업 그리고 주력 경제 활동 연령대의 고용창출력이 급감 - 3월 실업률은 전년대비 상승하였으나 구직단념자는 감소 ․ 3월 실업률은 3.1%로 전년동월'24년 3월 3.0%보다 악화되었으며, 비경제활동 인구 중 구직단념자3)는 '24년 3월 39.1만 명에서 '25년 3월 35.4만 명으로 감소함 - 3월 신규취업자취업자 수 증감는 전년동월비 19.3만 명으로 2월의 13.6만 명보 다 증가하였는데, 제조업과 건설업 고용창출력이 급감하는 모습 ․ 3월 중 취업자 수 증감분전년동월비은 19.3만 명으로 2월13.6만 명보다 소폭 확대됨 ※ 취업자 수 증감(YoY): '24년 12월 △5.2만 명, '25년 1월 13.5만 명, 2월 13.6 만 명, 3월 19.3만 명 ․ 3월 중 산업별 취업자 수 증감전년동월비은 제조업 △11.2만 명, 건설업 △ 18.5만 명, 서비스업 55.8만 명임 ․ 다만, 3월 취업자수 증가는 60세 이상 연령층이 주도전년동월비 36.5만 명하 고 있으며, 청년층15~29세 일자리는 축소△20.6만 명됨 < 3월 기준 실업률 및 청년실업률 > < 주요 산업별4) 취업자 증감 > 자료: 통계청.\n자료: 통계청.\n3) 비경제활동인구(만 15세 이상 인구 중 조사대상기간에 취업도 실업도 아닌 상태에 있는 자) 중 구직단념자는 취 업 의사와 일할 능력이 있지만, 일정한 사유로 이전 4주간 구직활동을 하지 않은 사람 중 1년 안에 구직경험이 있는 자를 의미.\n4) 기타는 광업, 유틸리티, 가구내 고용활동 및 달리 분류되지 않은 자가소비생산활동, 국제 및 외국기관의 합계.\n2025년 한국 경제 전망(수정) 16 3. 한국 경제 전망 ¡ 수정 전망의 배경 - 현대경제연구원은 '25년 한국 경제성장률에 대하여 지난 전망치 1.7% '24년 12 월 전망 시점에서 0.7%로 1.0%p 하향조정 ․ 하향조정의 가장 큰 이유는 소비와 투자의 내수 불황이 장기화되는 가운 데, 경기 선행지표들의 뚜렷한 반등 신호를 포착할 수 없기 때문임 ․ 또한, 향후 대외 불확실성트럼프 관세 인상 정책의 부정적 영향이 나타날 것 이기 때문에, 이제부터 수출 경기 침체가 본격화될 가능성이 매우 높다고 분석됨 ․ 나아가 '24년 2분기부터 시작된 불황이 만 1년 동안이나 지속 중인 상황임 에도, 경기 부양을 위한 적극적인 정책적 대응이 보이지 않는다는 점까지 고려할 때, 한국 경제에 대해 긍정적 시각을 가지기 어렵다고 판단됨 - 향후 한국 경제는 수출 경기와 내수 경기가 동반 침체되는 「절대 수요 부 족」 국면에 직면할 것이며, 이에 따라 「기업 실적 악화 → 고용 시장 냉각 → 소비 침체 → 시장 수요 위축 → 기업 실적 악화」의 경기 악순환에 빠질 가능성이 우려 ․ 내수 부문은 고금리에 따르는 소비자 실질구매력의 정체와 성장과 고용에 대한 국민경제적 영향이 매우 높은 건설투자의 침체로, 민간 부문 스스로 의 회복력이 거의 고갈된 상황임 ․ 과거의 경험상 한국 경제가 불황 국면에서 탈출하는 전형적인 경로는 수 출 경기 호조가 내수 회복으로 이어지는 것이나, 올해 교역 환경의 급격한 악화로 수출의 경제 성장 견인력을 기대하기 어렵다고 판단됨 - 따라서 기본 시나리오 하에서는 2025년 한국 경제의 0%대의 초 저성장 국면 탈출은 불가능해 보이며, 매우 긍정적 시나리오상 ① 교역 환경의 주목할만 한 개선이 이루어지거나 ② 적극적인 경기부양책이 대응될 경우 1%대 초반 의 성장률을 달성할 여지는 있다고 판단 2025년 한국 경제 전망(수정) 17 ① 경제 성장 GDP증가율 2.0% ⇨ 0.7% (2024) (2025) - 한국 경제는 '24년 내수 침체 속 수출 호조 국면에서 '25년에는 내수와 수출 이 모두 침체되는 국면으로 진입 ․ '25년 연간 경제성장률은 1% 미만의 수준을 기록할 가능성이 높으며, 예상 치 못한 대내외 경제 충격이 발생할 경우 특정 분기의 추가적인 역성장 출현도 가능한 상황임 ※ '60년 이후 경제성장률이 1% 미만에 머물렀던 시기는 '80년(△1.5%), '98년(△ 4.9%), '09년(0.8%), '20년(△0.7%)의 네 번에 불과함 ․ 특히, 수출과 내수가 뚜렷한 반등의 계기를 만들지 못하면서 민간경제주체 들의 심리 회복도 기대할 수 없어 장기불황 시대가 시작될 가능성도 배제 하기 어렵다고 판단됨 - 이에 따라 '25년 경제성장률은 '24년2.0%보다 크게 낮은 0.7%를 기록할 전망 ․ '25년 성장률은 잠재성장률 수준2% 내외에 크게 못 미치는 0.7%로 예상되 며, 기존 전망치 '24년 12월 전망 1.7%에서 1.0%p 하향조정함 ․ 다만, '24년의 상고하저의 영향으로 상반기 경제성장률은 전년동기대비 0.4%, 하반기 경제성장률은 0.9%의 상저하고의 추세를 보일 것으로 예상됨 < 경제성장률 추이 및 전망 > < 주요 기관의 2025년 성장률 전망 > 자료: 현대경제연구원(실적치는 한국은행).\n자료: 각 기관 홈페이지.\n2025년 한국 경제 전망(수정) 18 ② 내수 민간소비증가율 1.1% ⇨ 0.9% (2024) (2025) - 높은 물가 수준·고금리로 인한 실질구매력의 정체와 더불어, 경제 상황 악 화에 따른 소득 부진으로 소비 심리가 개선되기 어렵다고 판단 ․ 가계의 현재 경기 판단이나 향후 경기 상황에 대한 전망을 보여주는 CSI는 여전히 정체되는 모습을 보임 ․ '25년 전반적인 소비 여건을 보면, 실물 경제 펀더멘틀에 비해 높은 물가 와 금리, 근로/사업소득의 정체 등으로 '24년에 비해 개선되지 못할 것으로 예상됨 ․ 즉, 민간의 자생적 소비 회복력은 매우 취약한 상황이며, 민간소비의 침체 를 정부소비 확대로 보완하지 않는 이상 절대적인 시장 수요 부족에 직면 할 것으로 전망됨 - 이에 따라 '25년 민간소비증가율은 '24년1.1%에서 낮아진 0.9%를 기록할 것 으로 전망 ․ 다만, '25년 민간소비의 추세는 하반기 불확실성의 완화 또는 민간 주체들 의 불확실성에 대한 내성 강화로, 상저하고의 모습일 것으로 보이며 상반 기 전년동기대비 0.6%, 하반기 1.2%로 예상됨 < 현재경기판단및향후경기전망CSI > < 민간소비증가율 추이 및 전망 > 자료: 한국은행.\n자료: 현대경제연구원(실적치는 한국은행).\n2025년 한국 경제 전망(수정) 19 설비투자증가율 1.6% ⇨ 1.2% (2024) (2025) - 대내외 시장 불확실성으로 투자 여건이 크게 개선되지 않을 것으로 보이나, 디지털 전환 및 그린 전환 등 신산업 투자 수요 등은 확대될 것으로 전망 ․ 기업 심리의 침체 국면이 장기화되는 가운데, 자본 조달 비용의 급증, 자 본재 가격 상승 등의 영향으로 투자 여력도 취약한 상황임 ․ 특히, 통상 환경의 악화관세 전쟁, 해외시장 불확실성미국 경기 하강, 중국 회 복 지연 등 글로벌 시장의 수요 침체로 제조업의 생산 설비 확대 동기가 높 지 않을 것으로 예상됨 ․ 다만, DT AI, 데이터센터, GT 신재생에너지인프라 등의 신산업 투자 수요는 지 속될 것으로 예상됨 - 이에 따라 '25년 설비투자증가율은 '24년1.6%보다 낮아진 1.2%를 기록할 것으 로 전망 ․ 설비투자증가율은 상반기에 전년동기대비 4.0%를 유지하다가, 하반기에 들 어 역(逆) 기저효과가 작용하면서 △1.5%에 그칠 것으로 예상됨 < 주요 기업경기실사지수(BSI) > < 설비투자증가율 추이 및 전망 > 자료: 한국은행, 한국경제인협회.\n자료: 현대경제연구원(실적치는 한국은행).\n2025년 한국 경제 전망(수정) 20 건설투자증가율 △3.0% ⇨ △6.1% (2024) (2025) - 건설수주 침체의 장기화가 건설투자의 부진으로 이어질 것으로 보이나, 하반 기 시장 여건이 다소 개선되면서 투자가 미약한 반등을 보일 것으로 기대 ․ 부문별로 보면 토목SOC 분야의 경우 '25년 정부 예산에서의 재정투자 규 모가 25.4조 원으로 '24년 26.4조 원 대비 3.8% 감소함 ․ 특히, 건설투자의 약 75%를 차지하는 건축·건물건설 분야의 경우, 공급 측면에서 고물가에 따른 공사비와 고금리로 인한 금융조달비용이 급등한 상황이고, 수요 측면에서도 경제적·제도적 요인으로 부동산 시장 진입이 어려운 상황임 ․ 나아가 건축·건물건설투자의 선행지표인 건축 허가 및 착공 면적이 큰 폭으로 감소했기 때문에, 향후 업황 불황 국면이 장기화될 가능성이 매우 높다고 판단됨 - 이에 따라 '25년 건설투자증가율은 '24년 △3.0%에 이어 역성장△6.1%을 기록 할 것으로 전망 ․ 상반기와 하반기 모두 감소세를 지속할 것이나, 하반기에는 기저효과의 영 향으로 감소폭이 다소 축소될 가능성이 존재함 < 건축부문 허가 및 착공 면적 추이 > < 건설투자증가율 추이 및 전망 > 자료: 국토교통부.\n자료: 현대경제연구원(실적치는 한국은행).\n2025년 한국 경제 전망(수정) 21 ③ 대외 거래 수출증가율 8.1% ⇨ △4.0% (2024) (2025) - 수출증가율은 '24년 8.1%에서 '25년 △4.0%의 감소세로 전환 전망 ․ 상·하반기별로도 연중 내내 감소세를 벗어나기 어려워 보이며, 미국과 중 국 시장에 대한 의존도가 높은 수출 산업일수록 실적의 부침이 상대적으 로 심할 것으로 판단됨 ․ 다만, 향후 한국에 부과된 상호관세 협상의 결과와 미·중 간 관세 전쟁의 향방에 따라, 하반기 수출 경기의 방향성이 결정될 것으로 예상됨 수입증가율 △1.7% ⇨ △0.5% (2024) (2025) - 수입증가율은 '24년 △1.7%에서 '25년 △0.5%의 감소세가 이어질 전망 ․ 상·하반기별로 보면 상반기 전년동기대비 △2.0%, 하반기 1.0%로 예상됨 ․ 내수 침체로 수입재에 대한 수요가 위축되면서 상반기에는 감소세를 기록 할 것으로 보이나, 하반기에 들어 다소의 경기 반등과 기저효과의 영향으 로 소폭 증가세로 전환될 가능성이 존재함 < 수출증가율 추이 및 전망 > < 수입증가율 추이 및 전망 > 자료: 현대경제연구원(실적치는 관세청).\n자료: 현대경제연구원(실적치는 관세청).\n2025년 한국 경제 전망(수정) 22 무역수지 518억 달러 ⇨ 276억 달러 (2024) (2025) - 수출 경기 침체가 장기화되는 가운데, 수출 감소 폭이 수입 감소 폭보다 커, 무역수지 흑자는 '24년 518억 달러에서 '25년 276억 달러로 축소될 전망 ․ '25년 상반기 무역수지는 148억 달러를 기록할 것으로 보이며, 하반기에 들어서는 수입이 다소 증가하면서 128억 달러 수준으로 감소할 것으로 예 상됨 ․ 한편, 가능성은 높지 않으나 하반기에 수출 경기가 반등할 수 있는 여건이 조성된다면 무역수지 흑자 규모가 예상치를 상회할 가능성도 있음 경상수지 990억 달러 ⇨ 490억 달러 (2024) (2025) - 경상수지는 '24년 990억 달러에서 '25년 490억 달러로 크게 낮아질 것으로 전 망 ․ '25년 상반기 경상수지는 260억 달러를 기록할 것으로 보이며, 하반기에 들어서는 그보다 낮은 230억 달러가 예상됨 ․ 경상수지 흑자 규모의 감소는 주로 재화교역에서 상품수지무역수지 흑자 규모가 감소하는 영향 때문임 < 무역수지 추이 및 전망 > < 경상수지 추이 및 전망 > 자료: 현대경제연구원(실적치는 관세청).\n자료: 현대경제연구원(실적치는 한국은행).\n2025년 한국 경제 전망(수정) 23 ④ 물가 및 고용 소비자물가상승률 2.3% ⇨ 1.7% (2024) (2025) - 공급측 인플레이션 압력의 약화가 지속되는 가운데, 경기 침체에 따른 수요 측 인플레이션 압력도 낮아질 것으로 전망 ․ 국제 유가, 국제 원자재 가격이 글로벌 시장 수요 하락으로 낮은 수준을 기록할 것으로 보여 공급측 물가 상승 압력의 완화가 기대됨 ․ 한편, 수입물가를 높이는 원인 중 하나인 원/달러 환율은 높은 수준을 유 지할 것으로 예상됨 ․ 또한, 0%대의 극심한 침체 국면이 이어지면서 기대인플레이션 심리수요측 인플레이션 압력가 약화되어, 전반적인 인플레이션 압력은 낮아질 가능성이 존재함 ․ 다만, 주요 원자재 수출 지역에서의 전쟁, 수출 규제 확산 등의 예기치 못 한 글로벌 공급망 불안 이슈가 발생할 경우 공급측 인플레이션 압력이 다 시 높아질 가능성도 배제하기 어려움 - 이에 따라 소비자물가상승률은 '24년 2.3%에서 '25년 1.7%로 낮아질 전망 ․ '25년 상반기에는 2% 내외 수준을 보일 것으로 예상되나, 하반기에 들어 1%대의 물가상승률이 전망됨 < 기대인플레이션율 추이 > < 소비자물가상승률 추이 및 전망 > 자료: 한국은행.\n자료: 현대경제연구원(실적치는 통계청).\n2025년 한국 경제 전망(수정) 24 실업률 2.8% ⇨ 3.3% (2024) (2025) - 실업률은 '24년 2.8%에서 '25년 3.3%로 높아질 것으로 전망 ․ 전반적인 경제 상황 침체의 영향으로 고용창출력이 크게 약화되면서 실업 률이 크게 높아질 것으로 전망됨 ․ 특히, 불황 국면에서 기업들이 경력자를 선호하는 구인 특성을 보인다는 점을 고려할 때, 청년층 실업 문제가 심각한 수준에 이를 가능성이 높다고 판단됨 취업자수증감 16만명 ⇨ 15만명 (2024) (2025) - 신규취업자수전년동기대비 취업자수증감은 '24년 16만 명에서 '25년 15만 명으로 소폭 감소할 전망 ․ 상·하반기별로 보면 상반기에는 16만 명, 하반기에는 14만 명 수준을 기 록할 것으로 예상됨 ․ 신규취업자수의 감소 폭이 크지 않은 이유는 최근의 고용 시장 상황에서 찾아볼 수 있는데, 제조업이나 건설업에서의 고임금자가 서비스업 내 저임 금 업종으로 전환되면서 신규 일자리 숫자 자체가 크게 변화하지 않은 영 향으로 판단됨 < 실업률 추이 및 전망 > < 취업자수 증감 추이 및 전망 > 자료: 현대경제연구원(실적치는 통계청).\n자료: 현대경제연구원(실적치는 통계청).\n2025년 한국 경제 전망(수정) 25 < 현대경제연구원의 2025년 한국 경제 전망표 (2025년 4월) > 구 분 2023 2024 2025(E) 상반 하반 연간 상반 하반 연간 국 민 계 정 경제성장률 (%) 1.4 2.8 1.3 2.0 0.4 0.9 0.7 민간소비 (%) 1.8 1.0 1.3 1.1 0.6 1.2 0.9 건설투자 (%) 1.5 0.4 △6.1 △3.0 △10.0 △2.0 △6.1 설비투자 (%) 1.1 △1.8 5.1 1.6 4.0 △1.5 1.2 대 외 거 래 경상수지 (억 달러) 355 402 589 990 260 230 490 무역수지 (억 달러) △103 230 289 518 148 128 276 수출증가율 (%) △7.5 9.1 7.2 8.1 △4.3 △3.7 △4.0 수입증가율 (%) △12.1 △6.4 3.4 △1.7 △2.0 1.0 △0.5 소비자물가상승률 (%) 3.6 2.8 1.8 2.3 2.0 1.5 1.7 실업률 (%) 2.7 3.1 2.5 2.8 3.3 3.4 3.3 취업자수 증감 (만 명) 33 22 10 16 16 14 15 2025년 한국 경제 전망(수정) 26 4. 시사점 첫째, 사상 네 번째의 성장 쇼크를 극복하기 위해, 현 상황에 대한 위기 의식을 가지고 보다 적극적인 경기 부양 정책 기조로의 전환이 절실하다. - (적극적인 재정정책 추진) 대내외 불확실성이 그 어느 때보다 큰 상황인 만 큼 민간 중심의 성장경로 재진입 여부가 확인될 때까지 적극적인 재정정책과 성장 친화적 경제정책 기조를 유지해야 함 ․ 국내 실물경기는 내·외수 동반 부진으로 경제 전반의 수요 압력이 약화 되는 전형적인 침체 국면이 지속될 것으로 판단됨 ․ 더구나, 韓美 간 관세협상에서 긍정적인 성과를 도출하더라도 미국의 對 세계 관세정책의 불확실성과 불투명성이 크다는 점을 고려하면 외수 회복 시기도 불투명함 ․ 따라서, 적극적인 재정정책과 더불어 성장 친화적 경제정책 기조 유지로 내수 경기 회복에 집중하는 한편, 상황 악화 시 연내 추가적인 재정 지출 확대 조치도 취할 수 있을 정도의 유연성도 갖추어야 하는 상황임 ․ 한편, 재정 여력 및 효율성을 고려할 때 경제적 파급 효과가 큰 SOC 분야 에 대한 사업 조기 발주와 함께 가계 구매력 확충과 직결된 부문의 재정 집행 속도를 높여 내수 전반의 경기 침체 방어에 주력해야 함 ․ 재정 건전성 측면에서는 경제가 위중한 상황이라는 점을 고려해 단기 세 수·세출 균형을 고집할 것이 아니라, 중기 세수·세출 균형을 위한 경제 및 재정 전략을 마련하고 실천해 나가는 것이 바람직함 - (추가적 통화정책 완화) 통화정책은 재정정책과의 정합성 확보로 경기부양효 과의 극대화를 꾀하는 한편 물가 불안 등의 우려는 미시 대응을 통해 보완할 필요가 있음 ․ 국내 경제의 수요 압력 약화로 인플레 우려는 상대적으로 낮은 것으로 판 단됨에 따라 추가적 통화 완화가 물가 부담으로 직결되지는 않을 전망임 ․ 따라서, 일시적 계절적 물가 불안 요인에 대해서는 사전에 적절한 수급 대 책을 확보해 즉시 대응이 가능하도록 하는 한편 공공요금 인상 등 정책적 물가 불안 요인은 시기와 범위 조정 등 관리 강화가 필요함 2025년 한국 경제 전망(수정) 27 ․ 또, 추가적인 통화 완화에 있어서 걸림돌로 작용하고 있는 부동산 시장과 가계부채 문제는 정책 일관성 확보를 통한 시장 기대심리 안정화, 가계대 출에 대한 총량 규제 활용 및 고정금리 대출 비중 확대 등과 같은 미시 정책 대응을 통해 보완할 필요가 있음 - (금융시장의 안정성 확보) 금융시장 급변동에 의한 경제주체의 심리 약화가 내수 부진을 가속화하지 않도록 가격 변수의 변동성 완화와 금융기관의 건 전성 제고를 위한 노력도 지속되어야 함 ․ 환율, 주가, 금리 등 금융시장 가격 변수들은 실물 경제적 측면에서 당장 큰 영향을 미치지 않지만, 심리적 측면에서 가계와 기업의 경제 활력에 우 회적인 영향을 미친다는 점을 고려할 필요가 있음 ․ 외환 및 주식 시장 등 금융시장 불안은 경제주체의 심리 악화를 통해 소 비나 투자에 악영향을 미쳐 내수 경기의 회복을 제약할 수 있음 ․ 따라서 금융시장 안전성 확보를 위한 자본 유출입 모니터링 강화, 일부 투 기 자본의 교란 행위 방지를 위한 시스템 보완 등의 노력이 필요함 ․ 특히, 글로벌 자산 시장 변동성 확대가 국내 금융기관이나 개인의 피해로 이어지지 않도록 재무 및 금융 자산 투자 건전성 감독에 주력해야 함 ․ 한편, 금융시장 안정을 위해서는 정책당국과 시장 간 의사소통의 역할도 매우 중요한 만큼 ‘포워드 가이던스(Foward Guidance)’와 실제 정책의사 결정 결과와의 간극을 좁힘으로써 정책당국에 대한 시장의 신뢰와 건전한 기대를 형성해 급변동을 예방하는 것이 중요함 둘째, 트럼프 2기 행정부의 관세정책 변화 양상 및 주요국과의 협상 프로세스 등에 대한 모니터링 강화를 통해 국익 최대화를 위한 협상 전략을 수립하 는 한편, 통상전략 전반의 재점검 및 보완책 마련 등을 통해 피해 최소화 및 수출 경쟁력 유지를 꾀해야 한다. - (주요국 협상 모니터링을 통한 보완책 모색) 트럼프 2기 행정부의 관세협상 이 관세뿐 아니라 안보(국방, 영토), 통화(환율), 첨단 기술 및 산업(반도체, 자동 차, 에너지 등) 등과 연계되어 있다는 점을 고려할 때 주요국과의 협상 과정에 대한 모니터링 결과를 협상전략에 반영할 수 있도록 해야 함 2025년 한국 경제 전망(수정) 28 ․ 트럼프 2기 행정부는 우리나라를 포함한 영국과 호주, 인도, 일본 등 5개 국을 최우선 협상국으로 선정, ‘원칙적 합의’와 ‘구체화 실무작업’의 2단계로 무역 협상을 진행 중임 ․ 이 가운데 일본의 경우, 주일미군주둔비와 환율 등이 비관세장벽과 함께 관세협상의 주요 의제가 되고 있어, 우리나라 입장에서는 美日 협상 과정 에서 對美 협상전략의 단서를 얻을 수 있을 것임 - (수출 전략의 재검토) 트럼프 2기 행정부는 무차별적 관세 부과, 우회 수출 제약 등 국내 기업이 지금까지 구축해 온 공급망으로부터의 이익이 훼손될 가능성도 큰 만큼 공급망 재편에서부터 수출 기지 선정에 이르기까지 전반 적인 수출 전략의 재검토도 필요함 ․ 수출 품목 및 지역의 다변화, 현지화 등을 통해 특정 공급망 또는 수출 기 지에 대한 의존도를 낮추는 한편 불확실성이 높은 글로벌 교역 환경에 대 해서도 대응할 수 있는 여건을 확보해야 함 ․ 이는 국내를 통한 타국 기업의 우회수출, 국내 기업의 타국 이용 우회수출 등도 트럼프 2기 행정부의 규제 대상이므로 발 빠른 대응이 필요함 ․ 인도, 아세안 등 성장잠재력이 높은 시장 공략을 수출의 외연 확대, 점진 적인 對中 공급망 재편 등을 통해 중장기 수출 기반 안정화를 꾀해야 함 셋째, 정책 이니셔티브 발현을 통해 민간투자를 기반으로 한 고용 및 소득 확충 을 유도하는 한편, 이것이 소비 확대로 이어질 수 있는 경제 선순환 구조 를 확립해야 한다. - (민간투자 기반 고용 및 소득 확충) 기업친화적 투자 환경 조성, 외국인 직접 투자 유치 확대, 국내 건설시장의 조기 안정화 등을 통해 민간투자를 기반으 로 한 고용 및 소득 확충 노력이 필요함 ․ 대외적으로는 트럼프 2기 행정부 관세정책 등에 의한 해외투자 가속, 대내 적으로는 고금리 등 고비용 리스크와 내수 여건 악화 등으로 민간투자 부 진 현상이 장기화되고 있음 ․ 이의 극복을 위해서는 적극적인 기업 친화적 투자 환경 조성 노력 등 국 내 투자 유인을 증대시키는 것이 긴요함 2025년 한국 경제 전망(수정) 29 ․ 구체적으로는 기업 관련 규제 완화 노력 지속, 금융·세제상 지원 강화, 노사 관계 안정, 기업인의 사기 진작 정책 등 다각적인 투자 활성화 정책 이 동반되어야 함 ․ 또한, 의료나 교육 등은 물론 수출입 규제 등 외국인투자 관련 인프라 전 반에 대한 개선, 유턴기업이나 유망 신기술 및 신산업에 관한 지원 강화 등의 노력이 필요함 - (건설시장 조기 정상화) 부동산 버블을 우려하지 않아도 될 정도 수준에서 국내 건설시장이 정상화될 수 있도록 유동성 공급 확대 및 합리적인 PF 시 장 관리, 실수요자에 대한 시장 접근성 강화 등의 시장 정책도 적극 추진되 어야 할 것임 넷째, 경기 침체기와 미래 불확실성 고조기에 가장 큰 타격을 받을 수 있는 취 약 계층에 대한 적절한 사회 안전망을 제공하여 사회 양극화가 고착화되 는 것을 막아야 한다. - (가계 특성별 사회 안전망 차별화) 저소득 고령 1인 가구 등 가계 특성별 사 회 안전망 차별화 등을 통해 복지 사각지대를 해소함과 동시에 복지재정의 효율성을 개선해야 함 ․ 현재 추진 중인 일자리나 금융 등의 부문에서의 사회 안전망의 경우에는 경기 회복세가 추세적으로 확인될 때까지 유지되는 것이 바람직함 - (업종별 영세 자영업자 지원 차별화) 영세 자영업자 비중이 높고 경기 침체 기 피해가 타 산업에 비해 상대적으로 큰 도소매, 음식숙박, 개인서비스 업 종의 경우, 업종별 규모별 피해 정도가 제각각인 만큼 차별적 지원 대책이 필요함 - (취약계층 대상 일자리 우선 제공) 청년층, 여성, 저소득층 등 고용 충격이 집중될 수 있는 계층에 대해서는 민간 일자리를 우선 지원할 수 있는 시스 템을 확충하고, 공공일자리도 관리·감독 강화를 통해 효율적이고 투명한 재 정 운영을 꾀해야 함 2025년 한국 경제 전망(수정) 30 다섯째, 사회통합을 기반으로 경제·사회의 역동성 복원 노력을 통해 중장기적 으로 한국 경제가 지속성장할 수 있는 기반을 확보해야 한다. - (정책 공감대 형성과 지지 확보) 정책 목표의 안정적인 달성을 위해서는 해 당 정책에 대한 국민적 공감대 형성과 지지가 전제되어야 하며 이를 바탕으 로 사회통합을 도모함으로써 성장 동력을 확보하는 것이 중요함 ․ 특히, 새로운 정책일 경우 그 취지를 충분히 설명하여 불필요한 오해나 확 대해석으로 경제심리가 위축되는 일이 없도록 노력해야 할 것임 - (일자리 창출과 소득 증대에 집중) 단기 경기침체 극복은 물론 우리 경제의 지속 가능 성장을 담보하기 위해서는 일자리 창출과 소득 증대를 통한 경제 선순환 고리 형성이 매우 중요함 - (혁신 기반 산업생태계 활성화와 자본시장의 산업 지원 기능 강화) 이를 위 해서는 혁신 기반의 산업생태계 활성화로 산업의 고부가가치화가 한 단계 더 발전하고, 임금 및 고용 안정성 등에서 상대적으로 더 좋은 일자리가 다수 창출되어야 함 주 원 경제연구실장 (2072-6235, juwon@hri.co.kr) 이부형 동향분석팀장(2072-6306, leebuh@hri.co.kr) 이택근 연구위원 (2072-6266, tklee@hri.co.kr) 신지영 연구위원 (2072-6240, jyshin@hri.co.kr) 노시연 연구위원 (2072-6248, syroh@hri.co.kr)"},
  {'url': 'https://www.kif.re.kr/kif4/publication/pub_detail?mid=21&nid=199&sid=199&vid=7328&cno=342644&pn=1',
   'title': '2025년 경제전망 - KIF - 한국금융연구원',
   'content': '금융브리프\n   경제전망\n   금융연구\n   한국경제의 분석\n   종간간행물\n\n### KIF 인기 연구자료\n\n   정기간행물 2025년 수정 경제전망\n   금융브리프 영국 국채시장 불안 사례의 배경과 시사점\n   KIF이슈리포트 주요국의 전자금융거래 규제 및 시사점 : 사업자 분류 및 관련 주요 개념을 중심으로\n\n### 경제전망\n\n특별호\n\n링크 복사 출력\n\n##### 2025년 경제전망\n\n국내 실물경제\n\nImage 1\n\n저자\nKIF\n\n페이지 수 _155_\n\n   바로보기\n   다운로드\n\n   요약\n   목차\n\nⅠ. 2025년 경제전망\n\n1. 경제성장\n\n▣ 우리 경제의 실질 GDP는 2024년 2.2%, 2025년 2.0% 성장할 전망\n\n▣ 민간소비 증가율은 2024년 1.3%, 2025년 2.0%를 기록할 전망\n\n▣ 건설투자 증가율은 2024년 △2.3%, 2025년 △2.7%를 기록할 전망\n\n▣ 설비투자 증가율은 2024년 1.1%에서 2025년 3.8%로 상승할 전망 [...] ▣ 2025년 총수출 및 총수입 증가율은 각각 2.3% 및 3.4%를 기록할 전망\n\n2. 고용\n\n▣ 고용률은 2024년 62.8%에서 2025년 62.9%로 상승할 전망\n\n3. 물가 및 시장금리 \n\n▣ 소비자물가 상승률은 2024년 2.4%, 2025년 2.0%를 기록할 전망\n\n▣ 국고채 3년물의 연평균 금리는 2024년 3.1%, 2025년 2.8%로 전망\n\n4. 국제수지 전망\n\n▣경상수지 흑자 규모는 2024년 793억 달러를 기록한 후, 2025년에도 680억 달러 수준의 흑자 기조가 이어질 전망\n\nⅡ. 종합평가 및 정책제언\n\n▣ 2025년 세계 경제의 불확실성이 확대될 전망\n\n▣ 2025년 우리 경제는 성장세가 약화하며 2.0% 성장할 전망\n\n▣최근의 상황을 고려할 때 통화정책과 금융정책의 조화로운 운용이 중요할 것으로 판단\n\n▣ 인플레이션이 점차 완화되는 반면 성장세가 약화되는 상황을 고려할 때 확장적 통화정책을 통한 내수 활성화 필요성이 증대 [...] 제 II 장 2025년 국ㆍ내외 경제여건\n\n1. 해외경제여건\n\n2. 국내경제여건\n\n3. 주요 고려사항\n\n제 III 장 2025년 경제전망\n\n1. 2025년 국내경제전망\n\n2. 종합평가 및 정책제언\n\n###### 관련자료\n\n   보고서\n   정기간행물\n\n   해외경제,국내 실물경제,계량분석/모형글로벌 VAR 모형을 활용한 대외충격 효과 분석 및 경제전망KIF연구보고서 김현태 2024-12   \n   국내 실물경제,고용/임금,계량분석/모형우리나라 이민정책의 현황, 평가분석 및 향후과제KIF Working Paper 강종구, 류상철, 안희욱, 이중식 2024-11   \n   국내 실물경제,통화/금리/물가이자 비용 상승의 소비 감소 효과에 대한 미시분석KIF연구보고서 김현열, 박춘성 2024-08',
   'score': 0.92442214,
   'raw_content': 'KIF - 한국금융연구원\n\n===============\n\n[한국금융연구원](https://www.kif.re.kr/kif4/)\n======================================\n\n검색\n\n검색창 닫기\n\n전체메뉴 열기/닫기\n\n[KIF](https://www.kif.re.kr/kif4/)\n\n*   보고서\n    *   [연구보고서](https://www.kif.re.kr/kif4/publication/pub_list?mid=10)\n    *   [영상보고서](https://www.kif.re.kr/kif4/publication/pub_list?mid=11)\n    *   [위탁용역보고서](https://www.kif.re.kr/kif4/publication/pub_list?mid=15)\n    *   [현안이슈](https://www.kif.re.kr/kif4/publication/pub_list?mid=12)\n    *   [국내외 연구자료](https://www.kif.re.kr/kif4/publication/pub_list?mid=13)\n\n*   정기간행물\n    *   [금융브리프](https://www.kif.re.kr/kif4/publication/pub_list?mid=20)\n    *   [경제전망](https://www.kif.re.kr/kif4/publication/pub_list?mid=21)\n    *   [금융연구](https://www.kif.re.kr/kif4/publication/pub_list?mid=22)\n    *   [한국경제의 분석](https://www.kif.re.kr/kif4/publication/pub_list?mid=23)\n\n*   세미나\n    *   [국내세미나](https://www.kif.re.kr/kif4/publication/seminar_list?mid=30)\n    *   [국제세미나](https://www.kif.re.kr/kif4/publication/seminar_list?mid=31)\n    *   [전망세미나](https://www.kif.re.kr/kif4/publication/seminar_list?mid=32)\n    *   [원내세미나](https://www.kif.re.kr/kif4/publication/seminar_list?mid=33)\n    *   [행사안내](https://www.kif.re.kr/kif4/info/info_list?mid=34)\n\n*   이메일서비스\n    *   [KIF 연구동향](https://www.kif.re.kr/kif4/email/email_list?mid=40)\n    *   [최신 해외연구동향](https://www.kif.re.kr/kif4/email/email_list?mid=41)\n    *   [최신 국내연구동향](https://www.kif.re.kr/kif4/email/email_list?mid=42)\n    *   [최신 금융정보](https://www.kif.re.kr/kif4/email/email_list?mid=43)\n    *   [최신 해외언론동향](https://www.kif.re.kr/kif4/email/email_list?mid=44)\n    *   [신청](https://www.kif.re.kr/kif4/email/subscribe?mid=45)\n\n*   알림마당\n    *   [공지사항](https://www.kif.re.kr/kif4/info/info_list?mid=50)\n    *   [카드뉴스](https://www.kif.re.kr/kif4/info/info_list?mid=57)\n    *   [연구원 보도자료](https://www.kif.re.kr/kif4/info/info_list?mid=51)\n    *   [주요기관 보도자료](https://www.kif.re.kr/kif4/info/info_list?mid=52)\n    *   [연구원 대외기고](https://www.kif.re.kr/kif4/info/info_list?mid=53)\n    *   [ADB 기고문](https://development.asia/expert/korea-institute-finance-kif)\n    *   [주요기관 행사 및 연수](https://www.kif.re.kr/kif4/info/info_list?mid=55)\n    *   [간행물 안내](https://www.kif.re.kr/kif4/info/pub_info?mid=56)\n\n*   연구원 안내\n    *   [원장인사말](https://www.kif.re.kr/kif4/about/intro?mid=60)\n    *   [연구원소개](https://www.kif.re.kr/kif4/about/about?mid=61)\n    *   [연구원홍보](https://www.kif.re.kr/kif4/about/promo?mid=64)\n    *   [연구원조직](https://www.kif.re.kr/kif4/about/organ?mid=62)\n    *   [찾아오시는 길](https://www.kif.re.kr/kif4/about/location?mid=63)\n\n*   ENG\n\n[30주년 기념 웹사이트](https://www.kif.re.kr/30th "30주년기념")\n\n[연구진](https://www.kif.re.kr/kif4/about/organ?mid=62&mode=R "연구진")\n\n**연구별 주제**KIF 주제에 맞는 연구자료를 탐색하세요 거시경제 금융시장 금융정책/제도 금융산업 금융회사 경영/전략\n\n*   홈\n*   [정기간행물](https://www.kif.re.kr/kif4/publication/pub_list?mid=20)\n*   경제전망 모바일 메뉴 열림\n    *   [금융브리프](https://www.kif.re.kr/kif4/publication/pub_list?mid=20)\n    *   [경제전망](https://www.kif.re.kr/kif4/publication/pub_list?mid=21)\n    *   [금융연구](https://www.kif.re.kr/kif4/publication/pub_list?mid=22)\n    *   [한국경제의 분석](https://www.kif.re.kr/kif4/publication/pub_list?mid=23)\n    *   [종간간행물](https://www.kif.re.kr/kif4/publication/pub_list?mid=24)\n\n공유 열기/닫기\n*   youtube\n*   instagram\n*   kakao\n*   링크 복사\n\n정기간행물\n-----\n\n*   [금융브리프](https://www.kif.re.kr/kif4/publication/pub_list?mid=20)\n*   [경제전망](https://www.kif.re.kr/kif4/publication/pub_list?mid=21)\n*   [금융연구](https://www.kif.re.kr/kif4/publication/pub_list?mid=22)\n*   [한국경제의 분석](https://www.kif.re.kr/kif4/publication/pub_list?mid=23)\n*   [종간간행물](https://www.kif.re.kr/kif4/publication/pub_list?mid=24)\n\n### KIF 인기 연구자료\n\n*   [정기간행물 2025년 수정 경제전망](https://www.kif.re.kr/kif4/publication/pub_detail?mid=21&nid=60&sid=60&vid=7465&cno=349465)\n*   [금융브리프 영국 국채시장 불안 사례의 배경과 시사점](https://www.kif.re.kr/kif4/publication/pub_detail?mid=20&nid=75&sid=58&vid=7464&cno=349440)\n*   [KIF이슈리포트 주요국의 전자금융거래 규제 및 시사점 : 사업자 분류 및 관련 주요 개념을 중심으로](https://www.kif.re.kr/kif4/publication/pub_detail?mid=10&nid=1013&sid=1013&vid=7423&cno=347613)\n\n### 경제전망\n\n특별호\n\n링크 복사 출력\n\n##### 2025년 경제전망\n\n국내 실물경제\n\n![Image 1](https://www.kif.re.kr/kif4/inc/images/common/no_img.svg)\n\n저자\nKIF\n\n페이지 수 _155_\n\n*   바로보기\n*   다운로드\n\n*   요약\n*   목차\n\nⅠ. 2025년 경제전망\n\n1. 경제성장\n\n▣ 우리 경제의 실질 GDP는 2024년 2.2%, 2025년 2.0% 성장할 전망\n\n▣ 민간소비 증가율은 2024년 1.3%, 2025년 2.0%를 기록할 전망\n\n▣ 건설투자 증가율은 2024년 △2.3%, 2025년 △2.7%를 기록할 전망\n\n▣ 설비투자 증가율은 2024년 1.1%에서 2025년 3.8%로 상승할 전망\n\n▣ 2025년 총수출 및 총수입 증가율은 각각 2.3% 및 3.4%를 기록할 전망\n\n2. 고용\n\n▣ 고용률은 2024년 62.8%에서 2025년 62.9%로 상승할 전망\n\n3. 물가 및 시장금리 \n\n▣ 소비자물가 상승률은 2024년 2.4%, 2025년 2.0%를 기록할 전망\n\n▣ 국고채 3년물의 연평균 금리는 2024년 3.1%, 2025년 2.8%로 전망\n\n4. 국제수지 전망\n\n▣경상수지 흑자 규모는 2024년 793억 달러를 기록한 후, 2025년에도 680억 달러 수준의 흑자 기조가 이어질 전망\n\nⅡ. 종합평가 및 정책제언\n\n▣ 2025년 세계 경제의 불확실성이 확대될 전망\n\n▣ 2025년 우리 경제는 성장세가 약화하며 2.0% 성장할 전망\n\n▣최근의 상황을 고려할 때 통화정책과 금융정책의 조화로운 운용이 중요할 것으로 판단\n\n▣ 인플레이션이 점차 완화되는 반면 성장세가 약화되는 상황을 고려할 때 확장적 통화정책을 통한 내수 활성화 필요성이 증대\n\n▣ 반면, 금리 인하에 따르는 부채 증가 및 주택시장 과열 등 금융 불균형 위험과 대외 불확실성 확대에 따른 외환시장 부담 등은 기준금리 인하의 제약 요인으로 작용\n\n▣ 이러한 상황을 종합적으로 고려할 때, 통화정책은 대외여건을 보아가며 성장과 물가 등 실물경제를 중심으로 유연하게 운용하되, 그 과정에서 발생할 수 있는 가계부채 증가 등의 금융 불균형 문제는 금융정책으로 대응하는 정책조합을 고려할 필요 \n\n▣ 재정정책은 건전 재정기조를 훼손하지 않는 범위에서 취약계층 지원, 성장동력 강화를 위한 구조조정정책 등 필수적인 부분에 대한 정책을 확대할 필요 \n\n▣ 중장기적 관점에서 우리 경제가 자체적인 구조적 문제뿐만 아니라다양한 공급 측면의 불확실성에 노출되어 있음을 고려하여 생산성 향상을 위한 다양한 정책조합을 발굴할 필요\n\n제 I 장 최근 경제동향\n\n1. 해외경제 동향\n\n2. 국내경제 동향\n\n3. 금융시장 동향\n\n4. 국제수지 및 원/달러 환율 동향\n\n제 II 장 2025년 국ㆍ내외 경제여건\n\n1. 해외경제여건\n\n2. 국내경제여건\n\n3. 주요 고려사항\n\n제 III 장 2025년 경제전망\n\n1. 2025년 국내경제전망\n\n2. 종합평가 및 정책제언\n\n###### 관련자료\n\n*   보고서\n*   정기간행물\n\n*   해외경제,국내 실물경제,계량분석/모형[글로벌 VAR 모형을 활용한 대외충격 효과 분석 및 경제전망](https://www.kif.re.kr/kif4/publication/pub_detail?mid=10&nid=867&sid=867&vid=7343&cno=343400)KIF연구보고서 김현태 2024-12   \n*   국내 실물경제,고용/임금,계량분석/모형[우리나라 이민정책의 현황, 평가분석 및 향후과제](https://www.kif.re.kr/kif4/publication/pub_detail?mid=15&nid=846&sid=846&vid=7322&cno=342259)KIF Working Paper 강종구, 류상철, 안희욱, 이중식 2024-11   \n*   국내 실물경제,통화/금리/물가[이자 비용 상승의 소비 감소 효과에 대한 미시분석](https://www.kif.re.kr/kif4/publication/pub_detail?mid=10&nid=867&sid=867&vid=7253&cno=337928)KIF연구보고서 김현열, 박춘성 2024-08   \n\n*   국내 실물경제,통화/금리/물가,통화정책,재정정책[2025년 수정경제전망과 정책적 시사점](https://www.kif.re.kr/kif4/publication/pub_detail?mid=20&nid=189&sid=188&vid=7450&cno=348980)금융브리프 김현태 2025-05-24   \n*   국내 실물경제,통화/금리/물가[2025년 수정 경제전망](https://www.kif.re.kr/kif4/publication/pub_detail?mid=21&nid=199&sid=199&vid=7465&cno=349465)경제전망시리즈 KIF 2025-05   \n*   국내 실물경제,부동산금융,금융현안 및 정책[지방 미분양 주택 문제와 거시건전성 감독 차원의 금융정책 대응](https://www.kif.re.kr/kif4/publication/pub_detail?mid=20&nid=190&sid=188&vid=7421&cno=347495)금융브리프 신용상 2025-04-12   \n\n이전\n\n**한국금융연구원 \n\n공식 웹사이트입니다**Korea Institute of Finance\n\n04538 서울특별시 중구 명동 11길 19 \n\n은행회관 5~8F 02.3705.6300[webmaster@kif.re.kr](mailto:webmaster@kif.re.kr)Chrome/Edge에 최적화 되어 있습니다\n\n[이용약관](https://www.kif.re.kr/kif4/service/terms?mid=70&mode=0)|[개인정보보호정책](https://www.kif.re.kr/kif4/service/terms?mid=71&mode=1)\n\n*   You tube\n*   instagram\n*   kakao\n\n© 1991-2025 Korea Institute of Finance. \n\nAll Rights Reserved.\n\n*   글꼴 크기 변경 창 열기**글꼴 크기**\n    *   글꼴 크게 변경\n    *   글꼴 작게 변경\n    *   새로고침\n\n*   이메일**이메일서비스**\n*   위로 가기\n'},
  {'url': 'https://www.kif.re.kr/kif4/publication/pub_detail?mid=21&nid=199&sid=199&vid=7465&cno=349465&pn=1',
   'title': '2025년 수정 경제전망 - KIF - 한국금융연구원',
   'content': '금융브리프\n   경제전망\n   금융연구\n   한국경제의 분석\n   종간간행물\n\n### KIF 인기 연구자료\n\n   KIF이슈리포트 주요국의 전자금융거래 규제 및 시사점 : 사업자 분류 및 관련 주요 개념을 중심으로\n   금융브리프 영국 국채시장 불안 사례의 배경과 시사점\n   KIF이슈리포트 그린핀테크(Green FinTech) 국내외 사례와 정책적 시사점\n\n### 경제전망\n\n특별호\n\n링크 복사 출력\n\n##### 2025년 수정 경제전망\n\n국내 실물경제, 통화/금리/물가\n\nImage 1\n\n저자\nKIF\n\n페이지 수 _160_\n\n   바로보기\n   다운로드\n\n   요약\n   목차\n\nⅠ. 2025년 경제전망\n\n1. 경제성장\n\n▣ 2025년 우리 경제의 실질 국내총생산(GDP)은 0.8% 성장할 것으로 전망\n\n ∙대내외 불확실성 확대로 민간소비 회복이 둔화되고 누적된 수주 부진의 영향으로 건설투자가 크게 부진한 가운데 미국 관세 인상 여파로 수출도 위축되면서 성장이 둔화될 전망 [...] ▣ 2025년 고용률은 62.7%를 기록할 전망\n\n ∙고용률은 기업 경영 여건의 악화 및 내수 부진의 지속에도 불구하고 60세 이상 고령층의 견조한 노동시장 진입으로 전년도 수준을 유지할 전망\n\n ∙실업률은 전년대비 소폭 상승한 2.9%를 기록할 것으로 예상\n\n ∙취업자 수는 약 8만명 증가하여 전년대비 증가세가 둔화될 전망\n\n3. 물가 및 시장금리 \n\n▣ 소비자물가상승률은 상반기 2.0%, 하반기 1.9%로 연간으로는 2.0%를 기록할 전망\n\n ∙내수 부진 지속, 수출 감소 등으로 경제성장률이 크게 낮아지는 가운데 글로벌 경기침체 우려에 따른 유가 등 원자재가격 하락으로 물가는 하향 안정세를 유지할 것으로 전망\n\n ∙지정학적 위험 및 관세 협상 관련 불확실성 확대, 연준 금리인하 지연 등으로 인한 원/달러 환율 상승 가능성은 물가에 상방 압력으로 작용할 것으로 예상\n\n▣ 국고채 3년물의 연평균 금리는 2.3%로 전년 대비 상당폭 하락할 전망 [...] 제 II 장 2025년 국·내외 경제여건 \n\n1. 해외경제여건 \n\n2. 국내경제여건 \n\n3. 주요 고려사항 \n\n제 III 장 2025년 경제전망 \n\n1. 2025년 국내경제전망 \n\n2. 종합평가 및 정책제언\n\n###### 관련자료\n\n   보고서\n   정기간행물\n\n   통화/금리/물가우리나라의 소비행태 변화와 인플레이션KIF연구보고서 장민 2024-12   \n   해외경제,국내 실물경제,계량분석/모형글로벌 VAR 모형을 활용한 대외충격 효과 분석 및 경제전망KIF연구보고서 김현태 2024-12   \n   국내 실물경제,고용/임금,계량분석/모형우리나라 이민정책의 현황, 평가분석 및 향후과제KIF Working Paper 강종구, 류상철, 안희욱, 이중식 2024-11',
   'score': 0.9224337,
   'raw_content': 'KIF - 한국금융연구원\n\n===============\n\n[한국금융연구원](https://www.kif.re.kr/kif4/)\n======================================\n\n검색\n\n검색창 닫기\n\n전체메뉴 열기/닫기\n\n[KIF](https://www.kif.re.kr/kif4/)\n\n*   보고서\n    *   [연구보고서](https://www.kif.re.kr/kif4/publication/pub_list?mid=10)\n    *   [영상보고서](https://www.kif.re.kr/kif4/publication/pub_list?mid=11)\n    *   [위탁용역보고서](https://www.kif.re.kr/kif4/publication/pub_list?mid=15)\n    *   [현안이슈](https://www.kif.re.kr/kif4/publication/pub_list?mid=12)\n    *   [국내외 연구자료](https://www.kif.re.kr/kif4/publication/pub_list?mid=13)\n\n*   정기간행물\n    *   [금융브리프](https://www.kif.re.kr/kif4/publication/pub_list?mid=20)\n    *   [경제전망](https://www.kif.re.kr/kif4/publication/pub_list?mid=21)\n    *   [금융연구](https://www.kif.re.kr/kif4/publication/pub_list?mid=22)\n    *   [한국경제의 분석](https://www.kif.re.kr/kif4/publication/pub_list?mid=23)\n\n*   세미나\n    *   [국내세미나](https://www.kif.re.kr/kif4/publication/seminar_list?mid=30)\n    *   [국제세미나](https://www.kif.re.kr/kif4/publication/seminar_list?mid=31)\n    *   [전망세미나](https://www.kif.re.kr/kif4/publication/seminar_list?mid=32)\n    *   [원내세미나](https://www.kif.re.kr/kif4/publication/seminar_list?mid=33)\n    *   [행사안내](https://www.kif.re.kr/kif4/info/info_list?mid=34)\n\n*   이메일서비스\n    *   [KIF 연구동향](https://www.kif.re.kr/kif4/email/email_list?mid=40)\n    *   [최신 해외연구동향](https://www.kif.re.kr/kif4/email/email_list?mid=41)\n    *   [최신 국내연구동향](https://www.kif.re.kr/kif4/email/email_list?mid=42)\n    *   [최신 금융정보](https://www.kif.re.kr/kif4/email/email_list?mid=43)\n    *   [최신 해외언론동향](https://www.kif.re.kr/kif4/email/email_list?mid=44)\n    *   [신청](https://www.kif.re.kr/kif4/email/subscribe?mid=45)\n\n*   알림마당\n    *   [공지사항](https://www.kif.re.kr/kif4/info/info_list?mid=50)\n    *   [카드뉴스](https://www.kif.re.kr/kif4/info/info_list?mid=57)\n    *   [연구원 보도자료](https://www.kif.re.kr/kif4/info/info_list?mid=51)\n    *   [주요기관 보도자료](https://www.kif.re.kr/kif4/info/info_list?mid=52)\n    *   [연구원 대외기고](https://www.kif.re.kr/kif4/info/info_list?mid=53)\n    *   [ADB 기고문](https://development.asia/expert/korea-institute-finance-kif)\n    *   [주요기관 행사 및 연수](https://www.kif.re.kr/kif4/info/info_list?mid=55)\n    *   [간행물 안내](https://www.kif.re.kr/kif4/info/pub_info?mid=56)\n\n*   연구원 안내\n    *   [원장인사말](https://www.kif.re.kr/kif4/about/intro?mid=60)\n    *   [연구원소개](https://www.kif.re.kr/kif4/about/about?mid=61)\n    *   [연구원홍보](https://www.kif.re.kr/kif4/about/promo?mid=64)\n    *   [연구원조직](https://www.kif.re.kr/kif4/about/organ?mid=62)\n    *   [찾아오시는 길](https://www.kif.re.kr/kif4/about/location?mid=63)\n\n*   ENG\n\n[30주년 기념 웹사이트](https://www.kif.re.kr/30th "30주년기념")\n\n[연구진](https://www.kif.re.kr/kif4/about/organ?mid=62&mode=R "연구진")\n\n**연구별 주제**KIF 주제에 맞는 연구자료를 탐색하세요 거시경제 금융시장 금융정책/제도 금융산업 금융회사 경영/전략\n\n*   홈\n*   [정기간행물](https://www.kif.re.kr/kif4/publication/pub_list?mid=20)\n*   경제전망 모바일 메뉴 열림\n    *   [금융브리프](https://www.kif.re.kr/kif4/publication/pub_list?mid=20)\n    *   [경제전망](https://www.kif.re.kr/kif4/publication/pub_list?mid=21)\n    *   [금융연구](https://www.kif.re.kr/kif4/publication/pub_list?mid=22)\n    *   [한국경제의 분석](https://www.kif.re.kr/kif4/publication/pub_list?mid=23)\n    *   [종간간행물](https://www.kif.re.kr/kif4/publication/pub_list?mid=24)\n\n공유 열기/닫기\n*   youtube\n*   instagram\n*   kakao\n*   링크 복사\n\n정기간행물\n-----\n\n*   [금융브리프](https://www.kif.re.kr/kif4/publication/pub_list?mid=20)\n*   [경제전망](https://www.kif.re.kr/kif4/publication/pub_list?mid=21)\n*   [금융연구](https://www.kif.re.kr/kif4/publication/pub_list?mid=22)\n*   [한국경제의 분석](https://www.kif.re.kr/kif4/publication/pub_list?mid=23)\n*   [종간간행물](https://www.kif.re.kr/kif4/publication/pub_list?mid=24)\n\n### KIF 인기 연구자료\n\n*   [KIF이슈리포트 주요국의 전자금융거래 규제 및 시사점 : 사업자 분류 및 관련 주요 개념을 중심으로](https://www.kif.re.kr/kif4/publication/pub_detail?mid=10&nid=1013&sid=1013&vid=7423&cno=347613)\n*   [금융브리프 영국 국채시장 불안 사례의 배경과 시사점](https://www.kif.re.kr/kif4/publication/pub_detail?mid=20&nid=75&sid=58&vid=7464&cno=349440)\n*   [KIF이슈리포트 그린핀테크(Green FinTech) 국내외 사례와 정책적 시사점](https://www.kif.re.kr/kif4/publication/pub_detail?mid=10&nid=1013&sid=1013&vid=7428&cno=347920)\n\n### 경제전망\n\n특별호\n\n링크 복사 출력\n\n##### 2025년 수정 경제전망\n\n국내 실물경제, 통화/금리/물가\n\n![Image 1](https://www.kif.re.kr/kif4/inc/images/common/no_img.svg)\n\n저자\nKIF\n\n페이지 수 _160_\n\n*   바로보기\n*   다운로드\n\n*   요약\n*   목차\n\nⅠ. 2025년 경제전망\n\n1. 경제성장\n\n▣ 2025년 우리 경제의 실질 국내총생산(GDP)은 0.8% 성장할 것으로 전망\n\n ∙대내외 불확실성 확대로 민간소비 회복이 둔화되고 누적된 수주 부진의 영향으로 건설투자가 크게 부진한 가운데 미국 관세 인상 여파로 수출도 위축되면서 성장이 둔화될 전망\n\n▣ 민간소비 증가율은 0.9%를 기록할 전망\n\n ∙1/4분기 중 민간소비는 전기대비 0.1% 감소, 전년동기대비 0.5% 증가에 그쳐 부진이 심화\n\n ∙대내외적 불확실성의 해소가 지연됨으로 인해 소비심리는 장기간 위축될 전망\n\n ∙기업 경영 여건의 악화와 함께 고용시장이 둔화되는 등, 가계의 소득 여건 또한 연중 악화될 것으로 예상\n\n▣ 건설투자 증가율은 △5.7%를 기록할 전망\n\n ∙건설투자는 2022~2023년 수주 부진의 영향이 2025년까지 영향을 미치면서 △5.7%로 부진이 심화될 것으로 예상\n\n ∙2024년 2분기 이후 금리 인하 및 공사비 인상률 둔화 등으로 건설 수주가 완만한 회복세를 보여왔으나 그 수준은 여전히 낮은 상황\n\n ∙또한, 인허가 및 착공 물량이 여전히 감소세를 보이고 있는 점과 미분양 적체 등은 향후 건설투자 회복 속도를 제약하는 요인\n\n▣ 설비투자 증가율은 0.3%를 기록할 전망\n\n ∙상반기 예정된 설비투자는 일부 진행될 것으로 보이나, 관세 정책의 영향이 커지는 연말로 갈수록 설비투자 증가율 둔화폭이 커질 것으로 예상\n\n ∙다만, 관세 정책이 현재 예고된 수준보다 낮아질 가능성, 올해 상당수 항공기 도입이 예정되었던 점 등은 설비투자 증가율 하락을 제한하는 요인임.\n\n▣ 총수출 및 총수입 모두 0.3% 수준의 낮은 증가율을 기록할 전망\n\n ∙총수출은 미국의 관세 부과 및 경제 불확실성 고조에 따른 전 세계적 수요 위축으로 인해 증가율이 저조한 수준에 머물 전망\n\n* WTO는 2025년 전 세계 상품교역 성장률을 △0.2%로 전망하였는데, 이는 작년 10월에 발표된 전망치 2.9% 대비 3.1%p만큼 하향 조정된 수치에 해당\n\n ∙총수입은 글로벌 교역 위축이 중간재 및 자본재 수입에 대한 제약 요인으로 작용하는 가운데 소비심리 위축에 따라 내구성 소비재 수입도 부진한 모습을 나타내면서 낮은 증가율을 기록할 전망\n\n2. 고용\n\n▣ 2025년 고용률은 62.7%를 기록할 전망\n\n ∙고용률은 기업 경영 여건의 악화 및 내수 부진의 지속에도 불구하고 60세 이상 고령층의 견조한 노동시장 진입으로 전년도 수준을 유지할 전망\n\n ∙실업률은 전년대비 소폭 상승한 2.9%를 기록할 것으로 예상\n\n ∙취업자 수는 약 8만명 증가하여 전년대비 증가세가 둔화될 전망\n\n3. 물가 및 시장금리 \n\n▣ 소비자물가상승률은 상반기 2.0%, 하반기 1.9%로 연간으로는 2.0%를 기록할 전망\n\n ∙내수 부진 지속, 수출 감소 등으로 경제성장률이 크게 낮아지는 가운데 글로벌 경기침체 우려에 따른 유가 등 원자재가격 하락으로 물가는 하향 안정세를 유지할 것으로 전망\n\n ∙지정학적 위험 및 관세 협상 관련 불확실성 확대, 연준 금리인하 지연 등으로 인한 원/달러 환율 상승 가능성은 물가에 상방 압력으로 작용할 것으로 예상\n\n▣ 국고채 3년물의 연평균 금리는 2.3%로 전년 대비 상당폭 하락할 전망\n\n ∙작년말 이후 대내외 불확실성 확대로 경기 하방 리스크가 커지면서 기준금리에 대한 시장의 기대가 하향 조정되었고, 올해 상반기 중 시장금리도 지속적인 하락세 시현 \n\n ∙다만, 이미 국고채 3년물과 기준금리 간 역전폭이 큰 상황으로 이는 기준금리 인하 가능성이 상당 부분 선반영되어 있음을 시사\n\n ∙전년대비 증가 예정인 국고채 발행량과 추경 가능성, WGBI 편입 지연 등 수급 이슈 또한 금리 하락세를 일정 부분 제한할 것으로 예상\n\n4. 국제수지 전망\n\n▣ 경상수지는 880억 달러 흑자를 기록할 전망\n\n ∙전 세계 원유수요 둔화로 국제유가가 급락하면서 수출입물가도 큰 폭으로 하락함에 따라 수출입 모두 금액 기준으로 감소할 전망\n\n ∙2024년에 높은 수준을 기록했던 수출금액의 기저효과가 통관수출 감소율을 확대시키는 요인으로 작용하는 한편, 국제유가에 대한 탄력성 차이는 수입물가 및 수입금액이 수출 대비 상대적으로 더 큰 폭의 감소율을 기록하는 배경으로 작용\n\n ∙서비스 부문에서는 운송·관광 부문의 지급과 수입이 모두 동반부진을 경험하면서 서비스수지가 기존과 유사한 수준의 적자를 지속할 전망\n\nⅡ. 종합평가 및 정책제언\n\n▣ 2025년 세계 경제는 통상 마찰 격화와 정책 불확실성 확대로 성장과 교역이 둔화될 전망\n\n ∙IMF는 세계 경제성장률 전망치를 2025년 2.8%, 2026년 3.0%로 올해 1월 전망 대비 각각 0.5%p, 0.3%p 하향 조정\n\n ∙4.2일 발표된 미국의 보편관세 및 상호관세는 글로벌 금융시장에 충격을 주고 무역 관련 불확실성을 전례 없는 수준으로 높여 실물경기에 압박을 가하고 있으며, 상호관세 유예 발표 이후에도 이어지는 국가별 협상 관련한 불확실성이 지속\n\n* 미국 소비자 심리지표가 최근 급격히 둔화된 가운데 관세 회피를 위한 선제적 구매 효과가 사라진 이후의 소비·투자 둔화 위험이 확대\n\n ∙미국 정책 결정 과정의 즉흥성과 비일관성도 기업 투자와 민간 소비를 위축시키는 불확실성 요인으로 작용\n\n ∙관세로 인한 수입 물가 인상 압력이 현실화 할 경우 연준의 기준금리 인하 또한 지연될 가능성\n\n ∙이에 따라 IMF는 2025년 미국 경제성장률 전망을 1.8%로 1월 전망에 비해 0.9%p 하향 조정하였으며 상호관세의 주요 타겟이 된 중국의 성장률도 4.0%로 0.6%p 하향 조정\n\n* 세계 GDP의 43.4%를 차지(2024년 기준)하는 미ᐧ중 무역 갈등이 장기화 조짐을 보임에 따라 글로벌 경기둔화 위험이 현실화\n\n ∙중장기 성장률 전망 또한 약 3.2%로 과거 장기평균(2000-2019년, 3.7%) 대비 낮을 것으로 전망되어 구조적인 성장둔화 우려가 확대\n\n▣ 2025년 우리 경제는 민간소비, 건설투자를 중심으로 내수 부진이 지속되는 가운데 통상환경 악화로 순수출도 위축되면서 성장세가 당초 예상보다 크게 둔화될 전망\n\n ∙2024년 2분기 이후 GDP는 4분기 연속 전기비 0.1% 이하로 사실상 정체\n\n ∙건설투자는 누적된 수주 부진의 영향이 본격화하고 지방 부동산 시장 침체가 지속되면서 2024년 2분기 이후 4분기 연속 전기비 마이너스 성장을 기록\n\n* 건설투자를 제외한 2024년 및 2025년 1분기 성장률(전년동기비)은 각각 2.8%, 1.5%\n\n ∙당초 금리 인하 및 물가 안정으로 개선이 예상되었던 민간 소비는 대외불확실성 확대로 인한 경기둔화 우려 등에 따라 회복 속도가 둔화될 전망이며, 설비투자도 글로벌 경기 둔화로 성장세가 예상보다 낮아질 것으로 판단\n\n ∙수출은 미국 관세 인상과 수출시장 다변화를 위한 중국의 저가 공세 심화 등으로 증가세가 위축될 것으로 전망\n\n▣ 내수 부진과 수출 둔화가 맞물리며 성장세가 크게 약화된 최근 상황을 고려할 때, 보다 적극적인 경기 대응을 위한 방안을 강구하는 한편 중장기적 경제구조 개선을 위한 노력을 병행할 필요\n\n▣ 통화정책은 인플레이션 안정세와 경기 하방 압력 확대를 감안하여 보다 완화적으로 운용하고, 기준금리 조정 이외에 금융기관에 대한 신용공급 확대 등 대안을 모색\n\n ∙유가 안정세와 국내 수요 부진 심화로 추가적인 기준금리 인하 필요성이 높아진 상황이며, 내외금리차 역전 폭, 환율 변동성 등으로 기준금리 인하 폭이 제한되는 경우 경제지표와 연동한 포워드 가이던스 활용 등을 검토\n\n ∙경기 하강 지속 시 한은의 금융중개지원대출 등 금융기관에 직접 자금을 투입할 수 있는 방안을 모색함으로써 중소 수출기업 등에 대한 자금지원을 확대\n\n▣ 금융정책은 대외여건 변화와 금융시장 변동성 확대에 선제적으로 대응하는 한편 금리 인하 등으로 확대된 신용이 다시 부동산으로 쏠리지 않도록 경계하는 등 금융시장 안정 및 건전성 관리에 유의\n\n ∙미·중 무역갈등 격화와 글로벌 경기 둔화 우려 등으로 인한 급격한 자본유출 위험에 대비하여 금융시장 모니터링을 강화하고 비상대응체계를 유지\n\n ∙상환가능한 범위 내의 대출이라는 대원칙 하에 총부채원리금상환비율(DSR) 규제를 근간으로 한 가계부채 관리 기조를 일관되게 유지\n\n ∙다만, 경기 둔화로 기업 및 소상공인에 대한 신용 공급이 위축되지 않도록 관리\n\n▣ 재정정책은 중장기적 차원의 재정건전성 유지라는 현실적 제약을 감안하되 급격한 경기 둔화 시에는 보다 적극적이고 효율적으로 운용할 필요\n\n ∙경기 하방 압력 확대 시 신속하게 추가적인 추경예산 편성 및 집행을 고려하고, 경기 위축 시 피해가 예상되는 소상공인 및 저소득층 등 취약계층에 대한 선별적 지원을 통해 소비 위축을 최소화\n\n ∙관세 인상으로 피해가 예상되는 수출기업 및 산업에 대해 무역금융, 긴급유동성 지원 및 고용유지보조금 공급을 확대\n\n ∙이와 함께 미래 성장동력 확충을 위한 인프라 투자를 확대\n\n* 전기차 보급, 데이터센터, AI 모형 훈련 및 운용 등으로 크게 증가할 것으로 예상되는 전력수요에 대비하여 선제적 전력 인프라 투자를 실시\n\n** 국ᐧ공립 어린이집 및 초등학교 방과후 돌봄 확대, 유아 원격의료 및 상담 시스템 구축 등 육아 인프라 확대를 통해 저출산 심화에 대응\n\n ∙핵심 수출산업 및 전략 육성 산업의 경쟁력 제고를 위해 연구개발 및 설비투자에 대한 지원을 확대\n\n▣ 또한 보다 중장기적 관점에서 우리 경제의 체질을 강화하고 잠재성장률을 제고하기 위한 구조개혁 노력을 지속\n\n ∙글로벌 기술패권 경쟁 격화에 대응한 기업 사업구조 개편과 혁신 촉진을 위해 규제 완화, 금융ᐧ세제 지원 및 산업 수요와 연계한 인재 양성 등을 종합적으로 추진\n\n ∙노동 공급 감소에 대응하여 고령층 노동력 활용 확대를 위한 제도 개편, 자동화 기술 보급, 출산 인센티브 확대 등을 포괄한 정책을 추진\n\n ∙세제개혁, 재정지출 구조조정 등 재정건전성 유지를 위한 중장기 전략을 마련\n\n제 I 장 최근 경제동향\n\n1. 해외경제 동향\n\n2. 국내경제 동향 \n\n3. 금융시장 동향 \n\n4. 국제수지 및 원/달러 환율 동향 \n\n제 II 장 2025년 국·내외 경제여건 \n\n1. 해외경제여건 \n\n2. 국내경제여건 \n\n3. 주요 고려사항 \n\n제 III 장 2025년 경제전망 \n\n1. 2025년 국내경제전망 \n\n2. 종합평가 및 정책제언\n\n###### 관련자료\n\n*   보고서\n*   정기간행물\n\n*   통화/금리/물가[우리나라의 소비행태 변화와 인플레이션](https://www.kif.re.kr/kif4/publication/pub_detail?mid=10&nid=867&sid=867&vid=7357&cno=344154)KIF연구보고서 장민 2024-12   \n*   해외경제,국내 실물경제,계량분석/모형[글로벌 VAR 모형을 활용한 대외충격 효과 분석 및 경제전망](https://www.kif.re.kr/kif4/publication/pub_detail?mid=10&nid=867&sid=867&vid=7343&cno=343400)KIF연구보고서 김현태 2024-12   \n*   국내 실물경제,고용/임금,계량분석/모형[우리나라 이민정책의 현황, 평가분석 및 향후과제](https://www.kif.re.kr/kif4/publication/pub_detail?mid=15&nid=846&sid=846&vid=7322&cno=342259)KIF Working Paper 강종구, 류상철, 안희욱, 이중식 2024-11   \n\n*   통화/금리/물가,국제수지/환율[최근 대외여건 변화가 소비자물가에 미치는 영향](https://www.kif.re.kr/kif4/publication/pub_detail?mid=20&nid=190&sid=188&vid=7464&cno=349442)금융브리프 장민 2025-06-07   \n*   통화/금리/물가,국제수지/환율,통상/공급망/지정학[미국의 2019년 환율조작국 지정 사례와 향후 한·미 통상 협의에 대한 시사점](https://www.kif.re.kr/kif4/publication/pub_detail?mid=20&nid=190&sid=188&vid=7450&cno=348991)금융브리프 송민기 2025-05-24   \n*   해외경제,통화/금리/물가,통상/공급망/지정학[미중 관세전쟁의 반사이익과 풍선효과](https://www.kif.re.kr/kif4/publication/pub_detail?mid=20&nid=190&sid=188&vid=7450&cno=348989)금융브리프 지만수 2025-05-24   \n\n이전\n\n**한국금융연구원 \n\n공식 웹사이트입니다**Korea Institute of Finance\n\n04538 서울특별시 중구 명동 11길 19 \n\n은행회관 5~8F 02.3705.6300[webmaster@kif.re.kr](mailto:webmaster@kif.re.kr)Chrome/Edge에 최적화 되어 있습니다\n\n[이용약관](https://www.kif.re.kr/kif4/service/terms?mid=70&mode=0)|[개인정보보호정책](https://www.kif.re.kr/kif4/service/terms?mid=71&mode=1)\n\n*   You tube\n*   instagram\n*   kakao\n\n© 1991-2025 Korea Institute of Finance. \n\nAll Rights Reserved.\n\n*   글꼴 크기 변경 창 열기**글꼴 크기**\n    *   글꼴 크게 변경\n    *   글꼴 작게 변경\n    *   새로고침\n\n*   이메일**이메일서비스**\n*   위로 가기\n'},
  {'url': 'https://www.youtube.com/watch?v=E7sPhLmT17g',
   'title': 'BOK경제전망보고서(Indigo Book)|2025년 5월| - YouTube',
   'content': '인트로 [음악] 안녕하십니까 바로 지난주 한국은행 2025년 5월 경제전망이 발표됐는데요 경제전망은 한국은행이 지금 경제를 어떻게 바라보고 있는지 알 수 있는 아주 중요한 보고서입니다 그래서 오늘은 그 내용을 살펴보는 시간을 준비했습니다 먼저 이번 경제 전망에서는 성장률 전망치를 1.5%에서 0.8%로 8%로 크게 낮추셨는데요 왜 이렇게 크게 하향 이번 경제전망에서 성장률 전망치를 하향 조정하셨는데, 그 배경이 무엇인가요? 조정하게 되셨을까요 어 경제전만은 여건 변화를 반영하여 조정하게 되는데요 아시겠지만 최근 안 좋은 일들이 많이 발생했기 때문에 어,이를 반영한 결과로 보시면 될 거 같고 크게 세 가지 요인으로 나누어서 말씀드릴 수 있겠습니다 먼저 경제 심리가 위축되고 회복이 지연되었던 부분입니다 저희가 지난 2월에 전망을 발표했을 때도 정치 불확실성이라든지 대내외 여권 악화로 경제 주체들의 심리가 위축된 점을 전망에 반영하였지만 그 이후로도 정치불확실성이 좀 더 이어지고 미 [...] # 🔭BOK경제전망보고서(Indigo Book)|2025년 5월|\n## 한국은행\n109000 subscribers\n92 likes\n\n### Description\n9360 views\nPosted: 5 Jun 2025\n올해 우리 경제 안팎의 불확실성 탓에 경제심리 회복이 예상보다 늦어졌고, \n미국의 관세 정책도 예상보다 강하게 나오면서 연초 1.5%로 봤던 성장률이 0.8%까지 낮아질 전망인데요.\n\n물가의 경우, 식품·서비스 가격이 오르긴 했지만 수요 둔화와 유가 하락 등의 영향이 맞물리면서 \n2월에 예상했던 1.9% 수준에서 유지될 것으로 보입니다.\n\n더 자세한 내용은 아래 링크된 경제전망보고서에서 확인해 보세요! 😉\n\n#한국은행 #경제성장률 #물가 #경제전망 #미국 #관세',
   'score': 0.8752871,
   'raw_content': '# 🔭BOK경제전망보고서(Indigo Book)|2025년 5월|\n## 한국은행\n109000 subscribers\n92 likes\n\n### Description\n9360 views\nPosted: 5 Jun 2025\n올해 우리 경제 안팎의 불확실성 탓에 경제심리 회복이 예상보다 늦어졌고, \n미국의 관세 정책도 예상보다 강하게 나오면서 연초 1.5%로 봤던 성장률이 0.8%까지 낮아질 전망인데요.\n\n물가의 경우, 식품·서비스 가격이 오르긴 했지만 수요 둔화와 유가 하락 등의 영향이 맞물리면서 \n2월에 예상했던 1.9% 수준에서 유지될 것으로 보입니다.\n\n더 자세한 내용은 아래 링크된 경제전망보고서에서 확인해 보세요! 😉\n\n#한국은행 #경제성장률 #물가 #경제전망 #미국 #관세\n\n\n00:00 인트로\n00:28 이번 경제전망에서 성장률 전망치를 하향 조정하셨는데, 그 배경이 무엇인가요?\n01:47 지금도 미국의 관세정책이 계속 바뀌고 있는 것 같은데, 현재 상황을 어떻게 보면 좋을까요?\n02:20 불확실한 미국의 관세정책이 이번 경제 전망에 어떻게 반영됐나요?\n02:58 대부분이 수출을 통한 영향일 것 같은데, 구체적인 매커니즘이 궁금합니다.\n03:51 건설투자 전망이 많이 나빠졌는데, 일시적인 요인 외에 구조적인 요인도 영향을 준 걸까요?\n04:57 앞으로의 경기 흐름과 함께 긍정적으로 볼 수 있는 부분은 어떤 점이 있을까요?\n05:26 소비가 살아날 거라고 하셨는데, 아직은 체감이 잘 안됩니다. 그 이유는 무엇인가요?\n06:46 지난 전망보다 경제성장률은 낮췄는데, 물가상승률은 1.9%로 유지된 이유는 무엇인가요?\n\n\n✨더 자세한 정보가 궁금하다면?\n경제전망보고서(2025년 5월) \n🔗https://ko.fm/jYB\n\n7 comments\n### Transcript:\n인트로 [음악] 안녕하십니까 바로 지난주 한국은행 2025년 5월 경제전망이 발표됐는데요 경제전망은 한국은행이 지금 경제를 어떻게 바라보고 있는지 알 수 있는 아주 중요한 보고서입니다 그래서 오늘은 그 내용을 살펴보는 시간을 준비했습니다 먼저 이번 경제 전망에서는 성장률 전망치를 1.5%에서 0.8%로 8%로 크게 낮추셨는데요 왜 이렇게 크게 하향 이번 경제전망에서 성장률 전망치를 하향 조정하셨는데, 그 배경이 무엇인가요? 조정하게 되셨을까요 어 경제전만은 여건 변화를 반영하여 조정하게 되는데요 아시겠지만 최근 안 좋은 일들이 많이 발생했기 때문에 어,이를 반영한 결과로 보시면 될 거 같고 크게 세 가지 요인으로 나누어서 말씀드릴 수 있겠습니다 먼저 경제 심리가 위축되고 회복이 지연되었던 부분입니다 저희가 지난 2월에 전망을 발표했을 때도 정치 불확실성이라든지 대내외 여권 악화로 경제 주체들의 심리가 위축된 점을 전망에 반영하였지만 그 이후로도 정치불확실성이 좀 더 이어지고 미 정부가 관세 정책을 저희 예상보다 더 강하게 추진하면서 경제 심리가 회복되지 못하는 상황이 지속되었습니다 두 번째로는 건설 경기 침체가 심화된 점입니다 당초에도 건설 경기가 부진한 상황이었지만 최근 들어 부진폭이 크게 확대되면서 1분기 역성장의 주요 원인으로도 작용하였습니다 세 번째로는 앞서 잠시 말씀드렸지만 미국의 관세 정책이 강화되면서 앞으로 수출이 둔화될 것으로 예상되는 점을 반영하였습니다 그리고 이외에 대형산뿌이나 기상악화 건설현장 사고 같은 일시적인 요인들도 올해 경제 성장률 전망을 낮추는 원인이 되었습니다 경제 성장률 전망을 낮춘 요인으로 미국의 관세 정책을 언급하셨는데요 지금도 미국의 관세 지금도 미국의 관세정책이 계속 바뀌고 있는 것 같은데, 현재 상황을 어떻게 보면 좋을까요? 정책이 계속 바뀌고 있는 것 같습니다 그럼 현재 상황을 어떻게 보면 좋을까요\n 네 미국은 철강 알루미늄과 자동차의 품목 관세 25%를 매기고 있습니다 어 거기다가 반도체 스마트폰에 대해서도 품목 관세를 부과할 것이라고 밝힌 상황이고요 어 품목 관세 외에도 모든 국가에 대해 상호관세를 부과하였는데요 어 최근에는 상호관세에 대해 무효 무효 판결이 나고 여기에 항소가 이어지면서 앞으로 어떻게 진행될지 불투명한 상황입니다 아 굉장히 복잡하네요 그럼 이렇게 불확실한 미국의 관세정책이 이번 경제 전망에 어떻게 반영됐나요? 복잡하고 불확실한 미국의 관세 정책이 이번 경제전망에는 어떻게 반영됐나요 어 사실 작년 말부터 미국이 관세 정책을 적극적으로 쓸 거라고 예상이 많았기 때문에 어 작년 11월 그리고 올해 2월 전망에도 그 영향을 반영했습니다 어 하지만 실제 미국 관세의 범위화 정도가 예상보다 강했고요 어 구체적으로 말씀드리면 2월 대비 경제 성장률 전망치가 0.7% 7% 포인트 낮아졌는데 어 여기에 미국 관세 정책의 영향이 0.3에서 0.4% 4% 포인트 정도 차지하고 있습니다\n 아 그럼 거의 절반 정도가 미국 관세 정책의 영향이네요 대부분이 수출을 통한 영향일 것 같은데, 구체적인 매커니즘이 궁금합니다. 대부분이 수출을 통한 영향일 것 같은데 구체적인 메커니즘도 궁금합니다 어 일단 단기적으로 관세 때문에 수출 가격이 올라가기 때문에 어 미국 사람들이 우리 제품을 덜 사게 되는 효과가 있고요 어 장기적으로는 우리 기업들이 미국 내에 직접 공장을 지어서 어 생산하게 되기 때문에 어 수출이 줄어드는 효과가 있습니다 이런 점들을 볼 때 가장 큰 타격을 받을 수 있는 건 자동차 부문으로 보고 있습니다 어 실제로 분석해 보면 자동차 수출만으로 전체 수출이 0.6%나 어 주는 것으로 나왔고요 그다음에 또 철강 반도체도 영향을 많이 받을 것으로 보고 있습니다\n 네 설명 감사합니다 앞부분에 말씀해 주셨듯이 건설 투자 전망도 많이 안 좋아졌습니다 지난 전망에서는 -2.8%였던 건설 투자가 -6.1%로 1%로 크게 떨어졌던데 건설투자 전망이 많이 나빠졌는데, 일시적인 요인 외에 구조적인 요인도 영향을 준 걸까요? 앞서 말씀해 주셨던 일시적인 요인 외에 구조적인 요인도 반영된 건가요 어 네 건설투자 부진에는 경기적 의시적 요인뿐만 아니라 구조적인 요인까지 복합적으로 작용하고 있는 것으로 판단하고 있습니다 건설 투자는 저희가 이미 선행 지표인 착공이 그가 위축되었던 점을 감안해서 건물 부문 위주로 부진이 이어질 것으로는 전망해 오고 있었는데요 그런데 작년 말부터 불확실성이 확대되고 심리도 위축되면서 아파트들의 분양 일정이 연기되고 또 건설 현장 사고 등으로 작업일수도 줄면서 건설 투자가 예상보다 더 크게 위축되었습니다 이렇게 부진폭이 더 커진 상황에서 하반기로 갈수록 금융 요건이 완화되고 경제 심리도 회복되면서 건설 투자가 조금씩 나아지기는 하겠지만 아직 미분양된 지방 아파트가 많이 남아 있고 상가도 비어 있는 곳이 많아서 이러한 구조적 요인까지 감안할 때 회복이 빠르지는 못할 것으로 보아서 저희가 건설 투자 전망치를 추가적으로 낮추게 되었습니다 그렇군요 지금까지 말씀을 들어보면 사실 다 안 좋은 얘기들이었는데 혹시 앞으로의 경기 흐름과 함께 긍정적으로 볼 수 있는 부분은 어떤 점이 있을까요? 긍정적으로 볼 수 있는 부분은 없을까요 앞으로의 경기 흐름과 함께 설명해 주시면 감사하겠습니다\n 수출은 좀 전에 설명드린 것처럼 관세 영향으로 둔화되겠지만 소비나 건설 투자와 같은 내수는 회복되면서 앞으로는 우리 경제가 점차 개선될 것으로 보고 있습니다 위축되었던 경제 심리가 최근 크게 회복되었고 작년 10월부터 이어진 금리 인하와 추경의 효과도 나타나면서 내수를 중심으로 성장세를 보일 것으로 예상하고 소비가 살아날 거라고 하셨는데, 아직은 체감이 잘 안됩니다. 그 이유는 무엇인가요? 있습니다 말씀 중 소비가 살아날 거라고 하셨는데 아직은 크게 체감되는 것 같지는 않습니다 좀 더 설명해 주실 수 있을까요\n 네 1분기에는 GDP와 마찬가지로 소비도 조금 줄어들었습니다 이것은 경제 주체들의 심리가 위축되면서 지갑을 닫았기 때문으로 보고 있는데요 하지만 앞으로는 방금 말씀드린 심리 회복 금리 인하 효과에 더해서 작년 하반기부터 개선되었던 가게 소득도 소비 회복에 보탬이 될 것으로 보고 있습니다 실제로 카드 사용해서도 최근 개선 조짐이 나타나고 있습니다 그래도 앞으로 내수를 중심으로 성장할 수 있다니 참 다행인 것 같습니다 지금까지 내용을 종합해 보면 수출이 줄겠지만 내수를 중심으로 우리 경제가 회복할 것으로 보인다라고 말할 수 있겠네요 그런데이 부분에 대해서도 아직 불확실한 상황이 좀 많아 보입니다\n 네 맞습니다 최근 미연방 법원에서 상호관세 무효와 판결을 내리고 또 미정부가 이에 항소하는 이런 사례에서도 보시듯이 우리 경제를 둘러싼 불확실성이 여전히 높은데요 이러한 불확실성은 상방과 하방 양 방향으로 모두 큰 상황입니다 예를 들어 미국이랑 관세협상이 어떻게 되냐에 따라서 경제가 더 좋아질 수도 안 좋아질 수도 있고요 또 정부 경기 부양책 등에도 크게 영향 받을 것으로 보입니다\n 네 그런 마지막 질문입니다 지난 전망보다 경제성장률은 낮췄는데, 물가상승률은 1.9%로 유지된 이유는 무엇인가요? 지난 전망과 비교해서 경제 성장률은 낮췄는데 물가 상승률은 그대로 1.9%로 유지하셨어요 그건 왜 그런 건가요 말씀처럼 성장률이 낮아지면이는 물가 상승률을 낮추는 압력으로 작용하게 됩니다 하지만 올해 상반기에 가공식품이나 보험료 외식 이런 부분에서 서비스 가격이 높아지다 보니 성장률이 낮아지는 부분이나 또 국제 유가 하락 등과 상세될 것으로 보았습니다 그래서 물가 상승률은 그대로 1.9%로 전망을 했고요 앞으로 물가 상승률은 최근 변동이 큰 유가와 환율 그리고 정부의 물가 안정 대책과 국내외의 경기 흐름에 주로 영향을 받을 것으로 보고 있습니다\n 네 앞으로는 우리 경제 산재에 있는 여러 가지 불확실성이 줄어들면 좋겠네요 지금까지 한국은행 2025년 5월 경제전망 보고서 내용에 대해 살펴봤는데요 좀 더 자세히 알고 싶으신 분은 한국은행 홈페이지에서 경제전망 보고서를 다운받아 읽어 보실 수 있습니다 앞으로 BOK 경제 브리핑에 많은 관심 부탁드립니다 감사합니다 [음악]'},
  {'url': 'https://www.kdi.re.kr/research/economy',
   'title': 'KDI 경제전망 | 수정, 2025년 8월',
   'content': '□ 2025년 원유 도입단가(두바이유 기준)는 수요 부진에 기인하여 2024년(배럴당 80 달러)보다 낮은 69달러를 기록한 후 2026년에는 66달러로 소폭 하락할 것으로 전제\n\n   □ 실질실효환율로 평가한 원화가치는 최근 수준에서 큰 변동이 없을 것으로 전제\n\n2. 2025~26년 국내경제 전망\n\n   □ 우리 경제는 2025년에 건설업 부진과 통상 여건 악화로 0.8% 성장하는 데 그친 후,2026년에는 통상분쟁의 여파에도 불구하고 완만한 내수 회복으로 1.6% 성장할 전망 [...] 우리 경제는2025년에 건설업 부진과 통상 여건 악화로 0.8% 성장하는 데 그친 후,2026년에는 통상분쟁의 여파에도 불구하고 완만한 내수 회복으로 1.6% 성장할 전망 [...] 소비자물가는 2025년에 경기 둔화 및 유가 하락으로 1.7% 상승한 후, 2026년에는 국제유가 하락폭이 축소되고 내수도 완만한 회복세를 나타내면서 1.8%정도 상승할 전망\n   민간소비는 금년에도 1.1% 내외의 낮은 증가율을 기록하겠으나, 정국 불안의 영향이 완화되고 금리 인하도 반영되면서 내년에는 1.6%의 완만한 회복세를 나타낼 전망\n   설비투자는 높은 대외 불확실성에도 불구하고 고금리 기조가 완화되는 가운데 반도체 관련 투자 수요도 양호한 흐름을 나타냄에 따라 금년(1.7%)과 내년(1.6%)에 완만한 증가세를 지속할 것으로 예상됨.\n   건설투자는 작년(-3.0%)에 이어 금년(-4.2%)에도 감소세를 지속하겠으나, 건설수주 개선의 영향이 점차 반영되며 내년에는 2.4% 정도 증가하면서 부진이 완화될 전망\n   수출은 미국 관세인상에 따른 세계교역 위축으로 둔화될 것으로 전망\n   경상수지는 교역조건 개선에도 불구하고 수출 부진으로 흑자폭이 축소될 전망',
   'score': 0.8638634,
   'raw_content': 'KDI 경제전망, 2025 상반기 - KDI 한국개발연구원 - 연구 - 경제전망 - 경제전망\n\n===============\n\n[본문 바로가기](https://www.kdi.re.kr/research/economy#contents)\n\n[![Image 3: KDI 한국개발연구원](https://www.kdi.re.kr/res/img/KDI_logo.png)](https://www.kdi.re.kr/)\n=============================================================================================\n\n*   연구\n\n**연구**\nKDI는\n\n"미래를 여는 연구"를 통해\n\n정책 대안을 제시합니다.\n-------------------------------------------\n\n    *   [연구 보고서](https://www.kdi.re.kr/research/reportList)\n    *   [KDI FOCUS](https://www.kdi.re.kr/research/focusList)\n    *   [경제전망](https://www.kdi.re.kr/research/economy)\n        *   [현안분석](https://www.kdi.re.kr/research/analysisList)\n\n    *   [KDI 경제동향](https://www.kdi.re.kr/research/monTrends)\n    *   [KDI 북한경제리뷰](https://www.kdi.re.kr/research/monNorth)\n    *   [KDI JEP](https://www.kdi.re.kr/research/jep)\n    *   [기타 보고서](https://www.kdi.re.kr/research/etcReportList)\n    *   [나라경제](https://www.kdi.re.kr/research/monCountry)\n    *   [Economic Bulletin](https://www.kdi.re.kr/research/monEb)\n\n    *   [연구 주제](https://www.kdi.re.kr/research/topicList)\n        *   [거시](https://www.kdi.re.kr/research/topicList?cd=A)\n        *   [금융](https://www.kdi.re.kr/research/topicList?cd=B)\n        *   [법경제](https://www.kdi.re.kr/research/topicList?cd=C)\n        *   [규제](https://www.kdi.re.kr/research/topicList?cd=D)\n        *   [노동](https://www.kdi.re.kr/research/topicList?cd=E)\n        *   [교육](https://www.kdi.re.kr/research/topicList?cd=F)\n        *   [산업](https://www.kdi.re.kr/research/topicList?cd=G)\n        *   [국제경제](https://www.kdi.re.kr/research/topicList?cd=H)\n        *   [재정](https://www.kdi.re.kr/research/topicList?cd=I)\n        *   [복지](https://www.kdi.re.kr/research/topicList?cd=J)\n        *   [북한경제](https://www.kdi.re.kr/research/topicList?cd=K)\n        *   [공공투자](https://www.kdi.re.kr/research/topicList?cd=L)\n        *   [국토인프라](https://www.kdi.re.kr/research/topicList?cd=M)\n        *   [국제개발협력](https://www.kdi.re.kr/research/topicList?cd=N)\n        *   [경제교육](https://www.kdi.re.kr/research/topicList?cd=O)\n        *   [경제정보](https://www.kdi.re.kr/research/topicList?cd=P)\n\n[![Image 4: 표지](https://www.kdi.re.kr/kdidata/menu/menu_img_1-001.png)**연구 주제** KDI의 발간물을 다양한 연구 주제로 분류하여 제공합니다.](https://www.kdi.re.kr/research/topicList)[![Image 5: 표지](https://www.kdi.re.kr/kdidata/menu/menu_img_2-001.png)**연구과제 제안** KDI의 역할에 걸맞은 연구가 추진될 수 있도록 연구 과제를 제안해 주세요.](https://www.kdi.re.kr/share/researchList)\n\n*   소통\n\n**소통**\nKDI는\n\n한걸음 더 가까이\n\n여러분께 다가섭니다.\n-----------------------------------\n\n    *   [세미나](https://www.kdi.re.kr/research/economy#)\n        *   [컨퍼런스](https://www.kdi.re.kr/share/conferList)\n        *   [전문가 세미나](https://www.kdi.re.kr/share/seminarList)\n        *   [세미나 영상](https://www.kdi.re.kr/share/seminarMov)\n\n    *   [공지사항](https://www.kdi.re.kr/share/noticeList)\n    *   [연구원 동정](https://www.kdi.re.kr/share/centerList)\n    *   [보도자료](https://www.kdi.re.kr/share/pressList)\n    *   [언론기고](https://www.kdi.re.kr/share/pressContriList)\n    *   [언론보도](https://www.kdi.re.kr/share/pressRelease)\n\n    *   [매거진 KDlans](https://www.kdi.re.kr/share/kdiansList)\n    *   [채용](https://www.kdi.re.kr/share/recruitList)\n\n    *   [소통 콘텐츠](https://www.kdi.re.kr/share/multiMov)\n        *   [멀티콘텐츠](https://www.kdi.re.kr/share/multiMov)\n        *   [소셜박스](https://www.kdi.re.kr/share/socialBox)\n        *   [KDI 이용가이드](https://www.kdi.re.kr/share/userGuide?ug_cd=007004)\n        *   [연구과제 제안](https://www.kdi.re.kr/share/researchList)\n        *   [부조리신고센터](https://www.kdi.re.kr/share/absurdityCenter)\n        *   [Q&A](https://www.kdi.re.kr/share/qnaList)\n        *   [뉴스레터](https://www.kdi.re.kr/share/newsletter)\n        *   [KDI Open API](https://www.kdi.re.kr/share/openAPI)\n\n[![Image 6: 표지](https://www.kdi.re.kr/kdidata/menu/menu_img_1-002.png)**매거진 KDIans** 2025 SPRING VOL.64](https://www.kdi.re.kr/share/kdiansList)[![Image 7: 표지](https://www.kdi.re.kr/kdidata/menu/menu_img_2-002.png)**뉴스레터** KDI의 소식과 경제정책정보를 뉴스레터로 받아보세요.](https://www.kdi.re.kr/share/newsletter)\n\n*   소개\n\n**소개**\nsince 1971\n\n한국개발연구원의\n\n과거, 현재 그리고 미래\n------------------------------------------\n\n    *   [원장 소개](https://www.kdi.re.kr/introduce/greetings)\n        *   [인사말](https://www.kdi.re.kr/introduce/greetings)\n        *   [원장약력](https://www.kdi.re.kr/introduce/history)\n        *   [경영목표](https://www.kdi.re.kr/introduce/target)\n        *   [원장동정](https://www.kdi.re.kr/introduce/sympathy)\n        *   [역대원장](https://www.kdi.re.kr/introduce/historyLedger)\n\n    *   [조직도](https://www.kdi.re.kr/introduce/org)\n    *   [연구진](https://www.kdi.re.kr/introduce/expert)\n    *   [홍보](https://www.kdi.re.kr/research/economy#)\n        *   [연혁](https://www.kdi.re.kr/introduce/historyList)\n        *   [VISION HALL](https://www.kdi.re.kr/introduce/pmVision)\n        *   [기관 상징](https://www.kdi.re.kr/introduce/pmCi)\n        *   [브로슈어](https://www.kdi.re.kr/introduce/pmBrochure)\n\n    *   [부서 안내](https://www.kdi.re.kr/introduce/macroFinancial)\n        *   [거시ㆍ금융정책연구부](https://www.kdi.re.kr/introduce/macroFinancial)\n        *   [산업ㆍ시장정책연구부](https://www.kdi.re.kr/introduce/industryMarket)\n        *   [재정ㆍ사회정책연구부](https://www.kdi.re.kr/introduce/financeSocial)\n        *   [경제전망실](https://www.kdi.re.kr/introduce/economicOutlook)\n        *   [규제연구실](https://www.kdi.re.kr/introduce/regCenter)\n        *   [북한경제연구실](https://www.kdi.re.kr/introduce/northKoreanEconomic)\n        *   [글로벌경제연구실](https://www.kdi.re.kr/introduce/globalEconomy)\n        *   [경제교육·정보센터](https://www.kdi.re.kr/introduce/eiec)\n        *   [공공투자관리센터](https://www.kdi.re.kr/introduce/pimac)\n        *   [국제개발협력센터](https://www.kdi.re.kr/introduce/interCenter)\n\n[![Image 8: 표지](https://www.kdi.re.kr/kdidata/menu/menu_img_1-003.jpg)**인사말** KDI의 목표와 비전을 명확히 담은 원장님 인사말을 전합니다.](https://www.kdi.re.kr/introduce/greetings)[![Image 9: 표지](https://www.kdi.re.kr/kdidata/menu/menu_img_2-003.jpg)**연혁** KDI의 시대별 주요 연구 성과를 소개합니다.](https://www.kdi.re.kr/introduce/historyList)\n\n*   정보공개\n\n**정보\n\n공개**\n한국개발연구원의\n\n 정보공개제도를 안내해 \n\n드립니다.\n-----------------------------------------\n\n    *   [인권경영](https://www.kdi.re.kr/disclosure/humanScene)\n        *   [인권경영헌장](https://www.kdi.re.kr/disclosure/humanScene)\n        *   [인권경영 추진체계](https://www.kdi.re.kr/disclosure/humanPropel)\n        *   [인권경영 활동/교육](https://www.kdi.re.kr/disclosure/humanPlan)\n\n    *   [정보공개](https://www.kdi.re.kr/disclosure/openPolicy)\n        *   [정보공개제도 안내](https://www.kdi.re.kr/disclosure/openPolicy)\n        *   [사전정보공표](https://www.kdi.re.kr/disclosure/openDictionary)\n        *   [해외출장 보고](https://www.kdi.re.kr/disclosure/businessList)\n\n    *   [공공데이터 개방](https://www.kdi.re.kr/disclosure/publicData)\n    *   [사업실명제](https://www.kdi.re.kr/disclosure/realName)\n    *   [경영공시](https://www.kdi.re.kr/disclosure/operationOpen)\n\n*   [ENG](https://www.kdi.re.kr/eng/)\n\n검색 전체 메뉴 보기\n\n### [![Image 10: KDI 한국개발연구원](https://www.kdi.re.kr/res/img/KDI_logo.png)](https://www.kdi.re.kr/)\n\n#### SITEMAP\n\nCLOSE\n\n##### 연구\n\n*   [연구 보고서](https://www.kdi.re.kr/research/reportList)\n*   [KDI FOCUS](https://www.kdi.re.kr/research/focusList)\n*   [경제전망](https://www.kdi.re.kr/research/economy)\n    *   [현안분석](https://www.kdi.re.kr/research/analysisList)\n\n*   [KDI 경제동향](https://www.kdi.re.kr/research/monTrends)\n*   [KDI 북한경제리뷰](https://www.kdi.re.kr/research/monNorth)\n*   [KDI JEP](https://www.kdi.re.kr/research/jep)\n*   [기타 보고서](https://www.kdi.re.kr/research/etcReportList)\n*   [나라경제](https://www.kdi.re.kr/research/monCountry)\n*   [Economic Bulletin](https://www.kdi.re.kr/research/monEb)\n\n*   [연구 주제](https://www.kdi.re.kr/research/topicList)\n    *   [거시](https://www.kdi.re.kr/research/topicList?cd=A)\n    *   [금융](https://www.kdi.re.kr/research/topicList?cd=B)\n    *   [법경제](https://www.kdi.re.kr/research/topicList?cd=C)\n    *   [규제](https://www.kdi.re.kr/research/topicList?cd=D)\n    *   [노동](https://www.kdi.re.kr/research/topicList?cd=E)\n    *   [교육](https://www.kdi.re.kr/research/topicList?cd=F)\n    *   [산업](https://www.kdi.re.kr/research/topicList?cd=G)\n    *   [국제경제](https://www.kdi.re.kr/research/topicList?cd=H)\n    *   [재정](https://www.kdi.re.kr/research/topicList?cd=I)\n    *   [복지](https://www.kdi.re.kr/research/topicList?cd=J)\n    *   [북한경제](https://www.kdi.re.kr/research/topicList?cd=K)\n    *   [공공투자](https://www.kdi.re.kr/research/topicList?cd=L)\n    *   [국토인프라](https://www.kdi.re.kr/research/topicList?cd=M)\n    *   [국제개발협력](https://www.kdi.re.kr/research/topicList?cd=N)\n    *   [경제교육](https://www.kdi.re.kr/research/topicList?cd=O)\n    *   [경제정보](https://www.kdi.re.kr/research/topicList?cd=P)\n\n##### 소통\n\n*   [세미나](https://www.kdi.re.kr/research/economy#)\n    *   [컨퍼런스](https://www.kdi.re.kr/share/conferList)\n    *   [전문가 세미나](https://www.kdi.re.kr/share/seminarList)\n    *   [세미나 영상](https://www.kdi.re.kr/share/seminarMov)\n\n*   [공지사항](https://www.kdi.re.kr/share/noticeList)\n*   [연구원 동정](https://www.kdi.re.kr/share/centerList)\n*   [보도자료](https://www.kdi.re.kr/share/pressList)\n*   [언론기고](https://www.kdi.re.kr/share/pressContriList)\n*   [언론보도](https://www.kdi.re.kr/share/pressRelease)\n\n*   [매거진 KDlans](https://www.kdi.re.kr/share/kdiansList)\n*   [채용](https://www.kdi.re.kr/share/recruitList)\n\n*   [소통 콘텐츠](https://www.kdi.re.kr/share/multiMov)\n    *   [멀티콘텐츠](https://www.kdi.re.kr/share/multiMov)\n    *   [소셜박스](https://www.kdi.re.kr/share/socialBox)\n    *   [KDI 이용가이드](https://www.kdi.re.kr/share/userGuide?ug_cd=007004)\n    *   [연구과제 제안](https://www.kdi.re.kr/share/researchList)\n    *   [부조리신고센터](https://www.kdi.re.kr/share/absurdityCenter)\n    *   [Q&A](https://www.kdi.re.kr/share/qnaList)\n    *   [뉴스레터](https://www.kdi.re.kr/share/newsletter)\n    *   [KDI Open API](https://www.kdi.re.kr/share/openAPI)\n\n##### 소개\n\n*   [원장 소개](https://www.kdi.re.kr/introduce/greetings)\n    *   [인사말](https://www.kdi.re.kr/introduce/greetings)\n    *   [원장약력](https://www.kdi.re.kr/introduce/history)\n    *   [경영목표](https://www.kdi.re.kr/introduce/target)\n    *   [원장동정](https://www.kdi.re.kr/introduce/sympathy)\n    *   [역대원장](https://www.kdi.re.kr/introduce/historyLedger)\n\n*   [조직도](https://www.kdi.re.kr/introduce/org)\n*   [연구진](https://www.kdi.re.kr/introduce/expert)\n*   [홍보](https://www.kdi.re.kr/research/economy#)\n    *   [연혁](https://www.kdi.re.kr/introduce/historyList)\n    *   [VISION HALL](https://www.kdi.re.kr/introduce/pmVision)\n    *   [기관 상징](https://www.kdi.re.kr/introduce/pmCi)\n    *   [브로슈어](https://www.kdi.re.kr/introduce/pmBrochure)\n\n*   [부서 안내](https://www.kdi.re.kr/introduce/macroFinancial)\n    *   [거시ㆍ금융정책연구부](https://www.kdi.re.kr/introduce/macroFinancial)\n    *   [산업ㆍ시장정책연구부](https://www.kdi.re.kr/introduce/industryMarket)\n    *   [재정ㆍ사회정책연구부](https://www.kdi.re.kr/introduce/financeSocial)\n    *   [경제전망실](https://www.kdi.re.kr/introduce/economicOutlook)\n    *   [규제연구실](https://www.kdi.re.kr/introduce/regCenter)\n    *   [북한경제연구실](https://www.kdi.re.kr/introduce/northKoreanEconomic)\n    *   [글로벌경제연구실](https://www.kdi.re.kr/introduce/globalEconomy)\n    *   [경제교육·정보센터](https://www.kdi.re.kr/introduce/eiec)\n    *   [공공투자관리센터](https://www.kdi.re.kr/introduce/pimac)\n    *   [국제개발협력센터](https://www.kdi.re.kr/introduce/interCenter)\n\n##### 정보공개\n\n*   [인권경영](https://www.kdi.re.kr/disclosure/humanScene)\n    *   [인권경영헌장](https://www.kdi.re.kr/disclosure/humanScene)\n    *   [인권경영 추진체계](https://www.kdi.re.kr/disclosure/humanPropel)\n    *   [인권경영 활동/교육](https://www.kdi.re.kr/disclosure/humanPlan)\n\n*   [정보공개](https://www.kdi.re.kr/disclosure/openPolicy)\n    *   [정보공개제도 안내](https://www.kdi.re.kr/disclosure/openPolicy)\n    *   [사전정보공표](https://www.kdi.re.kr/disclosure/openDictionary)\n    *   [해외출장 보고](https://www.kdi.re.kr/disclosure/businessList)\n\n*   [공공데이터 개방](https://www.kdi.re.kr/disclosure/publicData)\n*   [사업실명제](https://www.kdi.re.kr/disclosure/realName)\n*   [경영공시](https://www.kdi.re.kr/disclosure/operationOpen)\n\n*   [도서회원](https://www.kdi.re.kr/bookMember/booksLogin)\n*   [찾아오시는길](https://www.kdi.re.kr/infomation/location)\n\n*   [고객헌장](https://www.kdi.re.kr/servicePolicy/charter)\n*   [개인정보처리방침](https://www.kdi.re.kr/servicePolicy/privacy)\n*   [영상정보처리기기 운영ㆍ관리방침](https://www.kdi.re.kr/servicePolicy/mediaPrivacy)\n*   [저작권정책](https://www.kdi.re.kr/servicePolicy/copyright)\n*   [이메일주소 무단수집거부](https://www.kdi.re.kr/servicePolicy/email)\n\nSEARCH 검색\n\n**인기 검색어**\n\nOPEN\n\n### SPOTLIGHT\n\n[**공지사항****왓츠업 뉴스레터 48호가 도착했습니다!** 소득지원정책, 어떻게 설계해야 할까요? 공정한 평가를 위한 분석툴을 제안합니다. 왓츠업 뉴스레터에서 지금 확인하세요! 2025.05.29](https://www.kdi.re.kr/share/newsletter?vno=48&pg=1)\n\n[**북한경제리뷰****KDI 북한경제리뷰 2025년 5월** 이번 호는 북한의 정보통신기술 발전과 그 경제적 파급효과를 분석한 네 편의 보고서를 수록함 2025.05.29](https://www.kdi.re.kr/research/monNorth?pub_no=18802)\n\n[**언론기고****모태펀드, 혁신을 위한 마중물** 모태펀드 존속기간을 연장하고 민간 벤처투자 시장과의 연계를 강화해 스타트업 혁신생태계를 장기적으로 뒷받침해야... 2025.05.28](https://www.kdi.re.kr/share/pressContriView?bd_no=51911)\n\n[**보도자료****KDI-한국은행 공동 심포지엄 개최: 초고령사회의 빈곤과 노동: 정책 방향을 묻다** 조동철 KDI 원장은 초고령사회 진입이 제기하는 구조적 문제를 강조하며, 이번 심포지엄이 정책 방향 설정의 이정표가 되길 기대한다고 밝힘 2025.05.15](https://www.kdi.re.kr/share/conferPress?sm_no=593)\n\n닫기\n\n[BACK](javascript:history.back();)\n\n[HOME](https://www.kdi.re.kr/)\n\n연구\n*   [연구](https://www.kdi.re.kr/research/reportList)\n*   [소통](https://www.kdi.re.kr/share/conferList)\n*   [소개](https://www.kdi.re.kr/introduce/org)\n\n경제전망\n*   [연구 보고서](https://www.kdi.re.kr/research/reportList)\n*   [KDI FOCUS](https://www.kdi.re.kr/research/focusList)\n*   [경제전망](https://www.kdi.re.kr/research/economy)\n*   [KDI 경제동향](https://www.kdi.re.kr/research/monTrends)\n*   [KDI 북한경제리뷰](https://www.kdi.re.kr/research/monNorth)\n*   [KDI JEP](https://www.kdi.re.kr/research/jep)\n*   [기타 보고서](https://www.kdi.re.kr/research/etcReportList)\n*   [나라경제](https://www.kdi.re.kr/research/monCountry)\n*   [Economic Bulletin](https://www.kdi.re.kr/research/monEb)\n*   [연구 주제](https://www.kdi.re.kr/research/topicList)\n\n*   [현안분석](https://www.kdi.re.kr/research/analysisList)\n\n[BACK](javascript:history.back();)\n\nKDI 경제전망, 2025 상반기 \n2025.05.14\n------------------------------\n\n![Image 11: 배경](https://www.kdi.re.kr/research/economy)\n\n년도 선택 \n\n원문 다운로드\n\n[네이버블로그](javascript:;)[페이스북](javascript:;)[프린트](javascript:;)[URL 복사](javascript:;)[크게보기](javascript:;)[작게보기](javascript:;)\n\n**요약 영상보고서**[KID YOUTUBE 바로가기](http://www.youtube.com/KDIofficial)\n\n![Image 12: 유튜브 영상](https://www.kdi.re.kr/res/img/img_utb-guide.gif)\n\n우리 경제는**2025년**에 건설업 부진과 통상 여건 악화로 **0.8% 성장**하는 데 그친 후,**2026년**에는 통상분쟁의 여파에도 불구하고 완만한 **내수 회복**으로 **1.6% 성장**할 전망\n\n*   **소비자물가**는 2025년에 경기 둔화 및 유가 하락으로 1.7% 상승한 후, 2026년에는 국제유가 하락폭이 축소되고 내수도 완만한 회복세를 나타내면서 1.8%정도 상승할 전망\n*   **민간소비**는 금년에도 1.1% 내외의 낮은 증가율을 기록하겠으나, 정국 불안의 영향이 완화되고 금리 인하도 반영되면서 내년에는 1.6%의 완만한 회복세를 나타낼 전망\n*   **설비투자**는 높은 대외 불확실성에도 불구하고 고금리 기조가 완화되는 가운데 반도체 관련 투자 수요도 양호한 흐름을 나타냄에 따라 금년(1.7%)과 내년(1.6%)에 완만한 증가세를 지속할 것으로 예상됨.\n*   **건설투자**는 작년(-3.0%)에 이어 금년(-4.2%)에도 감소세를 지속하겠으나, 건설수주 개선의 영향이 점차 반영되며 내년에는 2.4% 정도 증가하면서 부진이 완화될 전망\n*   **수출**은 미국 관세인상에 따른 세계교역 위축으로 둔화될 것으로 전망\n*   **경상수지**는 교역조건 개선에도 불구하고 수출 부진으로 흑자폭이 축소될 전망\n*   **취업자 수** 증가폭은 작년 16만명에서 금년 9만명, 내년 7만명 수준으로 축소될 전망\n\n**Ⅰ. 현 경제상황에 대한 인식**\n\n*   **□ 최근 우리 경제는 대내외 불확실성이 확대되면서 성장세가 둔화되는 모습**\n\n*    · 1/4분기 국내총생산은 전년동기대비 0.1% 감소하였으며, 계절조정 전기대비로도 4분기 연속 0% 내외의 증가율을 기록하며 정체되는 모습\n*    · 경제활동별로는 건설업이 대폭 감소한 가운데 제조업과 서비스업의 증가세도 둔화\n\n*   **□ 내수는 정국 불안에 따른 심리 위축이 지속되고 대외 불확실성이 확대되면서 가시적인 회복세가 나타나지 않는 모습**\n\n*    · 소비자심리 위축으로 숙박⋅음식 등 서비스를 중심으로 민간소비 증가세가 둔화\n*    · 설비투자가 양호한 증가세를 보였으나 대외 불확실성 확대로 기업심리가 위축되는 등 투자 여건이 악화되고 있으며, 건설투자는 감소세가 확대되며 부진이 심화\n*    ·경기 부진에 따라 물가상승세가 2% 내외를 지속한 가운데, 고용증가세는 건설업과 제조업에서 감소세가 심화되면서 완만한 수준에 머무름.\n*    ·한편, 그동안 내수경기에 하방 압력으로 작용해 왔던 고금리 기조와 건설수주 부진이 일부 해소되고 있어 향후 시차를 두고 내수 부진이 다소 완화될 가능성을 시사\n\n*   **□ 수출은 최근까지 반도체의 호조세에도 불구하고 여타 산업의 부진으로 둔화되고 있으며,향후에는 미국 관세인상으로 수출 여건이 더욱 악화될 가능성**\n\n*    · 상품수출(물량)이 감소한 가운데 경기 부진으로 상품수입(물량) 증가세도 둔화\n*    · 대규모 경상수지 흑자 추세가 지속되고 순대외자산 규모도 GDP 대비 60% 수준까지 증가하는 등 대외건전성은 양호한 모습\n*    · 4월 들어 미국이 관세를 대폭 인상하였으며, 통상 관련 불확실성도 급격히 상승\n*    · 최근 IMF는 통상분쟁의 부정적 영향을 반영하여 세계경제 성장률을 미국과 중국을 중심으로 대폭 하향 조정하였으며, 글로벌 경기 둔화로 국제유가도 하락세를 보임.\n\n*   **□ 이와 같은 대내외 여건을 고려할 때, 우리 경제는 통상 여건 악화에 따른 수출 부진으로 성장세가 둔화될 전망**\n\n*    · 내수가 여전히 미약한 증가세에 머물러 있으나, 금리 하락세, 소비심리 개선 및 건설 수주 증가 등이 반영되면서 향후 부진이 다소 완화될 것으로 예상됨.\n*    ·그러나 미국이 광범위한 품목에 대해 관세를 인상한 가운데, 관련 불확실성도 이례적인 수준으로 확대되며 수출 여건이 급격히 악화\n\n*   **□ 이러한 경기 둔화 흐름을 감안하여 거시정책은 완화적 기조로 운용하는 것이 바람직**\n\n*    · 대내외 수요 둔화로 초래될 수 있는 물가 하방 압력을 축소하기 위해 통화정책은 보다 완화적인 기조로 운용하는 것이 바람직\n*    · 재정정책은 큰 폭의 관리재정수지 적자(86.4조원, GDP 대비 3.3%)를 감안하면 이미 어느 정도 완화적 기조로 편성되어 있는바, 정부지출 추가 확대에는 신중하게 접근\n\n*   **□ 이와 함께 잠재성장률 하락세를 감안하여, 경제 구조개혁을 위한 정책적 노력을 지속**\n\n*    · 금년 우리 경제의 잠재성장률은 1%대 후반으로 추정되며, 2040년대에는 잠재성장률이 0% 내외까지 하락할 전망\n*    · 따라서 진입장벽과 노동시장 경직성을 완화하는 등 생산성 개선을 위한 노력이 필요\n*    · 이와 함께 거시정책 기조도 이러한 잠재성장률 하락 추세를 감안하여 설정할 필요\n\n**Ⅱ. 2025~26년 국내경제 전망**\n\n**1. 대외여건에 대한 주요 전제**\n\n*   **□ 2025~26년 세계경제는 국제 무역이 위축됨에 따라 성장세가 약화될 것으로 전제**\n\n*    · 최근 IMF는 미국의 보호무역주의가 초래한 통상환경 악화로 2025년 세계경제가 2024년(3.3%)보다 낮은 2.8%의 성장률을 기록한 후, 2026년에도 3.0% 성장에 그칠 것으로 전망\n*    · 미국 관세정책은 기본관세 10%와 현재의 품목별 관세율이 향후에도 지속될 것으로 전제\n\n*   **□ 2025년 원유 도입단가(두바이유 기준)는 수요 부진에 기인하여 2024년(배럴당 80 달러)보다 낮은 69달러를 기록한 후 2026년에는 66달러로 소폭 하락할 것으로 전제**\n\n*   **□ 실질실효환율로 평가한 원화가치는 최근 수준에서 큰 변동이 없을 것으로 전제**\n\n**2. 2025~26년 국내경제 전망**\n\n*   **□ 우리 경제는 2025년에 건설업 부진과 통상 여건 악화로 0.8% 성장하는 데 그친 후,2026년에는 통상분쟁의 여파에도 불구하고 완만한 내수 회복으로 1.6% 성장할 전망**\n\n*    · 민간소비는 금년에도 1.1% 내외의 낮은 증가율을 기록하겠으나, 정국 불안의 영향이 완화되고 금리 인하도 반영되면서 내년에는 1.6%의 완만한 회복세를 나타낼 전망\n*    · 설비투자는 높은 대외 불확실성에도 불구하고 고금리 기조가 완화되는 가운데 반도체 관련 투자 수요도 양호한 흐름을 나타냄에 따라 금년(1.7%)과 내년(1.6%)에 완만한 증가세를 지속할 것으로 예상됨.\n*    · 건설투자는 작년(-3.0%)에 이어 금년(-4.2%)에도 감소세를 지속하겠으나, 건설수주 개선의 영향이 점차 반영되며 내년에는 2.4% 정도 증가하면서 부진이 완화될 전망\n*    · 수출은 미국 관세인상에 따른 세계교역 위축으로 둔화될 것으로 전망\n*    · 경상수지는 교역조건 개선에도 불구하고 수출 부진으로 흑자폭이 축소될 전망\n\n*   **□ 소비자물가는 경기 둔화 및 유가 하락으로 낮은 상승률을 지속할 것으로 전망**\n\n*    · 소비자물가는 금년에 1.7% 상승한 후, 내년에는 국제유가 하락폭이 축소되고 내수도 완만한 회복세를 나타내면서 1.8% 정도 상승할 전망\n*    · 근원물가(식료품 및 에너지 제외)도 금년에 1.8% 수준의 낮은 상승률을 기록한 후,내년에는 1.9%로 상승폭이 소폭 확대될 것으로 예상됨.\n\n*   **□ 인구구조 변화가 지속적인 하방 압력으로 작용하는 가운데, 불확실성 증대에 따른 고용 여건 악화로 취업자 수 증가폭은 작년 16만명에서 금년 9만명, 내년 7만명 수준으로 축소될 전망**\n*   \n · 실업률은 작년 2.8%에서 금년과 내년에 각각 3.0% 수준으로 소폭 상승할 전망\n\n**3. 전망의 위험요인**\n\n*   **□ 우리 경제는 미국 관세정책과 여타 국가들의 대응에 따라 평소에 비해 상당히 높은 불확실성에 직면하고 있음.**\n\n*    ·미국이 높은 관세율을 유지하는 가운데 상대국들이 보복관세로 대응하며 통상분쟁이 격화되는 경우, 우리 경제의 성장에도 추가적인 하방 압력으로 작용할 것으로 예상됨.\n*    ·반면, 협상이 원만히 타결되면서 수출 여건이 빠르게 개선될 가능성도 존재\n\n*   **□ 대내적으로는 주택경기가 하락하면서 건설업체들의 재무건전성이 악화되는 경우, 건설 투자 회복이 지연될 가능성**\n\n*    · 비수도권에서 준공 후 미분양이 급증하는 가운데 주택매매가격이 하락세를 지속하는 등 주택경기가 하락하고 있음.\n*    · 이러한 상황에서 부동산 PF 대출 구조조정이 지연되고 건설업체 재무건전성이 추가적으로 악화될 경우, 공사진행에 차질이 발생하면서 건설투자 회복이 제약될 수 있음.\n\n![Image 13](https://www.kdi.re.kr/upload/publication/18775/editor/A07E10A01B_20250514175922.png)\n\n**Ⅲ. 정책방향**\n\n**1. 재정정책**\n\n*   **□ 최근 큰 폭의 관리재정수지 적자가 지속되고 있음을 감안할 때, 재정건전성 유지를 위해 추가적인 재정지출에는 신중하게 접근하는 것이 바람직**\n\n*    · 코로나19 위기가 지나간 2023~24년에도 큰 폭의 관리재정수지 적자가 발생\n*    · 추가경정예산이 확정됨에 따라 2025년에도 관리재정수지 적자가 GDP 대비 3.3%로 상향 조정되었으며, 경기 둔화에 따른 세입 여건 악화를 감안하면 관리재정수지 적자 폭이 더욱 확대될 가능성도 존재\n*    · 이와 같이 예산이 이미 확장적 기조로 편성되어 있다는 점을 감안하여 정부지출 추가 확대는 신중을 기하는 것이 바람직\n\n*   **□ 잠재성장률 하락에 따른 세입 여건 악화와 국민연금 지급보장 법제화 등을 감안하여,재정건전성이 크게 훼손되지 않도록 사전적으로 노력할 필요**\n\n*    · 국민부담률이 빠르게 상승하고 있음에도 불구하고 인구구조 변화에 따른 중장기적 성장세 둔화로 향후 국가채무가 급증할 것으로 예상되고 있음.\n*    · 국민연금법 개정에도 불구하고 향후 기금 고갈이 예상되며, 국가의 연금급여 지급보장이 명문화됨에 따라 미래세대의 부담이 크게 확대될 가능성\n*    · 이와 같이 중장기적으로 재정 여건이 크게 악화될 수 있음을 감안하여, 재정적자가 지나치게 확대되지 않도록 사전적으로 제도를 개편할 필요\n\n**2. 통화정책**\n\n*   **□ 통화정책은 물가 하방 압력에 대응하여 보다 완화적인 기조로 운용하는 것이 바람직**\n\n*    · 최근 경기 둔화에 따른 물가 하방 압력이 존재하며, 대외 불확실성 확대로 향후 물가 하방 압력이 확대될 가능성\n*    · 대외건전성이 양호한 가운데 금융시스템 위험도 높지 않을 것으로 판단되므로, 통화정책은 물가 안정에 중점을 두고 운용할 수 있을 것으로 사료됨.\n*    · 이러한 점을 종합적으로 고려할 때, 통화정책은 수요 둔화로 초래될 수 있는 물가 하방 압력을 축소할 수 있도록 완화적으로 운용하는 것이 바람직\n\n**3. 금융정책**\n\n*   **□ 대내외 불확실성이 높은 상황임에도 금융시스템은 대체로 안정적인 모습**\n\n*    · 주요 금융업권의 건전성 지표가 규제 수준을 상회하는 등 단기적으로 금융시장의 시스템리스크 가능성은 높지 않은 것으로 판단됨.\n*    · 2단계 스트레스 DSR 규제 시행, 가계대출 금융감독 등 거시건전성 정책 강화에 따라 GDP 대비 가계부채 비율은 완만한 하락 추세를 지속\n*    · 이와 함께 국가 부도위험을 나타내는 CDS 프리미엄이 낮은 수준을 유지하고 있으며,연간 1,000억달러 내외의 대규모 경상수지 흑자와 GDP 대비 60% 수준의 순대외자산을 감안하면 대외건전성도 비교적 양호한 모습\n\n*   **□ 구조적으로 생존 가능성이 희박한 부실 기업에 대한 금융지원을 자제하고 거시건전성 정책을 일관되게 추진하는 것이 바람직**\n\n*    · 기준금리 인하 기조, 부동산 PF 구조조정 추진 등으로 금융기관 자산건전성이 일부 개선되었으나, 가계 및 개인사업자 대출, 부동산 PF 연체율은 높은 수준을 지속\n*    · 취약부문에 대한 금융지원은 개별 차주의 상환능력을 감안하여 차별적으로 적용함으로써 도덕적 해이를 최소화할 필요\n*    · 중장기적 금융시스템 안정을 위해 금년 하반기로 예고된 3단계 스트레스 DSR 규제를 차질 없이 실행하고, 전세자금대출과 정책자금에 대한 SR 규제 예외 조항을 축소하는 등 차주 단위의 건전성 강화를 위한 규제 개선을 지속할 필요\n\n[![Image 14: 표지](https://img.youtube.com/vi/Uxn8Slc3ziU/mqdefault.jpg) _기타(경제전망)_**대선까지 치뤘겠다...2025년 한국경제는 어떻게 되는걸까?**](javascript:kdifn.slideLeftOpen(\'.move_movie_view.pub_668\');playMovie(\'.move_movie_view.pub_668\', \'Y\');)[![Image 15: 표지](https://img.youtube.com/vi/gg7kwapU-SA/mqdefault.jpg) _숏츠_**2025년 상반기 KDI 경제전망 (shorts)**](javascript:kdifn.slideLeftOpen(\'.move_movie_view.eco_664\');)\n\n**목차별 원문보기**\n*   요약\n\n원문 다운로드\n*   현 경제상황에 대한 인식\n\n원문 다운로드\n*   2025~26년 국내경제 전망\n\n원문 다운로드\n*   [잠재성장률 전망과 정책적 시사점 자세히보기](https://www.kdi.re.kr/research/analysisView?art_no=3671)\n*   [인구 요인이 소비성향에 미치는 영향과 시사점 자세히보기](https://www.kdi.re.kr/research/analysisView?art_no=3669)\n*   [최근의 환율 변동이 물가에 미치는 영향 자세히보기](https://www.kdi.re.kr/research/analysisView?art_no=3670)\n*   국내경제 동향\n\n원문 다운로드\n*   세계경제 동향\n\n원문 다운로드\n*   정책방향\n\n원문 다운로드\n\n### 경제 현안 분석\n\n*   [![Image 16: 표지](https://img.youtube.com/vi/Ulc-Owhu8Nc/mqdefault.jpg) **잠재성장률 전망과 정책적 시사점** ■ 인구구조 변화로 우리 경제의 잠재성장률은 향후에도 하락세를 지속하겠으며, 2040년대에는 0% 내외까지 하락할 것으로 전망됨. - 금년 잠재성장률이 1%대 후반으로 추정되는 가운데, 기준 시나리오에서는 2040년대 후반에 역성장이 예상되며, 경제 구조개혁이 지체되는 비관 시나리오에서는 역성장 시점이 2040년대 초반으로 앞당겨질 전망 - 따라서 경제 구조개혁을 통한 총요소생산성 개선에 역량을 집중할 필요 - 이와 함께 인구구조 변화에 따른 노동력 감소를 완화하기 위해 일？가정 양립, 고령층 경제활동 촉진, 노동시장 개방을 위한 정책적 노력을 지속 ■ 성장세 둔화에 따른 실질중립금리 하락으로 향후 명목금리하한(zero lower bound)이 제약될 가능성이 높아질 수 있으므로 기대인플레이션 안정을 위해 통화정책 체계를 점검 - 실질중립금리가 하락하는 가운데 기대인플레이션도 낮을 경우, 명목금리(=실질금리 + 기대인플레이션율)가 낮은 수준에 머무름에 따라 금리 인하폭이 제한될 수 있으므로, 고물가 위험뿐 아니라 저물가 위험에 대해서도 균형 있게 대응하는 것이 바람직 - 통화정책 목표로 추가 설정된 금융안정을 위해 높은 금리를 유지하는 경우 저물가를 유발할 수 있으므로, 금융안정을 유지하면서도 기대인플레이션이 지나치게 낮아지지 않도록 유도할 수 있는 통화정책 체계가 무엇인지에 대해서도 고민할 필요 ■ 잠재성장률 하락으로 정부 재정건전성 악화가 예상되는 가운데, 반복적인 경기부양으로 재정적자 기조가 만성화되지 않도록 유의 - 성장세 둔화에 따른 세입 기반 약화는 정부재정에 부담을 주는 요인이므로, 생산연령 인구 비중과 잠재성장률이 높았던 환경에서 설계된 제도를 향후에도 지속가능할 수 있도록 개편할 필요 - 이러한 맥락에서 경제 역동성 강화를 위해서는 재정지출에 의존하기보다 시장실패를 완화하고 경제적 왜곡을 초래하는 제도를 개선하는 데 역량을 집중할 필요 - 아울러 잠재성장률 하락에 따른 성장세 둔화를 단기적 경기 부진으로 판단하여 경기 부양을 반복할 경우, 재정건전성이 훼손되고 경기가 불안정해질 수 있음에 유의](https://www.kdi.re.kr/research/analysisView?art_no=3671)\n\n    *   ![Image 17](https://www.kdi.re.kr/data/download/resumes/img/picture/20200713.jpg)_프로필_ **김지연 전망총괄**프로필 보기\n    *   ![Image 18](https://www.kdi.re.kr/data/download/resumes/img/picture/20210817.jpg)_프로필_ **김준형 동향총괄**프로필 보기\n    *   ![Image 19](https://www.kdi.re.kr/data/download/resumes/img/picture/20110523.jpg)_프로필_ **정규철 경제전망실장**프로필 보기\n\n원문 미리보기 원문 다운로드 영상보고서 보기\n\n*   [![Image 20: 표지](https://img.youtube.com/vi/shl4BeYgWKo/mqdefault.jpg) **최근의 환율 변동이 물가에 미치는 영향** ■ 강달러 요인에 따른 원/달러 환율의 상승은 단기적으로 소비자물가에 상방 압력으로 작용하나, 지속성과 파급력은 국내 요인보다 제한적인 것으로 나타남. - 강달러 요인에 따른 원/달러 환율 상승은 시간이 지나며 수입품 가격에 미치는 영향이 점차 축소되는 반면, 국내 요인에 따른 원/달러 환율 상승은 그 영향이 점진적으로 확대되는 경향을 보임. - 미 달러화 요인과 국내 요인이 소비자물가에 미치는 단기적 영향은 유사하였으나, 시간이 지날수록 국내 요인에 따른 원/달러 환율 상승의 영향이 비교적 크게 확대 ■ 최근의 환율 변동이 소비자물가에 미친 영향을 분석한 결과, 달러화 요인의 영향이 비교적 큰 것으로 나타났으며, 시나리오 분석 결과 원/달러 환율이 급등하지 않는다면 물가상승률이 물가안정목표(2%)를 유의하게 상회하는 요인으로 작용하지 않을 것임을 시사 - 원/달러 환율이 1,500원까지 상승할 경우 소비자물가는 1/4분기 대비 최대 0.24%p까지 추가 상승하는 반면, 1,400원까지 하락할 경우에는 1/4분기 대비 최대 0.44%p 하락하는 것으로 나타남. - 1/4분기 소비자물가 상승률이 2.1%를 기록한 가운데 수요 압력이 여전히 낮다는 점을 감안하면, 원/달러 환율이 1,500원 부근까지 상승하는 경우에도 소비자물가 상승률이 물가안정목표(2%)를 크게 상회할 가능성이 높지 않음을 시사 ■ 환율이 물가에 미치는 영향이 환율 변동 요인에 따라 다르다는 본고의 분석 결과는 환율변동에 대한 정책 대응에 시사점을 제시해 줌. - 환율 변화 자체에 민감하게 반응하기보다는, 그 원인에 따른 물가상승률 변동폭과 지속성을 감안하여 대응해야 할 필요성을 시사 - 달러화 요인으로 환율이 상승하는 경우에는 그 영향이 단기에 그칠 수 있음을 감안하여 통화정책을 수행할 필요 - 반면, 환율 상승세가 장기간 지속되거나 국내 요인의 영향이 확대될 경우 물가 상승 압력이 지속될 수 있으므로, 향후 환율 추이와 변동 배경을 면밀히 모니터링하며 거시정책을 운영하는 것이 바람직](https://www.kdi.re.kr/research/analysisView?art_no=3670)\n\n    *   ![Image 21](https://www.kdi.re.kr/data/download/resumes/img/picture/20210817.jpg)_프로필_ **김준형 동향총괄**프로필 보기\n    *   ![Image 22](https://www.kdi.re.kr/data/download/resumes/img/picture/20230816.jpg)_프로필_ **마창석 부연구위원**프로필 보기\n\n원문 미리보기 원문 다운로드 영상보고서 보기\n\n*   [![Image 23: 표지](https://img.youtube.com/vi/Ibu6eFRBCSQ/mqdefault.jpg) **최근의 환율 변동이 물가에 미치는 영향** ■ 강달러 요인에 따른 원/달러 환율의 상승은 단기적으로 소비자물가에 상방 압력으로 작용하나, 지속성과 파급력은 국내 요인보다 제한적인 것으로 나타남. - 강달러 요인에 따른 원/달러 환율 상승은 시간이 지나며 수입품 가격에 미치는 영향이 점차 축소되는 반면, 국내 요인에 따른 원/달러 환율 상승은 그 영향이 점진적으로 확대되는 경향을 보임. - 미 달러화 요인과 국내 요인이 소비자물가에 미치는 단기적 영향은 유사하였으나, 시간이 지날수록 국내 요인에 따른 원/달러 환율 상승의 영향이 비교적 크게 확대 ■ 최근의 환율 변동이 소비자물가에 미친 영향을 분석한 결과, 달러화 요인의 영향이 비교적 큰 것으로 나타났으며, 시나리오 분석 결과 원/달러 환율이 급등하지 않는다면 물가상승률이 물가안정목표(2%)를 유의하게 상회하는 요인으로 작용하지 않을 것임을 시사 - 원/달러 환율이 1,500원까지 상승할 경우 소비자물가는 1/4분기 대비 최대 0.24%p까지 추가 상승하는 반면, 1,400원까지 하락할 경우에는 1/4분기 대비 최대 0.44%p 하락하는 것으로 나타남. - 1/4분기 소비자물가 상승률이 2.1%를 기록한 가운데 수요 압력이 여전히 낮다는 점을 감안하면, 원/달러 환율이 1,500원 부근까지 상승하는 경우에도 소비자물가 상승률이 물가안정목표(2%)를 크게 상회할 가능성이 높지 않음을 시사 ■ 환율이 물가에 미치는 영향이 환율 변동 요인에 따라 다르다는 본고의 분석 결과는 환율변동에 대한 정책 대응에 시사점을 제시해 줌. - 환율 변화 자체에 민감하게 반응하기보다는, 그 원인에 따른 물가상승률 변동폭과 지속성을 감안하여 대응해야 할 필요성을 시사 - 달러화 요인으로 환율이 상승하는 경우에는 그 영향이 단기에 그칠 수 있음을 감안하여 통화정책을 수행할 필요 - 반면, 환율 상승세가 장기간 지속되거나 국내 요인의 영향이 확대될 경우 물가 상승 압력이 지속될 수 있으므로, 향후 환율 추이와 변동 배경을 면밀히 모니터링하며 거시정책을 운영하는 것이 바람직](https://www.kdi.re.kr/research/analysisView?art_no=3670)\n\n    *   ![Image 24](https://www.kdi.re.kr/data/download/resumes/img/picture/20210817.jpg)_프로필_ **김준형 동향총괄**프로필 보기\n    *   ![Image 25](https://www.kdi.re.kr/data/download/resumes/img/picture/20230816.jpg)_프로필_ **마창석 부연구위원**프로필 보기\n\n원문 미리보기 원문 다운로드 영상보고서 보기\n\n*   [![Image 26: 표지](https://img.youtube.com/vi/kTWh9d79e7k/mqdefault.jpg) **인구 요인이 소비성향에 미치는 영향과 시사점** ■ 기대수명의 가파른 상승으로 지난 20년간 평균소비성향이 하락해 왔으며, 이는 민간소비 증가세가 경제성장률을 추세적으로 하회하는 주요인으로 작용 - 기대수명 증가에도 불구하고 생애주직장 퇴직연령에는 큰 변화가 없는 가운데, 퇴직 후 상대적으로 소득이 낮고 불안정한 일자리에 종사하게 될 가능성에 대비하여 저축 성향이 상승(소비성향이 하락)한 것으로 풀이됨. - 특히 기대수명 증가에 대한 반응이 잔여수명이 짧은 고령층에서 더 크게 나타나면서, 이들 연령층의 소비성향 하락이 뚜렷하게 관측됨. ■ 반면, 향후에는 기대수명 증가세가 둔화되고 초고령층(75세 이상) 인구 비중이 빠르게 증가함에 따라 평균소비성향이 점차 반등할 것으로 예상됨. - 지난 20년간 기대수명은 약 6.5세 증가한 반면, 향후 20년간의 기대수명 증가는 절반 수준인 약 3.5세에 그칠 것으로 전망 - 저출생 기조가 지속되며 고령층 인구의 비중이 빠르게 증가하면 생산가능인구가 축소되며 성장률이 더욱 하락하는 가운데 소비성향은 점차 증가할 것으로 예상 - 따라서 민간소비 증가세가 경제성장률을 하회하는 현상도 점차 완화될 전망 ■ 지난 20년간의 평균소비성향 하락에는 우리나라 노동시장의 구조적인 문제가 투영되어 있는 만큼, 이를 완화하기 위한 대응 방안을 모색할 필요 - 기대수명 증가에 대응하여 은퇴 시점이 적절히 조정될 수 있도록 고령층의 노동시장 참여를 제약하는 구조적 요인들을 해소할 필요 - 따라서 연공서열형의 경직적인 임금구조를 개선하고 직무 및 성과 중심의 임금체계를 강화하는 한편 정년퇴직 후 재고용 제도를 활성화하는 등 노동시장의 마찰적 요인을 해소하여 고령층 노동 수요를 확대할 필요 - 특히 고령 인력의 적절한 활용이 확대될 경우 저출생·고령화에 따른 잠재성장률 하락 압력을 부분적으로 상쇄할 수 있을 것으로 판단됨.](https://www.kdi.re.kr/research/analysisView?art_no=3669)\n\n    *   ![Image 27](https://www.kdi.re.kr/data/download/resumes/img/picture/20180702.jpg)_프로필_ **김미루 국채연구팀장**프로필 보기\n    *   ![Image 28](https://www.kdi.re.kr/data/download/resumes/img/picture/20220701.jpg)_프로필_ **이승희 부연구위원**프로필 보기\n\n원문 미리보기 원문 다운로드 영상보고서 보기\n\n*   [![Image 29: 표지](https://img.youtube.com/vi/MFbydUvGRtI/mqdefault.jpg) **인구 요인이 소비성향에 미치는 영향과 시사점** ■ 기대수명의 가파른 상승으로 지난 20년간 평균소비성향이 하락해 왔으며, 이는 민간소비 증가세가 경제성장률을 추세적으로 하회하는 주요인으로 작용 - 기대수명 증가에도 불구하고 생애주직장 퇴직연령에는 큰 변화가 없는 가운데, 퇴직 후 상대적으로 소득이 낮고 불안정한 일자리에 종사하게 될 가능성에 대비하여 저축 성향이 상승(소비성향이 하락)한 것으로 풀이됨. - 특히 기대수명 증가에 대한 반응이 잔여수명이 짧은 고령층에서 더 크게 나타나면서, 이들 연령층의 소비성향 하락이 뚜렷하게 관측됨. ■ 반면, 향후에는 기대수명 증가세가 둔화되고 초고령층(75세 이상) 인구 비중이 빠르게 증가함에 따라 평균소비성향이 점차 반등할 것으로 예상됨. - 지난 20년간 기대수명은 약 6.5세 증가한 반면, 향후 20년간의 기대수명 증가는 절반 수준인 약 3.5세에 그칠 것으로 전망 - 저출생 기조가 지속되며 고령층 인구의 비중이 빠르게 증가하면 생산가능인구가 축소되며 성장률이 더욱 하락하는 가운데 소비성향은 점차 증가할 것으로 예상 - 따라서 민간소비 증가세가 경제성장률을 하회하는 현상도 점차 완화될 전망 ■ 지난 20년간의 평균소비성향 하락에는 우리나라 노동시장의 구조적인 문제가 투영되어 있는 만큼, 이를 완화하기 위한 대응 방안을 모색할 필요 - 기대수명 증가에 대응하여 은퇴 시점이 적절히 조정될 수 있도록 고령층의 노동시장 참여를 제약하는 구조적 요인들을 해소할 필요 - 따라서 연공서열형의 경직적인 임금구조를 개선하고 직무 및 성과 중심의 임금체계를 강화하는 한편 정년퇴직 후 재고용 제도를 활성화하는 등 노동시장의 마찰적 요인을 해소하여 고령층 노동 수요를 확대할 필요 - 특히 고령 인력의 적절한 활용이 확대될 경우 저출생·고령화에 따른 잠재성장률 하락 압력을 부분적으로 상쇄할 수 있을 것으로 판단됨.](https://www.kdi.re.kr/research/analysisView?art_no=3669)\n\n    *   ![Image 30](https://www.kdi.re.kr/data/download/resumes/img/picture/20180702.jpg)_프로필_ **김미루 국채연구팀장**프로필 보기\n    *   ![Image 31](https://www.kdi.re.kr/data/download/resumes/img/picture/20220701.jpg)_프로필_ **이승희 부연구위원**프로필 보기\n\n원문 미리보기 원문 다운로드 영상보고서 보기\n\n![Image 32: 공공누리](https://www.kdi.re.kr/res/img/img_nuri_1.jpg)\n한국개발연구원의 본 저작물은 _“공공누리 제1유형 : 출처표시”_ 조건에 따라 이용할 수 있습니다. 저작권정책 참조\n\n**보안문자 확인**\n\n무단등록 및 수집 방지를 위해 아래 보안문자를 입력해 주세요.\n\n![Image 33: 보안문자](https://www.kdi.re.kr/captcha/captchaImg)문자 변경 확인\n\n팝업 닫기\n\n**KDI 직원 정보 확인**\n\n담당자 정보를 확인해 주세요.\n\n[확인](javascript:kdifn.miniPopupClose(\'.employee_email\');)\n\n팝업 닫기\n\n**KDI 직원 정보 확인**\n\n담당자 정보를 확인해 주세요. **044-550-5454**\n\n[확인](javascript:kdifn.miniPopupClose(\'.employee_phone\');)\n\n팝업 닫기\n\n**등록완료**\n\n소중한 의견 감사드립니다.\n\n[확인](javascript:kdifn.miniPopupClose(\'.employee_succ\');)\n\n팝업 닫기\n\n**등록실패**\n\n잠시 후 다시 시도해주세요.\n\n[확인](javascript:kdifn.miniPopupClose(\'.employee_fail\');)\n\n팝업 닫기\n\n**Join our Newsletter**\n매일 새로운 소식으로 준비된 KDI 뉴스레터와 함께\n\n다양한 정보를 확인하세요.\n\n뉴스레터 신청 \n\n*   [경제정책정보](https://eiec.kdi.re.kr/policy/materialList.do)\n*   [경제정책시계열서비스](http://epts.kdi.re.kr/)\n*   [KDI JEP](http://kdijep.org/)\n*   [공공투자관리센터](https://pimac.kdi.re.kr/)\n\n*   [도서관](http://lib.kdi.re.kr/)\n*   [알리오](http://www.alio.go.kr/)\n*   [도서회원](https://www.kdi.re.kr/bookMember/booksLogin)\n*   [고객헌장](https://www.kdi.re.kr/servicePolicy/charter)\n\n*   [개인정보처리방침](https://www.kdi.re.kr/servicePolicy/privacy)\n*   [영상정보처리기기 운영ㆍ관리방침](https://www.kdi.re.kr/servicePolicy/mediaPrivacy)\n*   [저작권정책](https://www.kdi.re.kr/servicePolicy/copyright)\n*   [이메일주소 무단수집거부](https://www.kdi.re.kr/servicePolicy/email)\n\n*   [뉴스레터](https://www.kdi.re.kr/share/newsletter)\n*   [부조리신고센터](https://www.kdi.re.kr/share/absurdityCenter)\n*   [Q&A](https://www.kdi.re.kr/share/qnaList)\n*   [찾아오시는길](https://www.kdi.re.kr/infomation/location)\n\n세종특별자치시 남세종로 263 Tel: [044-550-4114](tel:044-550-4114)Mail: [media@kdi.re.kr](mailto:media@kdi.re.kr)COPYRIGHT © KOREA DEVELOPMENT INSTITUTE ALL RIGHTS RESERVED \n\n[YOU TUBE](http://www.youtube.com/KDIofficial)[INSTAGRAM](https://www.instagram.com/kdi.official_/)[네이버블로그](https://blog.naver.com/kdisearch)[LINKEDIN](https://www.linkedin.com/company/korea-development-institute-kdi-/)\n\nFAMILY SITE\n*   [경제교육·정보센터](http://eiec.kdi.re.kr/)\n*   [공공투자관리센터](http://pimac.kdi.re.kr/)\n*   [국제개발협력센터](https://www.kdi.re.kr/introduce/interCenter)\n*   [국제정책대학원](http://www.kdischool.ac.kr/)\n\nTOP\n\n#### 요약 영상보고서\n\n_기타(경제전망)_\n대선까지 치뤘겠다...2025년 한국경제는 어떻게 되는걸까?\n\n[#경제동향 및 전망](https://www.kdi.re.kr/research/topicList?cd=A&sub=A00)\n\n2025.06.04\n\n[KID YOUTUBE 바로가기](http://www.youtube.com/KDIofficial)\n\n![Image 34: 유튜브 영상](https://www.kdi.re.kr/res/img/img_utb-guide.gif)\n\n팝업 닫기\n\n#### 관련 영상자료\n\n_숏츠_\n2025년 상반기 KDI 경제전망 (shorts)\n\n2025.05.20\n\n[KID YOUTUBE 바로가기](http://www.youtube.com/KDIofficial)\n\n![Image 35: 유튜브 영상](https://www.kdi.re.kr/res/img/img_utb-guide.gif)\n\n팝업 닫기\n\n#### 요약 영상보고서\n\n_기사/논문_\n올해도 1%대 성장 예상된다는데....이제부터 일본식 장기 불황?\n\n2025.05.08\n\n**[보고서 바로가기](https://www.kdi.re.kr/research/analysisView?art_no=3671)**[KID YOUTUBE 바로가기](http://www.youtube.com/KDIofficial)\n\n![Image 36: 유튜브 영상](https://www.kdi.re.kr/res/img/img_utb-guide.gif)\n\n|  관련정보  | 열기\n\n 코로나19는 어느새 또 한참 지난 얘기가 되었죠.\n\n 그런데 한국경제는 여전히 코로나19 위기 이전으로 회복하지 못하고 있습니다.\n\n 올해도 성장률이 1% 수준에 그칠 거라는 걱정이 많은데요,\n\n 이젠 정말 일본식 장기불황에 빠지게 되는 것 아닐까요?\n\n KDI가 한국의 잠재성장률을 전망해봤습니다. \n\n|  스크립트  | 열기\n\n 마스크를 벗은 지도 벌써 3년째지만,\n\n 한국경제는 여전히 코로나19 위기 이전으로 회복하지 못하고 있습니다.\n\n 올해도 성장률이 1% 수준에 그칠 거라는 걱정이 많죠.\n\n 우리나라의 잠재성장률, 그러니까 성장할 수 있는 능력치 자체가 계속 떨어져서\n\n 본격적으로 저성장 시대에 들어선 건 아닐까요?\n\n KDI가 한국의 잠재성장률을 전망해봤습니다.\n\n 우선 한 나라의 경제성장은 노동과 자본 같은 생산요소를 얼마나 투입하는지,\n\n 그리고 이 두 가지를 얼마나 효율적으로 활용하는지를 나타내는\n\n 총요소생산성으로 결정됩니다.\n\n 기술 개발이나 조직 혁신 같은 노력으로 생산성을 더 높일 수 있죠.\n\n 지난 20년의 경제성장을 분석해보니\n\n 2000년대에 비해 2010년대 경제성장률이 1.6%p 하락했는데,\n\n 이 중 약 67%는 생산성 증가세가 둔화되었기 때문입니다.\n\n 그리고 최근 10년 동안 경제성장률이 더 떨어진 건\n\n 생산성뿐만 아니라 노동 투입, 즉 일할 사람이 예전만큼 늘어나지 못했기 때문이었습니다.\n\n 실제로 생산연령인구는 2019년에 정점을 찍은 뒤 매년 수십만 명씩 줄고 있습니다.\n\n 앞으로 점점 줄어 2050년에는\n\n 생산연령인구 비중이 전체인구의 절반밖에 안 될 거라고 합니다.\n\n 반면, 65세 이상 고령인구의 비중은 올해 20%를 넘어서고,\n\n 2050년에는 40%까지 오를 전망이고요.\n\n (인터뷰 – 김지연 박사님)\n\n 문제는 이러한 인구구조의 변화가 노동투입뿐만 아니라\n\n 생산성에까지 악영향을 줄 수 있다는 점입니다.\n\n 청년층은 고령층에 비해 새로운 기술에 대한 적응력이 높습니다.\n\n 또한 청년층의 참신함과 위험을 감수하려는 성향은 혁신의 원동력이기도 한데요.\n\n 따라서 청년들의 비중이 줄어들면 우리나라 전체 생산성에 부정적인 영향을 줄 수 있습니다.\n\n 앞으로 우리 경제 전반의 생산성이 얼마나 좋아질 수 있을지를\n\n 세 가지 경우로 나눠서 잠재성장률을 전망해봤습니다.\n\n 기준이 되는 시나리오로 생산성이 매년 지난 10년 평균치인 0.6%씩 오르는 경우,\n\n 낙관 시나리오로 AI 기술이 더 발전하고 경제 구조개혁도 진행이 되어 생산성이 매년 0.9%씩 오르는 경우,\n\n 마지막으로 비관 시나리오는\n\n 무역갈등으로 기술 확산이 제한되고, 경제 구조개혁 마저 어려워 생산성 증가율이 0.3%로 축소되는 경우로 설정했습니다.\n\n 기준 시나리오로 전망해 봤을 때\n\n 올해 잠재성장률은 1% 후반대로 추정되고,\n\n 앞으로 쭉쭉 떨어져서 2040년대에는 0% 성장에 이르게 될 것으로 나타났습니다.\n\n 40년대 후반에는 역성장도 예상되는데요,\n\n 이렇게까지 성장률이 하락하는 데에는 생산가능인구가 줄면서 2030년부터는 노동투입이 성장률을 떨어트리는 요소로 작용하기 때문입니다.\n\n 낙관과 비관 시나리오에서도 모두 잠재성장률이 떨어지는 모습인데요,\n\n 비관적인 상황에선 역성장 시기가 40년대 초반으로 앞당겨집니다.\n\n 생산성이 예상보다 빠르게 좋아지는 낙관 시나리오에서는\n\n 2050년까지도 성장할 수 있을 것으로 예상됩니다.\n\n 특히, 처음엔 비슷하게 출발해도 생산성에 따라 차이가 점점 벌어지면서\n\n 2024년 대비 2050년의 1인당 GDP 증가폭이 낙관 시나리오에서 비관적인 경우보다 2.3배 정도 높을 것으로 나타났습니다.\n\n 생산성을 얼마나 개선하느냐에 따라 성장률이 크게 달라질 수 있다는 의미입니다.\n\n 그렇다면 앞으로 어떻게 해야 생산성을 더 높일 수 있을까요?\n\n (인터뷰 – 김준형 박사님)\n\n 우선 혁신 기업이 새로운 시장을 개척할 수 있도록 지원하고 성장을 가로막는 규제들은 정리해서 경쟁을 촉진해야 합니다.\n\n 고령화로 인해 일할 사람이 부족해지는 상황도 미리 대비해야 하는데요. 여성과 고령층의 경제활동을 촉진하고 외국인 노동자를 적절하게 수용하는 등 인적자원을 더 효율적으로 쓸 수 있는 여건을 마련해야겠습니다. 근무연차를 우선시하는 연공서열형 임금체계, 노동시간 규제 같은 경직적인 제도들을 유연하게 바꿔야 합니다.\n\n 저성장 시대에는 경제 구조 개혁뿐만 아니라 재정정책도 세심하게 활용해야겠죠.\n\n (인터뷰 – 정규철 박사님)\n\n 앞으로 성장률이 떨어지면서 정부재정 여건도 나빠지게 될 것입니다. 잠재성장률이 하락하면서 성장률이 낮아지는 것을 단기적인 경기 부진으로 보고 정부 재정을 풀어서 대응한다면, 재정건전성이 악화되고 경기는 더 불안정해질 수 있습니다. 특히 코로나 위기가 지나갔는데도 관리재정수지가 여전히 GDP 대비 4% 내외의 높은 수준이 계속되고 있다는 점을 경계하고, 재정지출을 늘리는 데 신중해야 할 것입니다.\n\n 대한민국의 미래를 지키기 위해 생산성 개선에 힘써야 할 때입니다. \n\n팝업 닫기\n\n#### 요약 영상보고서\n\n_기사/논문_\n한미 환율협의에 요동치는 환율, 물가는 어떻게 될까?\n\n2025.04.29\n\n**[보고서 바로가기](https://www.kdi.re.kr/research/analysisView?art_no=3670)**[KID YOUTUBE 바로가기](http://www.youtube.com/KDIofficial)\n\n![Image 37: 유튜브 영상](https://www.kdi.re.kr/res/img/img_utb-guide.gif)\n\n|  관련정보  | 열기\n\n 작년 말부터 쭉- 오르고 있는 환율.\n\n 환율이 오르면 수입품의 가격도 올라 물가도 상승할 수 있는데요.\n\n 그 영향은 환율이 오르는 요인에 따라 달라진다고 합니다.\n\n 코로나19 이후 상승한 환율에는 주로 어떤 요인이 영향을 미쳤을까요?\n\n KDI가 분석해 봤습니다. \n\n|  스크립트  | 열기\n\n 작년 말부터 고공행진을 이어가는 환율.\n\n ChatGPT 구독료처럼 해외 결제가 필요한 서비스나 해외 직구 제품 가격이 오른 걸 체감하신 분들도 계실 텐데요.\n\n 환율이 오르면 우리가 수입하는 원자재나 물건의 가격이 같이 오르기 때문에, 물가에도 영향을 줄 수 있습니다. 그래서 급등한 환율이 물가에 어떤 영향을 미쳤는지 분석해 봤습니다.\n\n 우선, 최근 원/달러 환율이 오르는 요인은 두 가지로 나눌 수 있습니다.\n\n 첫째, 미국 통화정책 기조 변화와 무역분쟁 심화로 다른 나라의 통화에 비해 달러화의 가치가 오르는 경우. (미 달러화 요인)\n\n 둘째, 정치나 경제 불안 등의 국내 요인으로 원화의 가치가 떨어지는 경우입니다. (국내 요인)\n\n 최근 원/달러 환율은 주로 어떤 요인의 영향을 받았을까요?\n\n 바로, 미 달러화 요인이었습니다.\n\n 주요국의 통화 대비 미국 달러의 가치를 나타내는 달러지수와 원/달러 환율의 상관성이 높아지고 있는데요. 즉, 최근 원/달러 환율이 원화보다는 달러화 자체의 움직임에 더 크게 영향을 받고 있다는 뜻입니다.\n\n 원/달러 환율이 어떤 요인으로 상승했는지에 따라, 수입품 가격에 미치는 영향도 달라질 수 있는데요.\n\n 미 달러화 요인으로 환율이 오를 경우, 수입 가격은 즉각적으로 상승했지만, 시간이 지나면서 그 영향은 점점 줄어듭니다.\n\n 반면에 국내 요인으로 환율이 오르면, 미국뿐만 아니라 모든 교역국 대비 원화 가치를 전반적으로 변화시키는데요. 이 때문에 수입품 가격에 주는 영향이 광범위하게 파급되어 시간이 지날수록 확대되는 모습입니다.\n\n 이를 바탕으로 환율 변동에 따라 소비자물가가 어떻게 반응하는지 볼까요?\n\n 원/달러 환율이 1%p 상승할 경우, 같은 분기 소비자물가는 0.04%p 올랐는데요.\n\n 1년간 누적된 영향을 보면, 미 달러화 요인보다는 국내 요인으로 인한 환율 상승이 더 큰 지속성과 파급력을 보였습니다.\n\n 실제로 올해 1분기 원/달러 환율 상승이 소비자물가를 0.47%p 상승시킨 것으로 나타났는데요. 이는 국내 요인의 영향은 큰 변동 없이 유지된 가운데, 최근 미 달러화 요인이 크게 확대되었기 때문입니다.\n\n 그렇다면, 앞으로 환율 변화에 따른 소비자물가는 어떻게 될까요?\n\n 환율에 변동이 없다면, 환율 때문에 물가가 더 오를 가능성은 크지 않을 것으로 보이는데요.\n\n 만약 환율이 각 요인에 의해서 1,500원 수준까지 오를 경우, 미 달러화 요인은 물가상승률을 0.19%p 높인 뒤 그 영향이 감소하고, 국내 요인은 더 큰 폭으로 오랜 기간 영향을 미쳐 물가상승률을 최대 0.24%p까지 높인 후 점진적으로 조정될 것으로 보입니다.\n\n (저자 인터뷰)\n\n 올해 1분기 소비자물가 상승률은 2.1%를 기록했습니다. 내수가 부진하다는 점을 고려하면, 원/달러 환율이 1,500원까지 오르더라도 소비자물가 상승률은 최대 0.2%p 정도 추가 상승하는 데 그쳐, 물가안정목표 2%를 크게 넘지 않을 것임을 시사합니다.\n\n 반면에 환율이 각 요인에 의해서 1,400원 수준으로 떨어진다면, 미 달러화 요인은 물가상승률을 0.29%p 감소시킨 후 점차 둔화됩니다. 국내 요인은 물가상승률을 더 빠르게 감소시켜 0.44%p까지 낮아지고, 2026년에는 환율 변화가 물가상승률에 하방 압력이 될 것으로 보입니다.\n\n 이렇듯 환율이 물가에 미치는 영향은 그 원인에 따라 달라지는데요. 환율 변동에 대해서 어떤 정책 대응이 필요할까요?\n\n (저자 인터뷰)\n\n 미 달러화 요인으로 환율이 상승하는 경우, 그 영향이 단기에 그칠 수 있음을 감안하여 통화정책을 수행할 필요가 있습니다. 하지만, 국내 요인의 영향이 확대될 경우 물가 상승 압력은 더 지속적으로 파급될 수 있기 때문에, 향후 환율 추이와 변동 배경을 면밀히 모니터링하면서 거시 정책을 운영하는 것이 바람직하겠습니다.\n\n 따라서 환율 변동에 대한 기계적으로 대응하기보다는, 그 원인에 따른 물가상승률 변동폭과 지속성을 고려한 정책 대응이 필요합니다. \n\n팝업 닫기\n\n#### 요약 영상보고서\n\n_기사/논문_\n급변하는 환율, 물가에는 어떤 영향이?\n\n2025.05.26\n\n**[보고서 바로가기](https://www.kdi.re.kr/research/analysisView?art_no=3670)**[KID YOUTUBE 바로가기](http://www.youtube.com/KDIofficial)\n\n![Image 38: 유튜브 영상](https://www.kdi.re.kr/res/img/img_utb-guide.gif)\n\n팝업 닫기\n\n#### 요약 영상보고서\n\n_기사/논문_\n20년 전보다 돈은 많이 벌어도... 쓰는 걸 꺼려하는 한국 사람들\n\n2025.04.23\n\n**[보고서 바로가기](https://www.kdi.re.kr/research/analysisView?art_no=3669)**[KID YOUTUBE 바로가기](http://www.youtube.com/KDIofficial)\n\n![Image 39: 유튜브 영상](https://www.kdi.re.kr/res/img/img_utb-guide.gif)\n\n팝업 닫기\n\n#### 요약 영상보고서\n\n_기사/논문_\n기대수명은 늘었는데 은퇴시점은 20년간 변함 없어...이러니 아낄 수 밖에\n\n2025.05.22\n\n**[보고서 바로가기](https://www.kdi.re.kr/research/analysisView?art_no=3669)**[KID YOUTUBE 바로가기](http://www.youtube.com/KDIofficial)\n\n![Image 40: 유튜브 영상](https://www.kdi.re.kr/res/img/img_utb-guide.gif)\n\n팝업 닫기\n\n#### 연구진 소개\n\n팝업 닫기\n'}],
 'response_time': 1.19}

In [7]:
from langchain.adapters.openai import convert_openai_messages
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(model="gpt-4o")

# Step 1. 질문에 대한 자료를 TavilyClient로 가져오기
query = "현대자동차 미국 시장 2025년 전망"

content = client.search(
    query, 
    include_raw_content=True,
    search_depth="advanced"
)["results"]

content

[{'url': 'https://novelone.tistory.com/entry/2025%EB%85%84-%ED%98%84%EB%8C%80%EC%B0%A8-%EC%A3%BC%EA%B0%80-%EC%A0%84%EB%A7%9D-%EB%AF%B8%EA%B5%AD-%ED%8C%90%EB%A7%A4-%EC%97%AD%EB%8C%80-%EC%B5%9C%EB%8C%80',
  'title': '2025년 현대차 주가 전망: 미국 판매 역대 최대! - novelone 님의 블로그',
  'content': 'Published Time: 2025-02-02T12:53:50+09:00\n\n2025년 현대차 주가 전망: 미국 판매 역대 최대!\n\n===============\n\n본문 바로가기\n\nnovelone 님의 블로그\n================================================\n\n블로그 내 검색 검색\n\nImage 1: 블로그 이미지\n   관리\n   글쓰기\n   로그인\n   로그아웃\n\n메뉴\n\n   홈\n\n경제/주식\n2025년 현대차 주가 전망: 미국 판매 역대 최대!\n=============================\n\nby novelone 2025. 2. 2.\n\n2025년 1월, 현대자동차가 미국 시장에서 1월 기준 역대 최대 판매량을 기록하며 글로벌 시장에서 긍정적인 성과를 보이고 있습니다. 특히, 친환경차 판매 증가와 SUV 라인업 강세가 주목받고 있으며, 이에 따라 증권가에서도 현대차의 주가에 대해 긍정적인 전망을 내놓고 있습니다. [...] 아이오닉 시리즈 및 하이브리드 모델을 통해 전기차 및 친환경차 시장에서 점유율 확대\n\n📢 미국 시장의 전기차·하이브리드 수요 증가에 따라 현대차의 판매 성장세는 지속될 가능성이 높습니다.\n\nImage 3\n\n  \n\n📈 현대차 주가 전망 (2025년)\n--------------------\n\n미국 시장에서의 성과와 함께 현대차 주가 전망도 긍정적

[{'url': 'https://novelone.tistory.com/entry/2025%EB%85%84-%ED%98%84%EB%8C%80%EC%B0%A8-%EC%A3%BC%EA%B0%80-%EC%A0%84%EB%A7%9D-%EB%AF%B8%EA%B5%AD-%ED%8C%90%EB%A7%A4-%EC%97%AD%EB%8C%80-%EC%B5%9C%EB%8C%80',
  'title': '2025년 현대차 주가 전망: 미국 판매 역대 최대! - novelone 님의 블로그',
  'content': 'Published Time: 2025-02-02T12:53:50+09:00\n\n2025년 현대차 주가 전망: 미국 판매 역대 최대!\n\n===============\n\n본문 바로가기\n\nnovelone 님의 블로그\n================================================\n\n블로그 내 검색 검색\n\nImage 1: 블로그 이미지\n   관리\n   글쓰기\n   로그인\n   로그아웃\n\n메뉴\n\n   홈\n\n경제/주식\n2025년 현대차 주가 전망: 미국 판매 역대 최대!\n=============================\n\nby novelone 2025. 2. 2.\n\n2025년 1월, 현대자동차가 미국 시장에서 1월 기준 역대 최대 판매량을 기록하며 글로벌 시장에서 긍정적인 성과를 보이고 있습니다. 특히, 친환경차 판매 증가와 SUV 라인업 강세가 주목받고 있으며, 이에 따라 증권가에서도 현대차의 주가에 대해 긍정적인 전망을 내놓고 있습니다. [...] 아이오닉 시리즈 및 하이브리드 모델을 통해 전기차 및 친환경차 시장에서 점유율 확대\n\n📢 미국 시장의 전기차·하이브리드 수요 증가에 따라 현대차의 판매 성장세는 지속될 가능성이 높습니다.\n\nImage 3\n\n  \n\n📈 현대차 주가 전망 (2025년)\n--------------------\n\n미국 시장에서의 성과와 함께 현대차 주가 전망도 긍정적입니다. 국내 증권사들은 현대차의 글로벌 판매 호조와 지배구조 개편 등의 요인을 반영하여 목표 주가를 상향 조정하고 있습니다.\n\n### 📊 증권사 목표 주가 변화\n\n증권사기존 목표 주가수정된 목표 주가전망\n\nDB금융투자300,000원330,000원인도 법인 IPO 기대감 반영\n삼성증권360,000원340,000원글로벌 자동차 시장 둔화 우려 반영\n\n🔍 DB금융투자는 현대차를 자동차 업종 최우선주로 선정하며, 인도 법인의 기업공개(IPO) 및 지배구조 개편 등의 호재가 아직 주가에 충분히 반영되지 않았다고 분석했습니다. [...] 이번 포스팅에서는 현대차의 최신 실적, 증권가의 주가 전망, 그리고 투자 시 고려해야 할 요소에 대해 정리해보겠습니다.\n\nImage 2\n\n  \n\n🚗 1월 미국 시장 역대 최대 판매량 기록\n------------------------\n\n현대차는 2025년 1월, 미국에서 총 54,503대를 판매하며 1월 기준 역대 최대 판매량을 기록했습니다. 이는 전년 동월 대비 15% 증가한 수치로, 글로벌 자동차 시장의 둔화에도 불구하고 강력한 성장세를 유지하고 있음을 보여줍니다.\n\n### 📌 판매량 증가 요인\n\n✔ 친환경차 판매 호조\n\n   하이브리드 차량 판매량 74% 증가\n   전기차(EV) 판매량 15% 증가\n   싼타페 하이브리드(160%↑), 투싼 하이브리드(89%↑), 아이오닉5(54%↑), 아이오닉6(15%↑) 등의 친환경 모델이 판매 성장 주도\n\n✔ SUV 라인업 강세\n\n   신형 싼타페, 투싼, 팰리세이드 등의 SUV 모델이 꾸준한 인기\n\n✔ 미국 전기차 시장 확대 대응',
  'score': 0.9145431,
  'raw_content': "Published Time: 2025-02-02T12:53:50+09:00\n\n2025년 현대차 주가 전망: 미국 판매 역대 최대!\n\n===============\n\n[본문 바로가기](https://novelone.tistory.com/entry/2025%EB%85%84-%ED%98%84%EB%8C%80%EC%B0%A8-%EC%A3%BC%EA%B0%80-%EC%A0%84%EB%A7%9D-%EB%AF%B8%EA%B5%AD-%ED%8C%90%EB%A7%A4-%EC%97%AD%EB%8C%80-%EC%B5%9C%EB%8C%80#content)\n\n[novelone 님의 블로그](https://novelone.tistory.com/)\n================================================\n\n블로그 내 검색 검색\n\n![Image 1: 블로그 이미지](https://t1.daumcdn.net/tistory_admin/static/manage/images/r3/default_L.png)\n*   [관리](https://novelone.tistory.com/manage)\n*   [글쓰기](https://novelone.tistory.com/manage/entry/post)\n*   [로그인](https://novelone.tistory.com/entry/2025%EB%85%84-%ED%98%84%EB%8C%80%EC%B0%A8-%EC%A3%BC%EA%B0%80-%EC%A0%84%EB%A7%9D-%EB%AF%B8%EA%B5%AD-%ED%8C%90%EB%A7%A4-%EC%97%AD%EB%8C%80-%EC%B5%9C%EB%8C%80#)\n*   [로그아웃](https://novelone.tistory.com/entry/2025%EB%85%84-%ED%98%84%EB%8C%80%EC%B0%A8-%EC%A3%BC%EA%B0%80-%EC%A0%84%EB%A7%9D-%EB%AF%B8%EA%B5%AD-%ED%8C%90%EB%A7%A4-%EC%97%AD%EB%8C%80-%EC%B5%9C%EB%8C%80#)\n\n메뉴\n\n*   [홈](https://novelone.tistory.com/)\n\n경제/주식\n2025년 현대차 주가 전망: 미국 판매 역대 최대!\n=============================\n\nby novelone 2025. 2. 2.\n\n2025년 1월, 현대자동차가 미국 시장에서 **1월 기준 역대 최대 판매량을 기록**하며 글로벌 시장에서 긍정적인 성과를 보이고 있습니다. 특히, 친환경차 판매 증가와 SUV 라인업 강세가 주목받고 있으며, 이에 따라 증권가에서도 현대차의 주가에 대해 긍정적인 전망을 내놓고 있습니다.\n\n이번 포스팅에서는 **현대차의 최신 실적, 증권가의 주가 전망, 그리고 투자 시 고려해야 할 요소**에 대해 정리해보겠습니다.\n\n![Image 2](https://blog.kakaocdn.net/dna/btJtMx/btsL4Q4qhat/AAAAAAAAAAAAAAAAAAAAAAd7I3M_0rHAGU0r9U7oxm11-Ga3ko2YHQD_p-R8bmKf/img.webp?credential=yqXZFxpELC7KVnFOS48ylbz2pIh7yKj8&expires=1753973999&allow_ip=&allow_referer=&signature=UcUsf9xAryHsxkmvvQOcqcqRd2c%3D)\n\n* * *\n\n🚗 1월 미국 시장 역대 최대 판매량 기록\n------------------------\n\n**현대차는 2025년 1월, 미국에서 총 54,503대를 판매하며 1월 기준 역대 최대 판매량을 기록**했습니다. 이는 전년 동월 대비 **15% 증가**한 수치로, 글로벌 자동차 시장의 둔화에도 불구하고 강력한 성장세를 유지하고 있음을 보여줍니다.\n\n### 📌 **판매량 증가 요인**\n\n✔ **친환경차 판매 호조**\n\n*   하이브리드 차량 판매량 **74% 증가**\n*   전기차(EV) 판매량 **15% 증가**\n*   **싼타페 하이브리드(160%↑), 투싼 하이브리드(89%↑), 아이오닉5(54%↑), 아이오닉6(15%↑)** 등의 친환경 모델이 판매 성장 주도\n\n✔ **SUV 라인업 강세**\n\n*   신형 **싼타페**, **투싼**, **팰리세이드** 등의 SUV 모델이 꾸준한 인기\n\n✔ **미국 전기차 시장 확대 대응**\n\n*   **아이오닉 시리즈 및 하이브리드 모델**을 통해 전기차 및 친환경차 시장에서 점유율 확대\n\n📢 **미국 시장의 전기차·하이브리드 수요 증가에 따라 현대차의 판매 성장세는 지속될 가능성이 높습니다.**\n\n![Image 3](https://blog.kakaocdn.net/dna/eg601s/btsL4MOAAoI/AAAAAAAAAAAAAAAAAAAAADKRv9yrHA9s7vpFts9FwQJn6ssl3yL0Wgh9CEUaroa7/img.webp?credential=yqXZFxpELC7KVnFOS48ylbz2pIh7yKj8&expires=1753973999&allow_ip=&allow_referer=&signature=O3PA7%2FzEQyxexAV3oDsm51xSd18%3D)\n\n* * *\n\n📈 현대차 주가 전망 (2025년)\n--------------------\n\n미국 시장에서의 성과와 함께 **현대차 주가 전망도 긍정적**입니다. 국내 증권사들은 현대차의 글로벌 판매 호조와 지배구조 개편 등의 요인을 반영하여 목표 주가를 상향 조정하고 있습니다.\n\n### 📊 **증권사 목표 주가 변화**\n\n증권사기존 목표 주가수정된 목표 주가전망\n\n**DB금융투자**300,000원**330,000원**인도 법인 IPO 기대감 반영\n**삼성증권**360,000원**340,000원**글로벌 자동차 시장 둔화 우려 반영\n\n🔍 **DB금융투자**는 현대차를 자동차 업종 최우선주로 선정하며, 인도 법인의 기업공개(IPO) 및 지배구조 개편 등의 호재가 아직 주가에 충분히 반영되지 않았다고 분석했습니다.\n\n🔍 **삼성증권**은 글로벌 자동차 시장 둔화 우려를 반영하여 목표 주가를 소폭 하향 조정했습니다.\n\n📢 **현대차의 글로벌 판매 증가, 지배구조 개편 이슈 등이 주가 상승을 견인할 가능성이 높지만, 경기 둔화와 금리 변동성 등의 변수도 고려해야 합니다.**\n\n![Image 4](https://blog.kakaocdn.net/dna/bw6oYL/btsL4ekvRTV/AAAAAAAAAAAAAAAAAAAAAJng0HTdqNBimAlIgiXuda_xiXlUxAt8c5-2xDPhTiMr/img.webp?credential=yqXZFxpELC7KVnFOS48ylbz2pIh7yKj8&expires=1753973999&allow_ip=&allow_referer=&signature=WHypvOxMMuzTLOj1ZB3YSC81UH8%3D)\n\n* * *\n\n💡 현대차 투자 시 고려해야 할 요소\n---------------------\n\n### ✅ **긍정적인 요소**\n\n✔ **미국 시장에서의 판매 증가** (특히 친환경차, SUV 강세)\n\n✔ **지배구조 개편 및 인도 법인 IPO 기대감**\n\n✔ **전기차 및 하이브리드 모델의 경쟁력 강화**\n\n### ⚠️ **주의해야 할 요소**\n\n⚠ **글로벌 자동차 시장 둔화 가능성** (경기 침체 및 금리 인상 영향)\n\n⚠ **전기차 시장 경쟁 심화** (테슬라, 중국 전기차 기업들과의 경쟁)\n\n⚠ **원자재 가격 변동 및 환율 리스크**\n\n📢 **현대차는 전기차 시장 확대와 글로벌 판매 증가를 통해 장기적인 성장 가능성이 높은 기업입니다. 하지만 글로벌 경제 상황과 자동차 시장 변동성을 고려하여 신중한 투자 전략을 세우는 것이 중요합니다.**\n\n![Image 5](https://blog.kakaocdn.net/dna/lbx1H/btsL47LA21I/AAAAAAAAAAAAAAAAAAAAAH3rB7fb99lzlycFgN3CzdIdfM_LIa2Ef9tgubS0h08H/img.webp?credential=yqXZFxpELC7KVnFOS48ylbz2pIh7yKj8&expires=1753973999&allow_ip=&allow_referer=&signature=TFVLdAiDgKuehY%2FHZWupiJ30NXY%3D)\n\n* * *\n\n📢 결론: 현대차 주가는 앞으로 어떻게 될까?\n--------------------------\n\n현대차는 **미국 시장에서의 강력한 판매 성장과 친환경차 전략**을 바탕으로 **긍정적인 흐름을 이어갈 가능성이 높습니다.** 하지만, 글로벌 경기 둔화 가능성 및 전기차 시장 경쟁 심화 등의 요소를 고려하여 투자 전략을 수립해야 합니다.\n\n✅ **현대차의 글로벌 판매 실적이 지속적으로 증가할 경우, 주가 상승 가능성이 높습니다.**\n\n⚠ **그러나 글로벌 경제 및 자동차 시장 변동성에 유의하며 투자해야 합니다.**\n\n💡 **앞으로의 주가 흐름을 지속적으로 모니터링하면서, 현대차의 중장기 전략과 실적 발표 등을 참고하여 투자 결정을 내리는 것이 중요합니다.**\n\n📢 **더 자세한 전망을 위해 아래 영상을 참고하세요:**\n\n[🔗 2025 년 현대차 주가 전망 (유튜브)](https://www.youtube.com/watch?v=epoYEbxDF70&utm_source=chatgpt.com)\n\n좋아요 4\n\n공유하기\n\nURL 복사 카카오톡 공유 페이스북 공유 엑스 공유\n\n게시글 관리\n\n_구독하기_**novelone 님의 블로그**\n\n[저작자표시 비영리 변경금지(새창열림)](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.ko)\n\n#### '[경제](https://novelone.tistory.com/category/%EA%B2%BD%EC%A0%9C)>[주식](https://novelone.tistory.com/category/%EA%B2%BD%EC%A0%9C/%EC%A3%BC%EC%8B%9D)' 카테고리의 다른 글\n\n| [2025년 더본코리아 주가 전망: 내수 시장 강자의 새로운 도전](https://novelone.tistory.com/entry/2025%EB%85%84-%EB%8D%94%EB%B3%B8%EC%BD%94%EB%A6%AC%EC%95%84-%EC%A3%BC%EA%B0%80-%EC%A0%84%EB%A7%9D-%EB%82%B4%EC%88%98-%EC%8B%9C%EC%9E%A5-%EA%B0%95%EC%9E%90%EC%9D%98-%EC%83%88%EB%A1%9C%EC%9A%B4-%EB%8F%84%EC%A0%84)(0) | 2025.02.02 |\n| --- |\n| [LG CNS 상장: 국내 IT 서비스 강자의 새로운 도약](https://novelone.tistory.com/entry/LG-CNS-%EC%83%81%EC%9E%A5-%EA%B5%AD%EB%82%B4-IT-%EC%84%9C%EB%B9%84%EC%8A%A4-%EA%B0%95%EC%9E%90%EC%9D%98-%EC%83%88%EB%A1%9C%EC%9A%B4-%EB%8F%84%EC%95%BD)(0) | 2025.02.02 |\n| [ChatGPT O3-Mini 발표 & 엔비디아 주가 폭락: AI 시장의 격변과 미래 전망](https://novelone.tistory.com/entry/ChatGPT-O3-Mini-%EB%B0%9C%ED%91%9C-%EC%97%94%EB%B9%84%EB%94%94%EC%95%84-%EC%A3%BC%EA%B0%80-%ED%8F%AD%EB%9D%BD-AI-%EC%8B%9C%EC%9E%A5%EC%9D%98-%EA%B2%A9%EB%B3%80%EA%B3%BC-%EB%AF%B8%EB%9E%98-%EC%A0%84%EB%A7%9D)(0) | 2025.02.02 |\n| [엔비디아 & 딥시크 & 삼성전자 & 하이닉스 2025년 주가 전망: AI 혁신과 반도체 시장의 변화](https://novelone.tistory.com/entry/%EC%97%94%EB%B9%84%EB%94%94%EC%95%84-%EB%94%A5%EC%8B%9C%ED%81%AC-%EC%82%BC%EC%84%B1%EC%A0%84%EC%9E%90-%ED%95%98%EC%9D%B4%EB%8B%89%EC%8A%A4-2025%EB%85%84-%EC%A3%BC%EA%B0%80-%EC%A0%84%EB%A7%9D-AI-%ED%98%81%EC%8B%A0%EA%B3%BC-%EB%B0%98%EB%8F%84%EC%B2%B4-%EC%8B%9C%EC%9E%A5%EC%9D%98-%EB%B3%80%ED%99%94)(0) | 2025.02.02 |\n| [한화오션 2025년 주가 전망: 트럼프 2.0 시대와 미국 해군 수주, LNG 시장 수혜](https://novelone.tistory.com/entry/%ED%95%9C%ED%99%94%EC%98%A4%EC%85%98-2025%EB%85%84-%EC%A3%BC%EA%B0%80-%EC%A0%84%EB%A7%9D-%ED%8A%B8%EB%9F%BC%ED%94%84-20-%EC%8B%9C%EB%8C%80%EC%99%80-%EB%AF%B8%EA%B5%AD-%ED%95%B4%EA%B5%B0-%EC%88%98%EC%A3%BC-LNG-%EC%8B%9C%EC%9E%A5-%EC%88%98%ED%98%9C)(0) | 2025.02.02 |\n\n태그\n--\n\n[현대차](https://novelone.tistory.com/tag/%ED%98%84%EB%8C%80%EC%B0%A8), [현대차 주가 전망](https://novelone.tistory.com/tag/%ED%98%84%EB%8C%80%EC%B0%A8%20%EC%A3%BC%EA%B0%80%20%EC%A0%84%EB%A7%9D)\n\n관련글\n---\n\n*   [![Image 6](https://i1.daumcdn.net/thumb/C176x120.fwebp.q85/?fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdna%2F55crf%2FbtsL5tgAGfl%2FAAAAAAAAAAAAAAAAAAAAACCNHLZ-uQdFTAx87Jz4aNKi9Fpy8gAqtqSdQmTX5Qu9%2Fimg.webp%3Fcredential%3DyqXZFxpELC7KVnFOS48ylbz2pIh7yKj8%26expires%3D1753973999%26allow_ip%3D%26allow_referer%3D%26signature%3DVUs2jLYlfCF0zjsV%252FTJN5kka3Xo%253D)2025년 더본코리아 주가 전망: 내수 시장 강자의 새로운 도전](https://novelone.tistory.com/entry/2025%EB%85%84-%EB%8D%94%EB%B3%B8%EC%BD%94%EB%A6%AC%EC%95%84-%EC%A3%BC%EA%B0%80-%EC%A0%84%EB%A7%9D-%EB%82%B4%EC%88%98-%EC%8B%9C%EC%9E%A5-%EA%B0%95%EC%9E%90%EC%9D%98-%EC%83%88%EB%A1%9C%EC%9A%B4-%EB%8F%84%EC%A0%84?category=1267875)\n*   [![Image 7](https://i1.daumcdn.net/thumb/C176x120.fwebp.q85/?fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdna%2FStLnF%2FbtsL5rpCciu%2FAAAAAAAAAAAAAAAAAAAAAFvyCyt_ftXTqrxE0gWMXiQuU8A5a2HearvNdsAw0eu_%2Fimg.webp%3Fcredential%3DyqXZFxpELC7KVnFOS48ylbz2pIh7yKj8%26expires%3D1753973999%26allow_ip%3D%26allow_referer%3D%26signature%3DggcPORNDkkyhpiGXSZGEOjGOdW8%253D)LG CNS 상장: 국내 IT 서비스 강자의 새로운 도약](https://novelone.tistory.com/entry/LG-CNS-%EC%83%81%EC%9E%A5-%EA%B5%AD%EB%82%B4-IT-%EC%84%9C%EB%B9%84%EC%8A%A4-%EA%B0%95%EC%9E%90%EC%9D%98-%EC%83%88%EB%A1%9C%EC%9A%B4-%EB%8F%84%EC%95%BD?category=1267875)\n*   [![Image 8](https://i1.daumcdn.net/thumb/C176x120.fwebp.q85/?fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdna%2FbVIxBp%2FbtsL5ANoIw8%2FAAAAAAAAAAAAAAAAAAAAACmgFfYPTKi5MLklLR21ei6Cv8nbsw5kISLlCh2uARR-%2Fimg.webp%3Fcredential%3DyqXZFxpELC7KVnFOS48ylbz2pIh7yKj8%26expires%3D1753973999%26allow_ip%3D%26allow_referer%3D%26signature%3DnjLU5ioXbBTS1ZIl9paDDZQrdgQ%253D)ChatGPT O3-Mini 발표 & 엔비디아 주가 폭락: AI 시장의 격변과 미래 전망](https://novelone.tistory.com/entry/ChatGPT-O3-Mini-%EB%B0%9C%ED%91%9C-%EC%97%94%EB%B9%84%EB%94%94%EC%95%84-%EC%A3%BC%EA%B0%80-%ED%8F%AD%EB%9D%BD-AI-%EC%8B%9C%EC%9E%A5%EC%9D%98-%EA%B2%A9%EB%B3%80%EA%B3%BC-%EB%AF%B8%EB%9E%98-%EC%A0%84%EB%A7%9D?category=1267875)\n*   [![Image 9](https://i1.daumcdn.net/thumb/C176x120.fwebp.q85/?fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdna%2F9tPQz%2FbtsL38YYben%2FAAAAAAAAAAAAAAAAAAAAALcnSmDKGn6T_HzwkpKZLVqg69jlgog-f8ht8cfut4Av%2Fimg.webp%3Fcredential%3DyqXZFxpELC7KVnFOS48ylbz2pIh7yKj8%26expires%3D1753973999%26allow_ip%3D%26allow_referer%3D%26signature%3DoVKIoo8yYlUjXHNunnQeKQfCXN0%253D)엔비디아 & 딥시크 & 삼성전자 & 하이닉스 2025년 주가 전망: AI 혁신과 반도체 시장의 변화](https://novelone.tistory.com/entry/%EC%97%94%EB%B9%84%EB%94%94%EC%95%84-%EB%94%A5%EC%8B%9C%ED%81%AC-%EC%82%BC%EC%84%B1%EC%A0%84%EC%9E%90-%ED%95%98%EC%9D%B4%EB%8B%89%EC%8A%A4-2025%EB%85%84-%EC%A3%BC%EA%B0%80-%EC%A0%84%EB%A7%9D-AI-%ED%98%81%EC%8B%A0%EA%B3%BC-%EB%B0%98%EB%8F%84%EC%B2%B4-%EC%8B%9C%EC%9E%A5%EC%9D%98-%EB%B3%80%ED%99%94?category=1267875)\n\n[novelone 님의 블로그](https://novelone.tistory.com/)[novelone 님의 블로그 입니다.](https://novelone.tistory.com/)구독하기\n\n[](https://novelone.tistory.com/)\n\n댓글 0\n\n- [x] 비밀글 등록\n\n*   [분류 전체보기](https://novelone.tistory.com/category)\n    *   [무료 소설](https://novelone.tistory.com/category/%EB%AC%B4%EB%A3%8C%20%EC%86%8C%EC%84%A4)\n        *   [프랑켄슈타인](https://novelone.tistory.com/category/%EB%AC%B4%EB%A3%8C%20%EC%86%8C%EC%84%A4/%ED%94%84%EB%9E%91%EC%BC%84%EC%8A%88%ED%83%80%EC%9D%B8)\n\n    *   [부동산](https://novelone.tistory.com/category/%EB%B6%80%EB%8F%99%EC%82%B0)\n        *   [정보](https://novelone.tistory.com/category/%EB%B6%80%EB%8F%99%EC%82%B0/%EC%A0%95%EB%B3%B4)\n        *   [정책](https://novelone.tistory.com/category/%EB%B6%80%EB%8F%99%EC%82%B0/%EC%A0%95%EC%B1%85)\n\n    *   [경제](https://novelone.tistory.com/category/%EA%B2%BD%EC%A0%9C)\n        *   [복지](https://novelone.tistory.com/category/%EA%B2%BD%EC%A0%9C/%EB%B3%B5%EC%A7%80)\n        *   [암호화폐](https://novelone.tistory.com/category/%EA%B2%BD%EC%A0%9C/%EC%95%94%ED%98%B8%ED%99%94%ED%8F%90)\n        *   [주식](https://novelone.tistory.com/category/%EA%B2%BD%EC%A0%9C/%EC%A3%BC%EC%8B%9D)\n        *   [대출](https://novelone.tistory.com/category/%EA%B2%BD%EC%A0%9C/%EB%8C%80%EC%B6%9C)\n\n    *   [생활](https://novelone.tistory.com/category/%EC%83%9D%ED%99%9C)\n        *   [근로제도](https://novelone.tistory.com/category/%EC%83%9D%ED%99%9C/%EA%B7%BC%EB%A1%9C%EC%A0%9C%EB%8F%84)\n        *   [연금](https://novelone.tistory.com/category/%EC%83%9D%ED%99%9C/%EC%97%B0%EA%B8%88)\n        *   [기타](https://novelone.tistory.com/category/%EC%83%9D%ED%99%9C/%EA%B8%B0%ED%83%80)\n\n공지사항\n----\n\n* * *\n\n[TOP](https://novelone.tistory.com/entry/2025%EB%85%84-%ED%98%84%EB%8C%80%EC%B0%A8-%EC%A3%BC%EA%B0%80-%EC%A0%84%EB%A7%9D-%EB%AF%B8%EA%B5%AD-%ED%8C%90%EB%A7%A4-%EC%97%AD%EB%8C%80-%EC%B5%9C%EB%8C%80#)\nDesigned by 티스토리\n\n© Kakao Corp.\n\n티스토리툴바\n------\n\n닫기\n단축키\n---\n\n### 내 블로그\n\n| 내 블로그 - 관리자 홈 전환 | Q Q |\n| --- |\n| 새 글 쓰기 | W W |\n\n### 블로그 게시글\n\n| 글 수정 (권한 있는 경우) | E E |\n| --- |\n| 댓글 영역으로 이동 | C C |\n\n### 모든 영역\n\n| 이 페이지의 URL 복사 | S S |\n| --- |\n| 맨 위로 이동 | T T |\n| 티스토리 홈 이동 | H H |\n| 단축키 안내 | Shift + / ⇧ + / |\n\n* 단축키는 한글/영문 대소문자로 이용 가능하며, 티스토리 기본 도메인에서만 동작합니다.\n"},
 {'url': 'https://seo.goover.ai/report/202506/go-public-report-ko-650e4de3-b7b3-4916-b47d-9293ec9ecd1f-0-0.html',
  'title': '현대차 2025년 2분기 실적 전망: 관세 리스크와 성장 모멘텀의 교차로',
  'content': '본 리포트는 현대차의 2025년 2분기 실적 전망을 분석하며, 주된 외부 변수인 미국의 25% 관세와 원·달러 환율 변동에 따른 영향에 대한 심층적인 검토를 제공합니다. 현대차는 관세 부과로 인해 대미 수출 물량이 20% 감소하며, 연간 영업이익이 약 5조 원 감소할 것으로 보입니다. 이러한 외부 환경 변화는 현대차의 성장 모멘텀에 결정적인 도전 과제가 되고 있습니다.\n\n   2025년 1분기 실적은 매출 37조7787억원, 영업이익 3조5927억원으로 전년 동기 대비 큰 폭의 성장세를 보였으나, 2분기 전망은 장기적인 성장성 유지에 있어 결정적인 변곡점이 될 것입니다. 향후 현대차는 현지 생산 확대를 통해 관세 부담을 완화하고, 추가적인 실적 부진을 최소화하기 위한 전략을 모색할 필요성이 큽니다.\n\n서론\n-- [...] 미국 정부의 25% 자동차 관세 부과는 현대차의 대미 수출에 직접적인 타격을 주고 있습니다. 현대차의 미국 수출 물량은 최근 20% 감소하였으며, 이는 2020년 코로나19 사태로 인한 선적 감소 이후 처음으로 나타난 현상입니다. 이러한 관세 부과로 인해 현대차의 연간 영업이익이 약 5조 원 감소할 것이라는 분석까지 등장하고 있습니다. 저렴한 가격대의 차종이 아닌 고가 차종 위주로 미국 시장에 진출한 현대차로서는 가격 경쟁력에 심각한 도전 과제를 안고 있습니다.\n\n   현재 현대차는 조지아주 신공장의 생산 능력을 증가시켜 미국 내 생산 비중을 높이고 관세 비용 상승세에 대응하고자 노력하고 있습니다. 하지만 관세가 본격적으로 적용되는 오는 6월과 7월 사이의 판매 실적은 예상보다 부진할 가능성이 높습니다. 미국 소비자들이 이미 관세 부과 전 차량 구매를 몰아간 점에서, 2분기 매출은 플러스 성장이 사실상 어려울 것으로 분석되고 있습니다. [...] 현대차의 성장모멘텀은 관세 협상 진행 상황에도 크게 의존하고 있습니다. 미국과의 협상에서 완화된 조건이 성립된다면, 영업이익의 하향 압력을 덜 수 있는 가능성이 있습니다. 최근의 재료비 상승과 규제 변화가 주가의 추가적인 하락을 유발할 수 있으나, 긍정적인 협상 결과는 주가 회복을 이끌 수 있습니다. 따라서, 관세 이슈 및 국제 정세의 변화를 면밀히 주시하는 것이 중요합니다.\n\n결론\n--\n\n   현대차의 2025년 2분기 실적 전망은 관세와 환율 변동이라는 외부 요인의 압박 속에서 상당히 불확실한 상태에 놓여 있습니다. 1분기 성과는 긍정적이었지만, 2분기 실적에 우려가 커지는 가운데, 현대차는 이러한 난관을 극복하기 위한 다양한 전략을 강구해야 할 시점에 있습니다. 특히, 현지 생산 확대와 재고 활용을 통해 비용 절감에 나서는 것이 중요할 것입니다.',
  'score': 0.9094659,
  'raw_content': '현대차 2025년 2분기 실적 전망: 관세 리스크와 성장 모멘텀의 교차로\n\n===============\n\n[![Image 1: goover](https://goover.ai/seo/go-goover-logo.png)](https://intro.goover.ai/)\n\n**This report was created by AI. Like what you see? [Discover Goover](https://goover.ai/) and unlock more insights!**\n\n[Sign up](https://goover.ai/register)[Log in](https://goover.ai/login)\n\n![Image 2](https://dqrvsa6iqgtew.cloudfront.net/report-image-default/sample_image_74.jpg)\n\n현대차 2025년 2분기 실적 전망: 관세 리스크와 성장 모멘텀의 교차로\n========================================\n\n일반 리포트 2025년 06월 02일\n\n![Image 3: goover](https://goover.ai/seo/go-goover-logo.png)\n\n목차\n--\n\n1.   매크로 환경 및 관세·환율 리스크\n2.   1분기 실적 리뷰 및 주요 동인\n3.   2분기 실적 전망 시나리오\n4.   투자 전략 및 결론\n\n요약\n--\n\n*   본 리포트는 현대차의 2025년 2분기 실적 전망을 분석하며, 주된 외부 변수인 미국의 25% 관세와 원·달러 환율 변동에 따른 영향에 대한 심층적인 검토를 제공합니다. 현대차는 관세 부과로 인해 대미 수출 물량이 20% 감소하며, 연간 영업이익이 약 5조 원 감소할 것으로 보입니다. 이러한 외부 환경 변화는 현대차의 성장 모멘텀에 결정적인 도전 과제가 되고 있습니다.\n\n*   2025년 1분기 실적은 매출 37조7787억원, 영업이익 3조5927억원으로 전년 동기 대비 큰 폭의 성장세를 보였으나, 2분기 전망은 장기적인 성장성 유지에 있어 결정적인 변곡점이 될 것입니다. 향후 현대차는 현지 생산 확대를 통해 관세 부담을 완화하고, 추가적인 실적 부진을 최소화하기 위한 전략을 모색할 필요성이 큽니다.\n\n서론\n--\n\n*   현대차는 최근 몇 년간 세계 자동차 시장에서 성장과 변화를 거듭해왔지만, 급변하는 경영 환경 속에서 위기를 맞이하고 있습니다. 특히, 미국 정부가 시행한 25% 자동차 관세는 현대차의 대미 수출에 심각한 타격을 주고 있으며, 환율 변동성 또한 회사의 영업 성과에 막대한 영향을 미치고 있습니다. 이러한 우려 속에서 2025년 2분기 실적은 관세와 환율이라는 외부 요인, 그리고 내수 및 수출 모멘텀 간의 복합적인 관계 속에서 어떤 양상을 띨지 궁금해집니다.\n\n*   이에 본 리포트는 현대차의 2분기 실적 전망을 다각적으로 분석하고, 이를 통해 투자자들이 명확한 전략을 세울 수 있도록 돕고자 합니다. 매크로 경제 환경 분석, 1분기 실적 리뷰, 2분기 전망 시나리오, 그리고 구체적인 투자 전략을 제시하여, 현대차가 위기 속에서도 성장 가능성을 유지할 수 있는 방안을 모색하겠습니다.\n\n3. 매크로 환경 및 관세·환율 리스크\n---------------------\n\n*   현대자동차는 지금까지 경험하지 못한 경영 압박에 직면하고 있습니다. 미국에서의 25% 관세 부과와 원·달러 환율의 급격한 변동, 그리고 노조와의 촉박한 협상은 현대차의 글로벌 경쟁력에 결정적인 영향을 미치고 있습니다. 이러한 외부 압박은 단순히 숫자로만 표현되는 경영 성과에 국한되지 않고, 고객들에게 제공하는 가치와 브랜드 신뢰도에까지 중대한 파장을 미치고 있습니다.\n\n*   ### 3-1. 미국 25% 관세 부과 현황 및 향후 일정\n\n*   미국 정부의 25% 자동차 관세 부과는 현대차의 대미 수출에 직접적인 타격을 주고 있습니다. 현대차의 미국 수출 물량은 최근 20% 감소하였으며, 이는 2020년 코로나19 사태로 인한 선적 감소 이후 처음으로 나타난 현상입니다. 이러한 관세 부과로 인해 현대차의 연간 영업이익이 약 5조 원 감소할 것이라는 분석까지 등장하고 있습니다. 저렴한 가격대의 차종이 아닌 고가 차종 위주로 미국 시장에 진출한 현대차로서는 가격 경쟁력에 심각한 도전 과제를 안고 있습니다.\n\n*   현재 현대차는 조지아주 신공장의 생산 능력을 증가시켜 미국 내 생산 비중을 높이고 관세 비용 상승세에 대응하고자 노력하고 있습니다. 하지만 관세가 본격적으로 적용되는 오는 6월과 7월 사이의 판매 실적은 예상보다 부진할 가능성이 높습니다. 미국 소비자들이 이미 관세 부과 전 차량 구매를 몰아간 점에서, 2분기 매출은 플러스 성장이 사실상 어려울 것으로 분석되고 있습니다.\n\n*   ### 3-2. 원·달러 환율 변동 추이\n\n*   원·달러 환율은 현대차 실적에 중요한 변수로 작용하고 있습니다. 2025년 1분기 평균 환율이 1453원이었던 반면, 최근 환율은 1380원대로 급락하면서 현대차의 실적에 부정적인 영향을 미치고 있습니다. 해외 판매 비중이 높은 현대차는 원화 강세가 이어질 경우 평균 판매 단가(ASP)의 감소를 피할 수 없습니다. 이로 인해 향후 실적에 대한 기대치는 점점 저조해지고 있습니다.\n\n*   예를 들어 한국투자증권은 현대차의 ASP가 달러 기준으로 이미 역성장에 가까운 수치를 기록할 것으로 보며, 이번 원화 강세가 지속되면 추가적인 실적 부진이 우려된다고 밝혔습니다. 지난 1분기 환율 상승이 긍정적인 영향을 미쳤지만, 이제는 급변하는 외부 환경에 의해 역풍을 맞을 날이 멀지 않았다는 실상을 반영하고 있습니다.\n\n*   ### 3-3. 주요 원자재 가격·노조 리스크\n\n*   원자재 가격 변동 역시 현대차의 경영에 영향을 미치고 있습니다. 금속 가격과 반도체 수급 부진이 겹쳐 부품 생산비용 상승을 초래하고 있으며, 이는 곧 차량의 총 제조 단가에 반영되고 있습니다. 이러한 상황에서 현대차는 추가적인 비용 절감을 위해 공급망 최적화와 현지 물량 조정을 강구하고 있으나, 현실적으로 해결해야 할 과제가 많습니다.\n\n*   또한, 올 여름 시작될 임단협은 또 다른 불안 요소로 자리 잡고 있습니다. 노조는 이번 협상에서 대규모의 임금 인상과 근무 조건 개선을 요구할 것으로 예상되고 있으며, 회사의 재정적 여건이 여의치 않은 만큼 갈등은 고조될 가능성이 큽니다. 현대차는 노조와의 협상에서 관세와 환율 등 외부 리스크가 가시화된 상황에서 내부 체질 개선의 필요성을 강조하며 균형을 찾아가려는 노력을 기울이고 있습니다.\n\n4. 1분기 실적 리뷰 및 주요 동인\n--------------------\n\n*   현대차의 2025년 1분기 실적은 역대급 성과로 기록되었습니다. 매출 37조7787억원, 영업이익 3조5927억원, 순이익 3조4194억원이라는 수치는 모두 전년 동기 대비 큰 폭으로 성장한 것입니다. 특히, 이러한 성장은 SUV 및 친환경차의 판매 증대와 함께 평균판매단가(ASP)의 향상에 기인하고 있습니다. 이는 단순한 숫자를 넘어 현대차의 전략적 유연성과 시장 내 위치를 잘 보여주는 사례입니다.\n\n*   ### 4-1. 1분기 매출·영업이익 실적 요약\n\n*   2025년 1분기 현대차는 총 102만1712대를 판매하며, 이는 전년 동기 대비 13.2% 증가한 수치입니다. 특히 내수 시장에서의 판매는 25.6% 상승하여 19만1047대를 기록했습니다. 이러한 판매 성장은 도심형 SUV 및 제네시스 브랜드의 누적 판매 증가로 이어지고 있으며, 이에 따라 평균판매단가가 3조1360억원의 매출 증대 효과를 초래하였습니다. 매출 원가율 또한 개선되어 79.6%로, 이는 부품 공급 상황의 개선과 환율 효과 덕분입니다.\n\n*   이는 전반적인 판매 성장을 바탕으로 하였으며, 현대차의 전략적 계획이 성공적으로 실행되고 있음을 상징합니다. 그러나 이러한 긍정적인 성과 뒤에는 지정학적 리스크와 금리 인상으로 인한 수요 감소 우려가 함께하고 있음을 주의할 필요가 있습니다.\n\n*   ### 4-2. SUV·친환경차 판매 믹스 개선\n\n*   현대차의 1분기 판매 믹스에서 SUV와 친환경차의 비중 상승은 주목할 만한 변화입니다. SUV 판매 비중은 지난해 57.2%에서 57.8%로 증가하였고, 친환경차의 판매는 전년 대비 38.8% 상승하여 총 16만1000대에 달했습니다. 이 같은 변화는 고객의 환경 친화적 요구에 부응하는 동시에 기업의 지속 가능성 전략에도 부합합니다.\n\n*   특히, 고부가가치 차종의 판매 증대는 ASP 상승으로 이어졌고, 이는 현대차의 수익성을 더욱 강화하는 요소로 작용하고 있습니다. 고객의 선호도 변화에 발맞춘 모델 개발과 마케팅 전략 덕분에 현대차는 시장에서의 경쟁력을 계속해서 확장할 수 있게 되었습니다.\n\n*   ### 4-3. 환율 상승 효과 및 분기 배당 발표\n\n*   이번 분기에서는 원달러 평균 환율이 1276원으로 전년 대비 5.9% 상승하면서 매출 증대에 기여하였습니다. 환율 상승은 해외 매출을 수익성 있게 전환시키는 데 중요한 역할을 했으며, 이러한 요소는 현대차의 글로벌 시장 내에서 경쟁력을 강화하는 데 긍정적인 영향을 미쳤습니다.\n\n*   또한, 현대차는 주주 가치를 최대화하기 위해 신규 배당 정책을 발표했습니다. 기존 잉여현금흐름(FCF)을 기준으로 하던 배당 기준을 연결 지배주주 순이익으로 변경하였고, 이제는 분기별로 배당을 실시하기로 결정한 것입니다. 이러한 변화는 투자자들에게 보다 예측 가능하고 투명한 배당을 제공하여, 장기 보유의 매력을 더욱 강화할 것으로 기대됩니다.\n\n5. 2분기 실적 전망 시나리오\n-----------------\n\n*   2025년 2분기 현대차의 실적 전망은 관세와 환율, 그리고 내부적인 판매 모멘텀 간의 상호작용에 의해 크게 좌우될 것으로 예상됩니다. 특히 미국에서의 관세 부과의 여파가 크기 때문에, 이를 준비하고 대응하는 전략이 무엇보다 중요합니다. 이러한 변수들은 현대차의 매출 및 영업이익에 중대한 영향을 미칠 수 있으며, 다양한 시나리오를 통해 이를 분석해 볼 필요가 있습니다. 이제 각각의 시나리오를 살펴보겠습니다.\n\n*   ### 5-1. 낙관 시나리오: 현지 생산 확대·재고 활용으로 비용 축소\n\n*   낙관적인 시나리오에서는 현대차가 현지 생산을 확대하고 재고를 효과적으로 활용함으로써 비용 절감을 이룰 것으로 보여집니다. 현대차는 현재 미국 내 생산 라인을 더욱 강화하고 있으며, 이를 통해 관세의 영향을 최소화할 전략을 모색 중입니다. 이러한 전략은 이미 GM과 토요타가 경험한 바와 같이, 생산 물량을 조정함으로써 부정적인 영향을 완화할 수 있는 가능성이 큽니다. 더불어, 하이브리드차와 같은 친환경 모델의 판매 증가는 안정적인 수익 기반을 제공할 것으로 보이며, 중장기적으로는 이익률 개선에 기여할 수 있습니다. 실질적으로 미국 내 고부가가치 차종에 대한 수요가 증가하며, 높은 가격대의 모델에서 판매 증가가 나타날 경우, 현대차는 관세 부담을 효과적으로 상쇄할 수 있을 것입니다. 이러한 긍정적인 요소들이 복합적으로 작용한다면, 현대차는 까다로운 매크로 환경 속에서도 희망적인 실적을 달성할 가능성이 높아지게 됩니다.\n\n6. 투자 전략 및 결론\n-------------\n\n*   현대차의 진정한 도전은 2025년의 글로벌 환경에서 어떻게 흔들림 없이 성장 가능성을 유지하느냐에 달려 있습니다. 관세와 환율이라는 외생 변수들이 영업 실적에 미치는 영향이 더욱 심각해지는 시점에서, 신중한 투자 전략은 그 어느 때보다도 중요합니다. 이러한 맥락에서, 현대차의 2분기 실적 전망 및 이를 반영한 투자 전략이 주목받고 있습니다.\n\n*   ### 6-1. 목표주가·투자의견 요약\n\n*   현재 현대차의 목표주가는 27만원으로 하향 조정되었습니다. 이는 미국의 25% 관세 부과가 미치는 영향을 반영한 것으로, 2025년의 영업이익은 기존 예상 대비 12% 감소한 12조5000억원이 될 것으로 추정됩니다. 이 보고서에서는 현대차의 PER(주가수익비율)가 4배에 불과하며, 이는 주가 하락에 대한 어느 정도의 방어력을 제공할 것입니다. SK증권에서는 투자 의견을 \'매수\'로 유지하였으며, 가격 조정의 부담에도 불구하고 향후 가파른 회복세를 기대하고 있습니다.\n\n*   ### 6-2. 배당수익률과 자사주 매입 효과\n\n*   현대차는 주주 가치를 증대시키기 위한 다양한 전략을 채택하고 있습니다. 자사주 매입과 배당은 단기적으로 주가를 지탱하는 역할을 할 것입니다. 예상 배당수익률은 약 3%로 보이며, 자사주 매입은 주가 상승 요인으로 작용할 수 있습니다. 과거에도 현대차는 안정적인 배당 정책을 통해 투자자들에게 매력적인 투자처로 자리 잡아 왔습니다. 현재 이러한 정책이 강화되면 안정적인 수익을 추구하는 투자자들에게 긍정적인 신호로 작용할 것입니다.\n\n*   ### 6-3. 관세 협상 전개 가능성 및 주가 모멘텀\n\n*   현대차의 성장모멘텀은 관세 협상 진행 상황에도 크게 의존하고 있습니다. 미국과의 협상에서 완화된 조건이 성립된다면, 영업이익의 하향 압력을 덜 수 있는 가능성이 있습니다. 최근의 재료비 상승과 규제 변화가 주가의 추가적인 하락을 유발할 수 있으나, 긍정적인 협상 결과는 주가 회복을 이끌 수 있습니다. 따라서, 관세 이슈 및 국제 정세의 변화를 면밀히 주시하는 것이 중요합니다.\n\n결론\n--\n\n*   현대차의 2025년 2분기 실적 전망은 관세와 환율 변동이라는 외부 요인의 압박 속에서 상당히 불확실한 상태에 놓여 있습니다. 1분기 성과는 긍정적이었지만, 2분기 실적에 우려가 커지는 가운데, 현대차는 이러한 난관을 극복하기 위한 다양한 전략을 강구해야 할 시점에 있습니다. 특히, 현지 생산 확대와 재고 활용을 통해 비용 절감에 나서는 것이 중요할 것입니다.\n\n*   더불어, 관세 협상 결과가 현대차의 영업이익에 미치는 영향은 중장기적인 성과 변동성을 결정하게 될 것입니다. 향후 추가적인 연구가 필요하겠지만, 주식 시장에서 현대차의 주가는 관세 및 환율 리스크에 민감하게 반응할 것으로 보입니다. 따라서 투자자들은 이를 반영한 전략적 접근이 요구됩니다.\n\n*   결국, 현대차의 향후 성장 경로는 글로벌 경제 환경 및 내부 경영 전략에 달려 있습니다. 이러한 변화의 연속 속에서 유연한 대처와 전략적 투자가 함께 이루어져야, 현대차는 지속 가능한 성장과 함께 주주 가치를 증대시킬 수 있을 것입니다.\n\n용어집\n---\n\n*   현대차: 한국의 대표적인 자동차 제조 기업으로, 현재 글로벌 시장에서 SUV 및 친환경차 분야에서 두각을 나타내고 있다.\n\n*   관세: 국가 간 물품 수출입 시 부과되는 세금으로, 현대차는 미국에서의 25% 자동차 관세로 인해 대미 수출에 큰 타격을 받고 있다.\n\n*   환율: 두 통화 간의 교환 비율로, 환율의 변동은 현대차의 해외 매출 및 수익성에 중요한 영향을 미친다.\n\n*   영업이익: 기업의 본업에서 발생하는 수익에서 경비를 제외한 순수익을 의미하며, 현대차의 영업이익은 관세와 환율에 따라 크게 변동할 수 있다.\n\n*   ASP(평균판매단가): 판매된 제품의 평균 가격으로, 현대차의 경쟁력 및 매출에 중요한 지표이다.\n\n*   SUV(스포츠 유틸리티 차량): 상대적으로 높은 차체와 더 넓은 공간을 가진 자동차 유형으로, 현대차의 판매 믹스에서 중요한 역할을 하고 있다.\n\n*   친환경차: 환경 오염을 최소화하기 위해 설계된 차종으로, 전기차와 하이브리드차 등이 포함된다.\n\n*   재고: 판매를 위해 보유하고 있는 제품으로, 현대차는 이 재고를 효과적으로 활용하여 비용을 절감할 수 있는 전략을 구사하고 있다.\n\n*   투자 전략: 특정 자산에 대한 투자 결정을 내리는 방안을 의미하며, 현대차의 경우 관세 및 환율 변동에 따른 전략을 강구해야 한다.\n\n*   목표주가: 특정 주식의 예상 거래 가격으로, 현대차의 목표주가는 외부 변수에 따라 조정되고 있다.\n\n*   주주 가치를 증대: 투자자들에게 돌아가는 이익을 증가시키는 것을 의미하며, 현대차는 자사주 매입과 배당 확대 정책을 통해 이를 추진하고 있다.\n\n*   노조: 직원들의 권익을 보호하기 위해 조직된 단체로, 현대차와의 임금 협상에서 중요한 역할을 한다.\n\n*   매크로 경제: 전체 경제에 영향을 미치는 큰 요인들을 포함하는 경제적 접근으로, 현대차의 실적에 큰 영향을 미친다.\n\n*   부품 생산비용: 차량을 조립하는 데 드는 비용으로, 원자재 가격 및 반도체 수급 상황에 따라 영향을 받는다.\n\n*   관세 협상: 국가 간의 무역 조건을 정하는 절차로, 현대차는 미국과의 관세 협상에서 영업이익에 영향을 미칠 수 있는 중요한 요소다.\n\n*   갈등: 노사 간의 대립 상황을 의미하며, 현대차는 노조와의 협상에서 이러한 문제가 발생할 수 있다.\n\n출처 문서\n\n*   **“관세·환율·노조”···현대차 ‘삼중고’ - 시사저널e**[https://www.sisajournal-e.com/news/articleView.html?idxno=412178](https://www.sisajournal-e.com/news/articleView.html?idxno=412178)\n*   **"현대차·기아, 美 관세로 월 이익 7000억 타격"**[https://kpinews.kr/newsView/1065597152851984](https://kpinews.kr/newsView/1065597152851984)\n*   **현대차, 1Q 사상 최대 매출 38조·영업이익 3.5조…"분기 배당 실시"**[https://v.daum.net/v/b6wpBzxvTZ?f=p](https://v.daum.net/v/b6wpBzxvTZ?f=p)\n*   **현대차 \'매출 피크\'…美관세 영향에 2분기부터 \'먹구름\' 오나**[https://v.daum.net/v/20250424180303424](https://v.daum.net/v/20250424180303424)\n*   **＂현대차, 역대급 1분기 실적…관세 부담에도 반등 가능성＂ [DB증권]**[https://m.ilyoweekly.co.kr/news/newsview.php?ncode=1065574639945621](https://m.ilyoweekly.co.kr/news/newsview.php?ncode=1065574639945621)\n*   **현대차, 1분기 실적 기대치 상회…2분기 관세 부담 최대 변수-유진**[https://www.edaily.co.kr/News/Read?newsId=02122166642139728&mediaCodeNo=257](https://www.edaily.co.kr/News/Read?newsId=02122166642139728&mediaCodeNo=257)\n*   **현대차, \'2분기부터 서서히 나타날 관세 충격\' 목표가 270, 000원 - 신한투자증권**[https://www.newspim.com/news/view/20250411000141](https://www.newspim.com/news/view/20250411000141)\n*   **Today\'s Pick : "현대차 영업익 5.2조 감소 예상…목표가 하향"**[https://www.hankyung.com/article/202504086550i](https://www.hankyung.com/article/202504086550i)\n*   **SK證 현대차, 2Q 실적부터 관세 영향권…목표가↓ | 아주경제**[https://www.ajunews.com/view/20250408081244981](https://www.ajunews.com/view/20250408081244981)\n'},
 {'url': 'https://seo.goover.ai/report/202504/go-public-report-ko-deb4e471-2938-494b-b19c-6eb5e10b1286-0-0.html',
  'title': '2025년 현대차·기아의 미국 시장 정복 전략: 전기차와 하이브리드가 ...',
  'content': "현대차·기아는 2025년 미국 시장에서 사상 최대 실적을 목표로 설정하고, 전기차와 하이브리드 시장에서 강력한 성장세를 이어가고 있습니다. 이들은 특히 차량 모델 경쟁력을 높이기 위해 공격적인 신차 출시와 마케팅 전략을 통해 판매 목표를 달성하고자 합니다. 미국 소비자들의 요구를 충족시키기 위해 SUV와 친환경차 중심으로 제품 라인업을 확장하고 고수익 차종 비중을 늘리고 있습니다. 또한, 2024년에는 소매 판매 기준으로 165만 대 판매를 돌파하는 성과를 기대하고 있으며, 이를 위해 시각적 매력과 기능성을 극대화한 신차 개발에 힘쓰고 있습니다. [...] 2025년 미국 자동차 시장에서 현대차·기아는 전기차와 하이브리드 시장에서의 리더십 강화를 위해 지속적인 혁신과 성장 전략을 구사하고 있습니다. 소비자들이 친환경 차량에 대한 선호도를 높이고 있는 가운데, 현대차·기아는 이들의 기대에 부응하기 위해 전기차와 하이브리드 차량의 생산 및 판매 확대에 주력하고 있습니다. 인플레이션 감축법(IRA)과 같은 정책적 변화에도 발 빠르게 대응하며, 현지 생산 비율을 높여 경쟁력을 유지하는 동시에, 소비자들에게 보다 합리적인 가격을 제공할 수 있는 노력을 지속하고 있습니다. [...] 현대차·기아는 2025년 동안 하이브리드 모델의 판매를 더욱 확대할 계획입니다. 특히, '디 올 뉴 싼타페 하이브리드'가 출시되면서 기대되는 판매량 증가가 주효할 것으로 예상됩니다. 이 모델은 1.6리터 직분사 터보차지 하이브리드를 탑재하여 최고출력 232마치를 제공하며, 우수한 연비를 자랑하여 소비자들의 호응을 얻을 것으로 보입니다. 또한, 현대차그룹은 기존의 전동화 생산라인을 활용하여 전기차와 하이브리드차를 동시에 생산할 수 있는 체계를 갖추고 있어, 급증하는 하이브리드 수요에 유연하게 대응할 수 있을 것입니다.\n\n5. 향후 전망 및 결론\n-------------\n\n   ### 5-1. 미국 자동차 시장의 변화",
  'score': 0.9092728,
  'raw_content': "2025년 현대차·기아의 미국 시장 정복 전략: 전기차와 하이브리드가 이끄는 성장\n\n===============\n\n[![Image 1: goover](https://goover.ai/seo/go-goover-logo.png)](https://intro.goover.ai/)\n\n**This report was generated by AI. If you like the report, please click the icon to use [Goover Service](https://goover.ai/)**\n\n[Sign up](https://goover.ai/register)[Log in](https://goover.ai/login)\n\n![Image 2](https://alpha.goover.ai:7999/thumbnail/insight-cover/db133fbc-258e-4347-a4f5-acf64a567885.jpg)\n\n2025년 현대차·기아의 미국 시장 정복 전략: 전기차와 하이브리드가 이끄는 성장\n=============================================\n\n일반 리포트 2025년 04월 01일\n\n![Image 3: goover](https://goover.ai/seo/go-goover-logo.png)\n\n목차\n--\n\n1.   요약\n2.   현대차·기아의 미국 시장 전략 분석\n3.   전기차 생산의 본격화와 그 의미\n4.   하이브리드 시장의 급성장과 현대차·기아의 대응\n5.   향후 전망 및 결론\n6.   결론\n\n1. 요약\n-----\n\n*   현대차·기아는 2025년 미국 시장에서 사상 최대 실적을 목표로 설정하고, 전기차와 하이브리드 시장에서 강력한 성장세를 이어가고 있습니다. 이들은 특히 차량 모델 경쟁력을 높이기 위해 공격적인 신차 출시와 마케팅 전략을 통해 판매 목표를 달성하고자 합니다. 미국 소비자들의 요구를 충족시키기 위해 SUV와 친환경차 중심으로 제품 라인업을 확장하고 고수익 차종 비중을 늘리고 있습니다. 또한, 2024년에는 소매 판매 기준으로 165만 대 판매를 돌파하는 성과를 기대하고 있으며, 이를 위해 시각적 매력과 기능성을 극대화한 신차 개발에 힘쓰고 있습니다.\n\n*   특히 전기차와 하이브리드 차량의 혼류 생산 방식은 현대차·기아의 제조 효율성을 높이고 시장 변화에 빠르게 대응할 수 있는 기반이 되고 있습니다. 2023년에는 미국 시장에서 친환경차 판매가 전년 대비 52.3% 증가하며, 이는 앞으로도 지속될 것으로 전망됩니다. 현대차·기아는 다양한 차급의 전기차 모델 출시 계획을 통해 소비자 선택의 폭을 확대하며, 이를 통해 시장 점유율을 높이고 있습니다.\n\n*   미국 시장에서 현대차·기아는 현지 생산을 강조하며 인플레이션 감축법(IRA)의 혜택을 최대한 활용하고 있습니다. 모든 전기차 모델이 미국 내에서 생산되어야 하는 현재의 규제 환경 속에서도, 이들은 소비자에게 보다 유리한 조건의 인센티브를 제공하여 경쟁력을 강화하고 있습니다. 지속적인 연구 개발을 통해 현대차·기아는 변화하는 소비자 기대에 부응하며, 품질 높은 제품과 서비스를 제공하기 위해 노력하고 있습니다.\n\n2. 현대차·기아의 미국 시장 전략 분석\n----------------------\n\n*   ### 2-1. 사상 최대 실적 목표\n\n*   현대차·기아는 2025년 미국 시장에서 사상 최대 실적을 목표로 하고 있습니다. 2024년 북미 시장에서의 판매 목표를 218만2000대로 잡았으며, 이는 전년 대비 4.3% 증가한 수치입니다. 이러한 목표는 현대차·기아가 공격적인 신차 출시와 마케팅 전략을 통해 가능하다고 판단하고 있기 때문입니다. 특히, SUV와 친환경차 중심으로 판매를 확대하며 고수익 차종 비중을 늘려 수익성을 개선하려는 계획이 포함되어 있습니다. 실제로, 2024년 현대차·기아는 소매 판매 기준으로 연간 165만대 판매를 처음으로 돌파하는 성과를 거두었습니다.\n\n*   또한, 현대차·기아는 미국 시장에서의 성장을 위해 지속적인 투자를 하고 있으며, 특히 시각적인 매력과 기능성을 갖춘 5세대 완전변경 싼타페와 같은 신차를 통해 높은 판매 실적을 유지하려 하고 있습니다. 이러한 차량들은 미국 소비자들이 선호하는 아웃도어 콘셉트로 개발되어, 판매 증가에 기여할 것으로 기대됩니다.\n\n*   ### 2-2. 전기차와 하이브리드의 결합 전략\n\n*   현대차·기아는 전기차(BEV)와 하이브리드(HEV) 차량의 생산을 혼류생산 방식으로 전환하여 양쪽 시장에서의 경쟁력을 강화하고 있습니다. 이를 통해 기존 공장에서 전기차와 하이브리드를 동시에 생산함으로써, 제조 효율성을 높이고 시장 변화에 즉각적으로 대응할 수 있는 체제를 구축하고 있습니다. 2023년에는 미국 시장에서 전년 대비 52.3% 증가한 27만8122대의 친환경차를 판매하였으며, 이러한 추세는 앞으로도 지속될 것으로 보입니다.\n\n*   또한, 현대차와 기아는 미리 계획된 신차 출시에 힘입어 고객의 선택의 폭을 넓히려 하고 있습니다. 현대차의 아이오닉7과 기아의 EV9과 같은 대형 전기차는 물론, 더 작은 차급의 전기차도 추가하여 다양한 소비자 요구를 충족할 계획입니다. 이와 같은 전략은 전기차 수요가 증가하는 가운데 다양한 차급의 차량을 제공함으로써 현대차·기아의 시장 점유율 확대에 긍정적인 영향을 미칠 것입니다.\n\n*   ### 2-3. 시장 내 경쟁력 강화 방안\n\n*   현대차·기아는 미국 시장 내 경쟁력 강화를 위해 다양한 전략을 채택하고 있습니다. 우선, 인플레이션 감축법(IRA) 시행에 따른 보조금 혜택이 축소된 상황에서도 경쟁력을 유지하기 위해 현지에서의 생산을 강조하고 있습니다. IRA 규정에 따라 현지에서 생산된 전기차는 세액 공제를 받을 수 있는데, 이를 통해 가격 경쟁력을 확보할 수 있습니다.\n\n*   또한, 현대차·기아는 고객에게 더 나은 인센티브를 제공하여 판매를 촉진하고 있는 점도 특징적입니다. 특히 미국 내 판매 목표를 달성하기 위해 판매 장려금(인센티브) 정책을 강화하고 있으며, 이는 소비자들에게 더 유리한 조건으로 차량 구매를 유도하는 역할을 하고 있습니다. 이렇게 만들어진 판매 환경은 결국 수익성 강화로 이어질 것으로 기대됩니다.\n\n*   마지막으로, 현대차·기아는 지속적인 연구 개발과 시장 조사로 변화하는 소비자 트렌드에 맞춰 제품과 서비스를 개선해 나가고 있습니다. 이는 브랜드 이미지 향상은 물론, 소비자 로열티를 증가시키는 데 중요한 요소로 작용할 것입니다.\n\n3. 전기차 생산의 본격화와 그 의미\n--------------------\n\n*   ### 3-1. 미국 내 전기차 생산기지 현황\n\n*   현대차·기아는 미국 시장에서 전기차 생산을 본격화하고 있으며, 이는 국내외 시장에서의 경쟁력을 강화하기 위한 중요한 전략입니다. 이러한 전략의 일환으로 현대차·기아는 조지아주와 앨라배마주에 전기차 생산 공장을 운영하고 있습니다. 특히, 조지아주 웨스트포인트 공장에서는 기아의 EV9과 같은 대형 전기 SUV 모델을 생산할 예정인데, 이는 미국 내 수요에 즉각 대응할 수 있는 체계를 구축하는 것을 목표로 하고 있습니다.\n\n*   또한, 현대차 그룹에서 설계한 'HMGMA(현대자동차그룹 메타플랜트 아메리카)'는 연간 30만 대의 전기차를 양산할 수 있는 규모를 목표로 하고 있어, 이는 북미에서의 전기차 생산 확대를 실현하는 기반이 될 것입니다. 현대차는 아이오닉5와 같은 모델을 이 공장에서 첫 생산할 계획이며, 이는 소비자들에게 더 많은 품질 높은 전기차 모델을 제공할 수 있는 기회를 열어줍니다.\n\n*   ### 3-2. 인플레이션 감축법(IRA)의 영향\n\n*   인플레이션 감축법(IRA)은 미국 연방 정부가 환경 친화적인 자동차의 구매를 장려하기 위해 시행한 법률로, 이를 통해 소비자들에게 세액 공제를 제공합니다. 현대차·기아는 이러한 법을 활용하여 미국 내 전기차 판매를 확대하려 하고 있습니다. 그러나 IRA 규정이 더욱 강화됨에 따라 보조금 혜택을 받기 위한 자격을 갖춘 차량의 수가 감소한 상황에서, 현대차·기아는 이를 기회로 삼아 현지 생산을 늘리고 있습니다.\n\n*   2024년 1월부터 시행된 IRA의 세부 조항에 따라 미국 내에서 판매되는 전기차는 반드시 미국 내 생산 공장에서 제조되어야 하며, 이는 현대차·기아가 미국 내에서의 공장 가동을 강화하고 현지 생산 비율을 2030년까지 75%까지 높이겠다는 전략적 목표를 수립하는 데 기여하고 있습니다. 이처럼, 현대차·기아는 실시간으로 변동하는 시장 환경에 발 빠르게 대응하며, 전기차 시장에서의 우위를 지속적으로 확보하고 있습니다.\n\n*   ### 3-3. 전기차 모델 출시 계획\n\n*   현대차·기아는 미국 시장에 맞춘 다양한 전기차 모델을 출시할 계획입니다. 기아는 EV9과 더불어 EV3, EV4 모델을 연내에 출시할 예정이며, 이러한 모델들은 소비자들에게 다양한 차급과 가격대의 선택지를 제공합니다. 이와 함께, 현대차는 아이오닉7을 출시하여 세 번째 전기차 전용 플랫폼을 적용한 모델로 시장에 도입할 계획입니다.\n\n*   이러한 다양한 모델 출시는 시장 내 경쟁력을 높이는 데 중요한 요소로 작용할 것입니다. 특히, 소비자들이 선호하는 느낌의 SUV와 크로스오버 모델 중심으로 라인업을 강화함으로써, 현대차·기아의 전기차 제품군은 더욱 다양해질 것입니다. 이러한 전략적 접근은 변화하는 트렌드에 맞춰 전기차에 대한 소비자의 수요를 극대화하고, 향후 성장 가능성을 더욱 높일 수 있을 것입니다.\n\n4. 하이브리드 시장의 급성장과 현대차·기아의 대응\n----------------------------\n\n*   ### 4-1. 미국 하이브리드 시장 성장 추세\n\n*   미국 하이브리드 자동차 시장은 최근 몇 년간 눈에 띄는 성장세를 보여줍니다. 2022년에는 전체 자동차 판매량 중 하이브리드 차량의 비중이 5%에서 8%로 상승하였고, 2023년에는 하이브리드의 판매 증가율이 71.3%에 달했습니다. 이는 지난해 1분기 전기차 판매 증가율이 62.6%에서 4분기에는 27.2%로 둔화된 것과 대조적입니다. 하이브리드는 이제 소비자들에게 친환경성과 연비를 제공하는 매력적인 대안으로 각광받고 있으며, 현대차·기아는 이러한 트렌드를 활용하여 시장 점유율을 확대하고 있습니다.\n\n*   ### 4-2. 경쟁 업체 분석 및 대비 전략\n\n*   현대차·기아는 미국 시장의 하이브리드 판매 증가에 대응하기 위해 다양한 전략을 수립 중입니다. 특히, 경쟁 업체들이 전기차에 집중하는 동안 하이브리드차량의 수요가 증가하고 있는 점을 주목하고 있습니다. 현대차는 투싼 HEV와 엘란트라 HEV 모델을 통해 각각 23.5%와 23.7%의 판매 증가를 기록하였으며, 기아는 쏘렌토 HEV와 스포티지 HEV에서 각각 81.9%와 76.4%의 기록적인 판매 증가를 보였습니다. 이러한 성과는 현대차·기아가 하이브리드 시스템을 한층 강화하고 있어 가능해진 결과입니다.\n\n*   ### 4-3. 2025년 판매 목표 및 예상\n\n*   현대차·기아는 2025년 동안 하이브리드 모델의 판매를 더욱 확대할 계획입니다. 특히, '디 올 뉴 싼타페 하이브리드'가 출시되면서 기대되는 판매량 증가가 주효할 것으로 예상됩니다. 이 모델은 1.6리터 직분사 터보차지 하이브리드를 탑재하여 최고출력 232마치를 제공하며, 우수한 연비를 자랑하여 소비자들의 호응을 얻을 것으로 보입니다. 또한, 현대차그룹은 기존의 전동화 생산라인을 활용하여 전기차와 하이브리드차를 동시에 생산할 수 있는 체계를 갖추고 있어, 급증하는 하이브리드 수요에 유연하게 대응할 수 있을 것입니다.\n\n5. 향후 전망 및 결론\n-------------\n\n*   ### 5-1. 미국 자동차 시장의 변화\n\n*   미국 자동차 시장은 지속적으로 변화하고 있으며, 이러한 변화를 주도하는 주요 요소 중 하나는 소비자들의 친환경 차량에 대한 선호도 증가입니다. 특히 전기차와 하이브리드 차량의 수요가 증가하며, 이로 인해 자동차 제조사들은 더욱 혁신적인 기술 개발과 다양한 모델 출시를 통해 시장 점유율을 늘리기 위해 노력하고 있습니다. 현대차·기아는 이러한 시장 변화에 효과적으로 대응하기 위해 전기차와 하이브리드 모델의 생산 및 판매 확대에 집중하고 있습니다.\n\n*   또한, 인플레이션 감축법(IRA)과 같은 정책적 요소도 시장에 큰 영향을 미치고 있습니다. 이 법안은 미국 내 전기차 생산을 증대시키고, 해외 제조업체들이 시장에 진입하기 위한 다양한 인센티브를 제공함으로써 미국 시장의 경쟁 상황을 변화시키고 있습니다. 현대차·기아가 이에 맞춰 미국 내 생산기지를 확장하는 전략은 이러한 시장 변화에 부합하며, 앞으로의 성장은 더욱 가속화될 것으로 예상됩니다.\n\n*   ### 5-2. 현대차·기아의 지속 가능한 성장 전략\n\n*   현대차·기아는 지속 가능한 성장을 위해 친환경 차량 개발에 대한 투자를 지속하고 있으며, 이는 단순히 시장에서의 점유율을 높이는 것을 넘어 환경 보호를 위한 고유한 책임을 다하기 위한 노력이라고 할 수 있습니다. 이들은 특히 하이브리드 차량의 라인업을 확장하고, 향후 출시될 차량에 고성능 하이브리드 시스템을 적용하여 연비 성능을 획기적으로 개선할 계획입니다.\n\n*   하이브리드 모델 시장의 급성장과 관련하여, 현대차·기아는 이미 시장의 요구에 맞춰 다양한 하이브리드 모델을 출시하고 있으며, 이러한 모델들은 각각의 소비자 요구에 부응하고 있습니다. 디 올 뉴 싼타페 하이브리드와 같은 최신 모델의 경우, 성능과 효율성을 동시에 충족시켜 소비자들에게 긍정적인 반응을 얻고 있습니다.\n\n*   ### 5-3. 구매환경 변화에 따른 시장 대응\n\n*   소비자의 구매환경은 급속도로 변화하고 있으며, 이는 자동차 산업에도 직접적인 영향을 미치고 있습니다. 특히 디지털화와 온라인 쇼핑의 확산으로 인해 소비자들은 더 많은 정보를 바탕으로 구매 결정을 내리고 있습니다. 현대차·기아는 이러한 소비자 트렌드에 맞춰 디지털 플랫폼을 구축하고 소비자와의 소통을 강화하는 방안을 마련하고 있습니다.\n\n*   또한, 소비자들이 친환경 차량을 고려할 때 주요하게 생각하는 사항 중 하나는 가격과 비용입니다. 현대차·기아는 전기차 및 하이브리드 차량의 가격 경쟁력을 높이기 위해 생산 공정의 효율성을 극대화하고, 안정적인 부품 공급망을 구축함으로써 최종 소비자에게 보다 합리적인 가격을 제공할 수 있도록 힘쓰고 있습니다. 이러한 노력들은 향후 시장 전망에 긍정적인 영향을 미칠 것으로 보입니다.\n\n결론\n--\n\n*   2025년 미국 자동차 시장에서 현대차·기아는 전기차와 하이브리드 시장에서의 리더십 강화를 위해 지속적인 혁신과 성장 전략을 구사하고 있습니다. 소비자들이 친환경 차량에 대한 선호도를 높이고 있는 가운데, 현대차·기아는 이들의 기대에 부응하기 위해 전기차와 하이브리드 차량의 생산 및 판매 확대에 주력하고 있습니다. 인플레이션 감축법(IRA)과 같은 정책적 변화에도 발 빠르게 대응하며, 현지 생산 비율을 높여 경쟁력을 유지하는 동시에, 소비자들에게 보다 합리적인 가격을 제공할 수 있는 노력을 지속하고 있습니다.\n\n*   또한, 현대차·기아는 하이브리드 모델의 라인업을 확장하며 다양한 소비자 요구에 부합하는 제품 개발에 힘쓰고 있습니다. 더욱이, 디지털화를 통해 소비자와의 소통을 강화하고 정보 접근성을 높여 구매 환경의 변화에 적응하고 있습니다. 이러한 종합적인 접근은 현대차·기아의 지속 가능한 성장 전략의 핵심이며, 향후 자동차 산업의 생태계가 변화하는 과정에서 중요한 역할을 하게 될 것입니다. 결국 현대차·기아의 지속 가능한 성장 전략은 기업의 비전과 맞물려 더 나은 환경을 만들어 가는 데 기여할 것으로 기대됩니다.\n\n용어집\n---\n\n*   인플레이션 감축법(IRA) [법률]: 미국 연방 정부가 환경 친화적인 자동차 구매를 장려하기 위해 시행한 법률로, 소비자에게 세액 공제를 제공합니다.\n\n*   전기차(BEV) [차량 유형]: 물리적인 연료가 아닌 전기를 통해 추진되는 자동차로, 배기가스를 발생하지 않는 친환경 차량입니다.\n\n*   하이브리드(HEV) [차량 유형]: 내연기관과 전기모터를 결합하여 구동되는 자동차로, 연비와 친환경성을 동시에 갖춘 차량입니다.\n\n*   혼류생산 방식 [생산 방식]: 두 가지 이상의 제품을 동일한 생산라인에서 동시에 제조하는 방식으로, 제조 효율성을 높이기 위한 전략입니다.\n\n*   소매 판매 [판매 방식]: 최종 소비자에게 직접 차량을 판매하는 방식을 의미하며, 자동차 업계에서 주로 사용되는 판매 통계입니다.\n\n*   전동화 [기술]: 전기 모터와 배터리를 사용하는 자동차 기술로, 연료 효율성 및 친환경성을 증대시키는 방향으로 발전하고 있습니다.\n\n*   디지털화 [트렌드]: 소비자의 구매 결정 과정에서 정보 접근과 편리함을 제공하기 위해 디지털 플랫폼을 활용하는 과정입니다.\n\n출처 문서\n\n*   **현대차·기아, 올해도 美시장 '정조준'…사상최대 실적 자신**[https://www.fnnews.com/news/202401301512192620](https://www.fnnews.com/news/202401301512192620)\n*   **현대차·기아, 美현지 전기차 생산 본격화..“악재뚫고 질주”**[http://www.edaily.co.kr/news/newspath.asp?newsid=03742486638758704](http://www.edaily.co.kr/news/newspath.asp?newsid=03742486638758704)\n*   **현대차·기아, 美 하이브리드 시장 공략**[https://www.asiatoday.co.kr/view.php?key=20240110010006578](https://www.asiatoday.co.kr/view.php?key=20240110010006578)\n*   **현대차·기아, 급성장하는 미국 하이브리드 시장 정조준**[https://www.asiatoday.co.kr/view.php?key=20240110010006679](https://www.asiatoday.co.kr/view.php?key=20240110010006679)\n"},
 {'url': 'https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/',
  'title': '현대차 미국 법인, 2025년 2월 역대 최고 판매 기록 달성',
  'content': '현대자동차 미국 법인(Hyundai Motor America)이 2025년 2월 총 62,032대의 차량을 판매하며 전년 동월 대비 3% 증가한 역대 최고 2월 판매 실적을 기록했다. 이는 현대차 역사상 가장 높은 2월 판매량이며, 5개월 연속 최고 판매 기록을 경신한 성과다.\n\n특히 산타페 HEV(+194%), 투싼(+2%), 아이오닉 6(+12%)가 2월 역대 최고 판매량을 기록했다.\n\n하이브리드 전기차(HEV) 판매량은 57% 증가했으며, 전기차(EV) 판매량도 6% 상승했다.\n\n현대차 북미 법인 CEO 랜디 파커(Randy Parker)는 다음과 같이 밝혔다.\n\n> _“이번 2월은 현대차의 총판매량에서 역대 최고의 기록을 세운 달이었으며,\n> \n> 투싼을 중심으로 전기차와 하이브리드 차량의 성장이 계속되고 있습니다.\n> \n> 우리의 강력하고 다양한 제품 라인업이 시장 점유율 확대와 고객 수요 충족을\n> \n> 더욱 견인할 것으로 기대합니다.”_ [...] | 차종 | Feb-25 | Feb-24 | 증감률 | 2025 YTD | 2024 YTD | 증감률 |\n| --- | --- | --- | --- | --- | --- | --- |\n| 엘란트라(Elantra) | 10,163 | 8,432 | +21% | 19,029 | 15,332 | +24% |\n| 아이오닉 5 (Ioniq 5) | 2,442 | 1,996 | +22% | 4,692 | 3,461 | +36% |\n| 아이오닉 6 (Ioniq 6) | 1,012 | 902 | +12% | 1,883 | 1,662 | +13% |\n| 코나(Kona) | 5,629 | 7,024 | -20% | 9,994 | 13,601 | -27% |\n| 넥쏘(Nexo) | 0 | 11 | -100% | 0 | 34 | -100% |\n| 팰리세이드(Palisade) | 7,806 | 7,832 | -0% | 14,493 | 15,470 | -6% | [...] | 산타크루즈(Santa Cruz) | 1,938 | 2,568 | -25% | 3,724 | 5,055 | -26% |\n| 산타페(Santa Fe) | 9,562 | 9,239 | +3% | 17,858 | 15,260 | +17% |\n| 쏘나타(Sonata) | 5,334 | 4,379 | +22% | 10,091 | 7,500 | +35% |\n| 투싼(Tucson) | 16,317 | 15,999 | +2% | 31,342 | 27,115 | +16% |\n| 베뉴(Venue) | 1,829 | 1,959 | -7% | 3,429 | 3,394 | +1% |',
  'score': 0.84767824,
  'raw_content': 'Published Time: 2025-03-01T23:13:38+00:00\n\n현대차 미국 법인, 2025년 2월 역대 최고 판매 기록 달성 - 서배너 코리안 타임즈 | Savannah Korean Times\n\n===============\n\n[![Image 1: 서배너 코리안 타임즈 | Savannah Korean Times](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_500,h_127/https://savannahkoreatimes.com/wp-content/uploads/2025/05/%ED%81%AC%EA%B8%B0%EB%B3%80%ED%99%98%ED%81%AC%EA%B8%B0%EB%B3%80%ED%99%9820250503_114844.png)](https://savannahkoreatimes.com/)\n\n[](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#)\n\n*   [홈](https://savannahkoreatimes.com/)\n*   [최신뉴스](https://savannahkoreatimes.com/category/%ec%b5%9c%ec%8b%a0%eb%89%b4%ec%8a%a4/)\n*   [로컬](https://savannahkoreatimes.com/category/%eb%a1%9c%ec%bb%ac/)\n*   [미국 / 국제](https://savannahkoreatimes.com/category/%eb%af%b8%ea%b5%ad-%ea%b5%ad%ec%a0%9c/)\n*   [한국뉴스](https://savannahkoreatimes.com/category/%ed%95%9c%ea%b5%ad%eb%89%b4%ec%8a%a4/)\n*   [경제](https://savannahkoreatimes.com/category/%ea%b2%bd%ec%a0%9c/)\n*   [정치](https://savannahkoreatimes.com/category/%ec%a0%95%ec%b9%98/)\n*   [사회](https://savannahkoreatimes.com/category/%ec%82%ac%ed%9a%8c/)\n*   [연예](https://savannahkoreatimes.com/category/%ec%97%b0%ec%98%88/)\n*   [산업 / IT / 과학](https://savannahkoreatimes.com/category/%ec%82%b0%ec%97%85-it-%ea%b3%bc%ed%95%99/)\n*   [스포츠](https://savannahkoreatimes.com/category/%ec%8a%a4%ed%8f%ac%ec%b8%a0/)\n*   [건강](https://savannahkoreatimes.com/category/%ea%b1%b4%ea%b0%95/)\n*   [컬럼](https://savannahkoreatimes.com/category/%ec%bb%ac%eb%9f%bc/)\n*   [알림](https://savannahkoreatimes.com/category/%ec%95%8c%eb%a6%bc/)\n\n[](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#)\n\n No Result\n\n View All Result\n\n[](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#)\n\n*   [홈](https://savannahkoreatimes.com/)\n*   [최신뉴스](https://savannahkoreatimes.com/category/%ec%b5%9c%ec%8b%a0%eb%89%b4%ec%8a%a4/)\n*   [로컬](https://savannahkoreatimes.com/category/%eb%a1%9c%ec%bb%ac/)\n*   [미국 / 국제](https://savannahkoreatimes.com/category/%eb%af%b8%ea%b5%ad-%ea%b5%ad%ec%a0%9c/)\n*   [한국뉴스](https://savannahkoreatimes.com/category/%ed%95%9c%ea%b5%ad%eb%89%b4%ec%8a%a4/)\n*   [경제](https://savannahkoreatimes.com/category/%ea%b2%bd%ec%a0%9c/)\n*   [정치](https://savannahkoreatimes.com/category/%ec%a0%95%ec%b9%98/)\n*   [사회](https://savannahkoreatimes.com/category/%ec%82%ac%ed%9a%8c/)\n*   [연예](https://savannahkoreatimes.com/category/%ec%97%b0%ec%98%88/)\n*   [산업 / IT / 과학](https://savannahkoreatimes.com/category/%ec%82%b0%ec%97%85-it-%ea%b3%bc%ed%95%99/)\n*   [스포츠](https://savannahkoreatimes.com/category/%ec%8a%a4%ed%8f%ac%ec%b8%a0/)\n*   [건강](https://savannahkoreatimes.com/category/%ea%b1%b4%ea%b0%95/)\n*   [컬럼](https://savannahkoreatimes.com/category/%ec%bb%ac%eb%9f%bc/)\n*   [알림](https://savannahkoreatimes.com/category/%ec%95%8c%eb%a6%bc/)\n\n[](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#)\n\n No Result\n\n View All Result\n\n[](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#)\n\n[![Image 2: 서배너 코리안 타임즈 | Savannah Korean Times](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_500,h_127/https://savannahkoreatimes.com/wp-content/uploads/2025/05/%ED%81%AC%EA%B8%B0%EB%B3%80%ED%99%98%ED%81%AC%EA%B8%B0%EB%B3%80%ED%99%9820250503_114844.png)](https://savannahkoreatimes.com/)\n\n[](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#)\n\n No Result\n\n View All Result\n\n*   [홈](https://savannahkoreatimes.com/)\n*   [최신뉴스](https://savannahkoreatimes.com/category/%ec%b5%9c%ec%8b%a0%eb%89%b4%ec%8a%a4/)\n*   [로컬](https://savannahkoreatimes.com/category/%eb%a1%9c%ec%bb%ac/)\n*   [미국 / 국제](https://savannahkoreatimes.com/category/%eb%af%b8%ea%b5%ad-%ea%b5%ad%ec%a0%9c/)\n*   [한국뉴스](https://savannahkoreatimes.com/category/%ed%95%9c%ea%b5%ad%eb%89%b4%ec%8a%a4/)\n*   [경제](https://savannahkoreatimes.com/category/%ea%b2%bd%ec%a0%9c/)\n*   [정치](https://savannahkoreatimes.com/category/%ec%a0%95%ec%b9%98/)\n*   [사회](https://savannahkoreatimes.com/category/%ec%82%ac%ed%9a%8c/)\n*   [연예](https://savannahkoreatimes.com/category/%ec%97%b0%ec%98%88/)\n*   [산업 / IT / 과학](https://savannahkoreatimes.com/category/%ec%82%b0%ec%97%85-it-%ea%b3%bc%ed%95%99/)\n*   [스포츠](https://savannahkoreatimes.com/category/%ec%8a%a4%ed%8f%ac%ec%b8%a0/)\n*   [건강](https://savannahkoreatimes.com/category/%ea%b1%b4%ea%b0%95/)\n*   [컬럼](https://savannahkoreatimes.com/category/%ec%bb%ac%eb%9f%bc/)\n*   [알림](https://savannahkoreatimes.com/category/%ec%95%8c%eb%a6%bc/)\n\n[Home](https://savannahkoreatimes.com/)[미국 / 국제](https://savannahkoreatimes.com/category/%eb%af%b8%ea%b5%ad-%ea%b5%ad%ec%a0%9c/)\n\n현대차 미국 법인, 2025년 2월 역대 최고 판매 기록 달성\n==================================\n\n전기차(EV) 판매량 6% 증가, 하이브리드(HEV) 판매량 57% 급증\n----------------------------------------\n\n![Image 3: 서배너코리안타임즈 | Savannah Korean Times](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_80,h_80/https://savannahkoreatimes.com/wp-content/uploads/2025/01/cropped-%EC%84%9C%EB%B0%B0%EB%84%88%EC%BD%94%EB%A6%AC%EC%95%88%ED%83%80%EC%9E%84%EC%A6%88-150x150.jpg)by[서배너코리안타임즈 | Savannah Korean Times](https://savannahkoreatimes.com/author/savannahtimesadmin/)\n\n[3월 1, 2025](https://savannahkoreatimes.com/%ed%98%84%eb%8c%80%ec%b0%a8-%eb%af%b8%ea%b5%ad-%eb%b2%95%ec%9d%b8-2025%eb%85%84-2%ec%9b%94-%ec%97%ad%eb%8c%80-%ec%b5%9c%ea%b3%a0-%ed%8c%90%eb%a7%a4-%ea%b8%b0%eb%a1%9d-%eb%8b%ac%ec%84%b1/)\n\nin[미국 / 국제](https://savannahkoreatimes.com/category/%eb%af%b8%ea%b5%ad-%ea%b5%ad%ec%a0%9c/), [산업 / IT / 과학](https://savannahkoreatimes.com/category/%ec%82%b0%ec%97%85-it-%ea%b3%bc%ed%95%99/), [최신뉴스](https://savannahkoreatimes.com/category/%ec%b5%9c%ec%8b%a0%eb%89%b4%ec%8a%a4/)\n\n Reading Time: 2 mins read \n\nA A\n\nA A Reset\n\n[![Image 4: 현대차 미국 법인, 2025년 2월 역대 최고 판매 기록 달성](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_682,h_375/https://savannahkoreatimes.com/wp-content/uploads/2025/03/hyundaicarsusa.com-682x375.png)](https://savannahkoreatimes.com/wp-content/uploads/2025/03/hyundaicarsusa.com.png)\n\n현대자동차 미국 법인(Hyundai Motor America)이 2025년 2월 총 62,032대의 차량을 판매하며 전년 동월 대비 3% 증가한 역대 최고 2월 판매 실적을 기록했다. 이는 현대차 역사상 가장 높은 2월 판매량이며, 5개월 연속 최고 판매 기록을 경신한 성과다.\n\n특히 산타페 HEV(+194%), 투싼(+2%), 아이오닉 6(+12%)가 2월 역대 최고 판매량을 기록했다.\n\n하이브리드 전기차(HEV) 판매량은 57% 증가했으며, 전기차(EV) 판매량도 6% 상승했다.\n\n현대차 북미 법인 CEO 랜디 파커(Randy Parker)는 다음과 같이 밝혔다.\n\n> _“이번 2월은 현대차의 총판매량에서 역대 최고의 기록을 세운 달이었으며,\n> \n> 투싼을 중심으로 전기차와 하이브리드 차량의 성장이 계속되고 있습니다.\n> \n> 우리의 강력하고 다양한 제품 라인업이 시장 점유율 확대와 고객 수요 충족을\n> \n> 더욱 견인할 것으로 기대합니다.”_\n\n* * *\n\n### **2025년 2월 총판매량 요약**\n\n|  | **Feb-25** | **Feb-24** | **증감률** | **2025년 YTD** | **2024년 YTD** | **증감률** |\n| --- | --- | --- | --- | --- | --- | --- |\n| **현대차 총 판매량** | **62,032** | **60,341** | **+3%** | **116,535** | **107,884** | **+8%** |\n\n### **2025년 2월 차종별 판매 실적**\n\n| **차종** | **Feb-25** | **Feb-24** | **증감률** | **2025 YTD** | **2024 YTD** | **증감률** |\n| --- | --- | --- | --- | --- | --- | --- |\n| **엘란트라(Elantra)** | 10,163 | 8,432 | +21% | 19,029 | 15,332 | +24% |\n| **아이오닉 5 (Ioniq 5)** | 2,442 | 1,996 | +22% | 4,692 | 3,461 | +36% |\n| **아이오닉 6 (Ioniq 6)** | 1,012 | 902 | +12% | 1,883 | 1,662 | +13% |\n| **코나(Kona)** | 5,629 | 7,024 | -20% | 9,994 | 13,601 | -27% |\n| **넥쏘(Nexo)** | 0 | 11 | -100% | 0 | 34 | -100% |\n| **팰리세이드(Palisade)** | 7,806 | 7,832 | -0% | 14,493 | 15,470 | -6% |\n| **산타크루즈(Santa Cruz)** | 1,938 | 2,568 | -25% | 3,724 | 5,055 | -26% |\n| **산타페(Santa Fe)** | 9,562 | 9,239 | +3% | 17,858 | 15,260 | +17% |\n| **쏘나타(Sonata)** | 5,334 | 4,379 | +22% | 10,091 | 7,500 | +35% |\n| **투싼(Tucson)** | 16,317 | 15,999 | +2% | 31,342 | 27,115 | +16% |\n| **베뉴(Venue)** | 1,829 | 1,959 | -7% | 3,429 | 3,394 | +1% |\n\n현대차는 전기차, 하이브리드, 내연기관 차량을 아우르는 다양한 포트폴리오를 통해 성장세를 이어갈 계획이다.\n\n![Image 5: 서배너코리안타임즈 | Savannah Korean Times](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_80,h_80/https://savannahkoreatimes.com/wp-content/uploads/2025/01/cropped-%EC%84%9C%EB%B0%B0%EB%84%88%EC%BD%94%EB%A6%AC%EC%95%88%ED%83%80%EC%9E%84%EC%A6%88-150x150.jpg)\n\n### [서배너코리안타임즈 | Savannah Korean Times](https://savannahkoreatimes.com/author/savannahtimesadmin/)\n\n[](http://savannahtimesdev.com/)\n\n### Related**Posts**\n\n[![Image 6: 조지아주, 정신건강 위기 대응센터 확장 추진](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_350,h_250/https://savannahkoreatimes.com/wp-content/themes/jnews/assets/img/jeg-empty.png)](https://savannahkoreatimes.com/%ed%8a%b8%eb%9f%bc%ed%94%84-%eb%8c%80%ed%86%b5%eb%a0%b9-%eb%af%b8%ea%b5%ad%ec%97%90-%eb%b9%84%ec%83%9d%ec%82%b0%ec%a0%81-%ea%b3%b5%ed%9c%b4%ec%9d%bc-%eb%84%88%eb%ac%b4-%eb%a7%8e%ec%95%84/)\n\n[미국 / 국제](https://savannahkoreatimes.com/category/%eb%af%b8%ea%b5%ad-%ea%b5%ad%ec%a0%9c/)\n\n### [트럼프 대통령 “미국에 비생산적 공휴일 너무 많아”… 준틴스 논란 재점화](https://savannahkoreatimes.com/%ed%8a%b8%eb%9f%bc%ed%94%84-%eb%8c%80%ed%86%b5%eb%a0%b9-%eb%af%b8%ea%b5%ad%ec%97%90-%eb%b9%84%ec%83%9d%ec%82%b0%ec%a0%81-%ea%b3%b5%ed%9c%b4%ec%9d%bc-%eb%84%88%eb%ac%b4-%eb%a7%8e%ec%95%84/)\n\n[6월 19, 2025](https://savannahkoreatimes.com/%ed%8a%b8%eb%9f%bc%ed%94%84-%eb%8c%80%ed%86%b5%eb%a0%b9-%eb%af%b8%ea%b5%ad%ec%97%90-%eb%b9%84%ec%83%9d%ec%82%b0%ec%a0%81-%ea%b3%b5%ed%9c%b4%ec%9d%bc-%eb%84%88%eb%ac%b4-%eb%a7%8e%ec%95%84/)\n\n[![Image 7: 조지아주, 정신건강 위기 대응센터 확장 추진](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_350,h_250/https://savannahkoreatimes.com/wp-content/themes/jnews/assets/img/jeg-empty.png)](https://savannahkoreatimes.com/%eb%a9%b4%eb%8f%84%eb%82%a0-%ec%82%bc%ed%82%a4%eb%8a%94-%eb%93%af%ed%95%9c-%eb%aa%a9%ea%b0%90%ea%b8%b0-%ec%9c%a0%eb%b0%9c%ed%95%98%eb%8a%94-%ec%83%88-%ec%bd%94%eb%a1%9c%eb%82%98/)\n\n[건강](https://savannahkoreatimes.com/category/%ea%b1%b4%ea%b0%95/)\n\n### [‘면도날 삼키는 듯한 목감기’ 유발하는 새 코로나 변이, 전 세계 확산 조짐](https://savannahkoreatimes.com/%eb%a9%b4%eb%8f%84%eb%82%a0-%ec%82%bc%ed%82%a4%eb%8a%94-%eb%93%af%ed%95%9c-%eb%aa%a9%ea%b0%90%ea%b8%b0-%ec%9c%a0%eb%b0%9c%ed%95%98%eb%8a%94-%ec%83%88-%ec%bd%94%eb%a1%9c%eb%82%98/)\n\n[6월 19, 2025](https://savannahkoreatimes.com/%eb%a9%b4%eb%8f%84%eb%82%a0-%ec%82%bc%ed%82%a4%eb%8a%94-%eb%93%af%ed%95%9c-%eb%aa%a9%ea%b0%90%ea%b8%b0-%ec%9c%a0%eb%b0%9c%ed%95%98%eb%8a%94-%ec%83%88-%ec%bd%94%eb%a1%9c%eb%82%98/)\n\n[![Image 8: 조지아주, 정신건강 위기 대응센터 확장 추진](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_350,h_250/https://savannahkoreatimes.com/wp-content/themes/jnews/assets/img/jeg-empty.png)](https://savannahkoreatimes.com/%ec%a1%b0%ec%a7%80%ec%95%84%ec%a3%bc-%ec%a0%95%ec%8b%a0%ea%b1%b4%ea%b0%95-%ec%9c%84%ea%b8%b0-%eb%8c%80%ec%9d%91%ec%84%bc%ed%84%b0-%ed%99%95%ec%9e%a5-%ec%b6%94%ec%a7%84/)\n\n[Savannah / 서배너로컬 / 지역](https://savannahkoreatimes.com/category/savannah-%ec%84%9c%eb%b0%b0%eb%84%88%eb%a1%9c%ec%bb%ac-%ec%a7%80%ec%97%ad/)\n\n### [조지아주, 정신건강 위기 대응센터 확장 추진](https://savannahkoreatimes.com/%ec%a1%b0%ec%a7%80%ec%95%84%ec%a3%bc-%ec%a0%95%ec%8b%a0%ea%b1%b4%ea%b0%95-%ec%9c%84%ea%b8%b0-%eb%8c%80%ec%9d%91%ec%84%bc%ed%84%b0-%ed%99%95%ec%9e%a5-%ec%b6%94%ec%a7%84/)\n\n[6월 19, 2025](https://savannahkoreatimes.com/%ec%a1%b0%ec%a7%80%ec%95%84%ec%a3%bc-%ec%a0%95%ec%8b%a0%ea%b1%b4%ea%b0%95-%ec%9c%84%ea%b8%b0-%eb%8c%80%ec%9d%91%ec%84%bc%ed%84%b0-%ed%99%95%ec%9e%a5-%ec%b6%94%ec%a7%84/)\n\nNext Post\n\n[![Image 9: 교육부 직원들, 월요일까지 최대 2만 5천 달러 퇴직금 제안받아](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_75,h_75/https://savannahkoreatimes.com/wp-content/themes/jnews/assets/img/jeg-empty.png)](https://savannahkoreatimes.com/%e7%be%8e-1%ec%9b%94-%eb%ac%b4%ec%97%ad%ec%a0%81%ec%9e%90-1530%ec%96%b5-%eb%8b%ac%eb%9f%ac-%ea%b8%b0%eb%a1%9d-%ec%82%ac%ec%83%81-%ec%b5%9c%eb%8c%80/)\n\n### [美 1월 무역적자, 1530억 달러 기록 \'사상 최대\'](https://savannahkoreatimes.com/%e7%be%8e-1%ec%9b%94-%eb%ac%b4%ec%97%ad%ec%a0%81%ec%9e%90-1530%ec%96%b5-%eb%8b%ac%eb%9f%ac-%ea%b8%b0%eb%a1%9d-%ec%82%ac%ec%83%81-%ec%b5%9c%eb%8c%80/)\n\n[![Image 10: 교육부 직원들, 월요일까지 최대 2만 5천 달러 퇴직금 제안받아](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_75,h_75/https://savannahkoreatimes.com/wp-content/themes/jnews/assets/img/jeg-empty.png)](https://savannahkoreatimes.com/%eb%af%b8%ea%b5%ad-%ea%b8%b0%eb%8f%85%ea%b5%90%ec%9d%b8-%eb%b9%84%ec%9c%a8-16%eb%85%84%ea%b0%84-%ed%95%98%eb%9d%bd%ec%84%b8-%eb%a9%88%ec%b6%94%ea%b3%a0-63%eb%a1%9c-%ec%95%88%ec%a0%95%ed%99%94/)\n\n### [미국 기독교인 비율, 16년간 하락세 멈추고 63%로 안정화](https://savannahkoreatimes.com/%eb%af%b8%ea%b5%ad-%ea%b8%b0%eb%8f%85%ea%b5%90%ec%9d%b8-%eb%b9%84%ec%9c%a8-16%eb%85%84%ea%b0%84-%ed%95%98%eb%9d%bd%ec%84%b8-%eb%a9%88%ec%b6%94%ea%b3%a0-63%eb%a1%9c-%ec%95%88%ec%a0%95%ed%99%94/)\n\n[![Image 11: 교육부 직원들, 월요일까지 최대 2만 5천 달러 퇴직금 제안받아](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_75,h_75/https://savannahkoreatimes.com/wp-content/themes/jnews/assets/img/jeg-empty.png)](https://savannahkoreatimes.com/%ea%b5%90%ec%9c%a1%eb%b6%80-%ec%a7%81%ec%9b%90%eb%93%a4-%ec%9b%94%ec%9a%94%ec%9d%bc%ea%b9%8c%ec%a7%80-%ec%b5%9c%eb%8c%80-2%eb%a7%8c-5%ec%b2%9c-%eb%8b%ac%eb%9f%ac-%ed%87%b4%ec%a7%81%ea%b8%88-%ec%a0%9c/)\n\n### [교육부 직원들, 월요일까지 최대 2만 5천 달러 퇴직금 제안받아](https://savannahkoreatimes.com/%ea%b5%90%ec%9c%a1%eb%b6%80-%ec%a7%81%ec%9b%90%eb%93%a4-%ec%9b%94%ec%9a%94%ec%9d%bc%ea%b9%8c%ec%a7%80-%ec%b5%9c%eb%8c%80-2%eb%a7%8c-5%ec%b2%9c-%eb%8b%ac%eb%9f%ac-%ed%87%b4%ec%a7%81%ea%b8%88-%ec%a0%9c/)\n\n[](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#)\n\n[![Image 12](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_338,h_180/https://savannahkoreatimes.com/wp-content/uploads/2025/01/unnamed-4.jpg)](https://blog.naver.com/insook0415)\n\n[![Image 13](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_2173,h_953/https://savannahkoreatimes.com/wp-content/uploads/2025/01/1738110349596.jpg)](https://cuckoorental.com/ko?gad_source=1&gclid=CjwKCAiAneK8BhAVEiwAoy2HYRBdT1m1qOkUqIW6Z86XNr6pnEuBBFrGz1KP11obRed2iD2-mZIAWRoCeU0QAvD_BwE)\n\n![Image 14](https://savannahkoreatimes.com/wp-content/uploads/2024/11/%EB%8D%B8%ED%83%80-%EC%82%AC%EC%9A%B0%EC%8A%A4-%EA%B1%B4%EC%84%A4.svg)\n\n[![Image 15](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_2164,h_956/https://savannahkoreatimes.com/wp-content/uploads/2025/03/KakaoTalk_20250309_195517548.jpg)](https://h2hsavannah.com/)\n\n[![Image 16](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_2166,h_953/https://savannahkoreatimes.com/wp-content/uploads/2025/05/1747173340910.jpg)](https://www.mdchealthcare.org/)\n\n![Image 17](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_2166,h_947/https://savannahkoreatimes.com/wp-content/uploads/2025/04/KakaoTalk_20250405_182001930.jpg)\n\n[![Image 18](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_1756,h_853/https://savannahkoreatimes.com/wp-content/uploads/2025/01/KakaoTalk_20250114_212747928-1.jpg)](https://cnjbusiness.com/)\n\n[![Image 19](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_2164,h_947/https://savannahkoreatimes.com/wp-content/uploads/2025/01/unnamed-7.jpg)](https://goodratehomeloan.com/)\n\n[![Image 20](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_2163,h_963/https://savannahkoreatimes.com/wp-content/uploads/2025/01/unnamed-9.jpg)](https://www.jwleelaw.com/)\n\n[![Image 21](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_2560,h_1280/https://savannahkoreatimes.com/wp-content/uploads/2025/02/%EC%84%9C%EB%B0%B0%EB%84%88-%EC%95%A8%EB%9F%AC%EB%B0%B0%EB%A7%88-%EB%A1%9C%EA%B3%A0-1-scaled.jpg)](https://alabamakoreantimes.com/)\n\n*   [홈](https://savannahkoreatimes.com/)\n*   [최신뉴스](https://savannahkoreatimes.com/category/%ec%b5%9c%ec%8b%a0%eb%89%b4%ec%8a%a4/)\n*   [로컬](https://savannahkoreatimes.com/category/%eb%a1%9c%ec%bb%ac/)\n*   [미국 / 국제](https://savannahkoreatimes.com/category/%eb%af%b8%ea%b5%ad-%ea%b5%ad%ec%a0%9c/)\n*   [한국뉴스](https://savannahkoreatimes.com/category/%ed%95%9c%ea%b5%ad%eb%89%b4%ec%8a%a4/)\n*   [경제](https://savannahkoreatimes.com/category/%ea%b2%bd%ec%a0%9c/)\n*   [정치](https://savannahkoreatimes.com/category/%ec%a0%95%ec%b9%98/)\n*   [사회](https://savannahkoreatimes.com/category/%ec%82%ac%ed%9a%8c/)\n*   [연예](https://savannahkoreatimes.com/category/%ec%97%b0%ec%98%88/)\n*   [산업 / IT / 과학](https://savannahkoreatimes.com/category/%ec%82%b0%ec%97%85-it-%ea%b3%bc%ed%95%99/)\n*   [스포츠](https://savannahkoreatimes.com/category/%ec%8a%a4%ed%8f%ac%ec%b8%a0/)\n*   [건강](https://savannahkoreatimes.com/category/%ea%b1%b4%ea%b0%95/)\n*   [컬럼](https://savannahkoreatimes.com/category/%ec%bb%ac%eb%9f%bc/)\n*   [알림](https://savannahkoreatimes.com/category/%ec%95%8c%eb%a6%bc/)\n\n**광고문의: savannaktimes@gmail.com (470)843-6822**\n\n© 2025 [서배너 코리안 타임즈](http://jegtheme.com/ "Premium WordPress news & magazine theme") - [The Savannah Korean Times](http://www.savannahkoreatimes.com/ "Jegtheme").\n\n[](https://www.facebook.com/jegtheme/)[](https://twitter.com/jegtheme)[](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#)[](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#)\n\n[](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#back-to-top)\n\n### Welcome Back!\n\nLogin to your account below\n\n- [x] Remember Me\n\n[Forgotten Password?](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#jeg_forgotform)[Sign Up](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#jeg_registerform)\n\n### Create New Account!\n\nFill the forms bellow to register\n\nAll fields are required.[Log In](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#jeg_loginform)\n\n### Retrieve your password\n\nPlease enter your username or email address to reset your password.\n\n[Log In](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#jeg_loginform)\n\n### Add New Playlist\n\n[](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#)\n\n[](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#)\n\n No Result\n\n View All Result\n\n*   [홈](https://savannahkoreatimes.com/)\n*   [최신뉴스](https://savannahkoreatimes.com/category/%ec%b5%9c%ec%8b%a0%eb%89%b4%ec%8a%a4/)\n*   [로컬](https://savannahkoreatimes.com/category/%eb%a1%9c%ec%bb%ac/)\n*   [미국 / 국제](https://savannahkoreatimes.com/category/%eb%af%b8%ea%b5%ad-%ea%b5%ad%ec%a0%9c/)\n*   [한국뉴스](https://savannahkoreatimes.com/category/%ed%95%9c%ea%b5%ad%eb%89%b4%ec%8a%a4/)\n*   [경제](https://savannahkoreatimes.com/category/%ea%b2%bd%ec%a0%9c/)\n*   [정치](https://savannahkoreatimes.com/category/%ec%a0%95%ec%b9%98/)\n*   [사회](https://savannahkoreatimes.com/category/%ec%82%ac%ed%9a%8c/)\n*   [연예](https://savannahkoreatimes.com/category/%ec%97%b0%ec%98%88/)\n*   [산업 / IT / 과학](https://savannahkoreatimes.com/category/%ec%82%b0%ec%97%85-it-%ea%b3%bc%ed%95%99/)\n*   [스포츠](https://savannahkoreatimes.com/category/%ec%8a%a4%ed%8f%ac%ec%b8%a0/)\n*   [건강](https://savannahkoreatimes.com/category/%ea%b1%b4%ea%b0%95/)\n*   [컬럼](https://savannahkoreatimes.com/category/%ec%bb%ac%eb%9f%bc/)\n*   [알림](https://savannahkoreatimes.com/category/%ec%95%8c%eb%a6%bc/)\n\n[](https://www.facebook.com/jegtheme/)[](https://twitter.com/jegtheme)[](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#)[](https://savannahkoreatimes.com/%ED%98%84%EB%8C%80%EC%B0%A8-%EB%AF%B8%EA%B5%AD-%EB%B2%95%EC%9D%B8-2025%EB%85%84-2%EC%9B%94-%EC%97%AD%EB%8C%80-%EC%B5%9C%EA%B3%A0-%ED%8C%90%EB%A7%A4-%EA%B8%B0%EB%A1%9D-%EB%8B%AC%EC%84%B1/#)\n\n© 2025 [서배너 코리안 타임즈](http://jegtheme.com/ "Premium WordPress news & magazine theme") - [The Savannah Korean Times](http://www.savannahkoreatimes.com/ "Jegtheme").\n\n##### Are you sure want to unlock this post?\n\nUnlock left : 0 Yes No\n\n##### Are you sure want to cancel subscription?\n\nYes No\n\n![Image 22](https://pixel.wp.com/g.gif?v=ext&blog=219185719&post=27339&tz=-4&srv=savannahkoreatimes.com&j=1%3A14.7&host=savannahkoreatimes.com&ref=&fcp=1000&rand=0.09486989675777635)\n'},
 {'url': 'https://www.irsglobal.com/bbs/rwdboard/25706',
  'title': '미국 자동차 시장 : 자동차의 성장과 2025년 전망',
  'content': '2025 년에는 정책 전환 및 경쟁 환경의 변화로 인해 각 기업이 다양한 전략을 모색할 필요성이 있다.\n\n특히 BEV 의 성장을 내다보는 장기적인 투자와 단기적으로 수요가 높은 HEV 및 ICEV 에 대응하는 유연한 접근방식이 경쟁 우위성을 확보하는 열쇠가 될 것이다.\n\n소비자의 다양한 니즈를 정확하게 간파하면서 제품 및 서비스를 균형 있게 전개해야 한다.\n\n이것은 쉬운 과제는 아니지만, 시장 및 데이터와의 지속적인 대화를 통해 적절한 판단을 내리는 것이 성공을 위한 필수 요소라 할 수 있다.\n\n[2025년 국내외 미래자동차 관련 유망 기술, 시장 동향과 사업화 전략]보고서 상세 보기\n\nImage 12)\n\n게시글 공유URL복사\n\n출력)\n\n목록\n\n_prev_이전글수소 사업에 주력 : SK, 현대자동차, 포스코)_next_다음글중국 Zeekr가 테슬라・BYD를 추격 : 신흥 EV ‘3가지 강점’)\n\n   검색\n\n게시물 검색 검색 [...] Image 4: 상품 리스트 상단 아이콘   4차산업\n\n   검색\n\n게시물 검색 검색\n\n자동차/로봇 미국 자동차 시장 : 자동차의 성장과 2025년 전망\n====================================\n\n   관리자(irsglobal1)\n   2025-02-25 14:50:00\n   _hit_ 7090\n   121.173.47.139\n\n출처 :\n\n2024 년의 미국 자동차 시장은 전기차(BEV, HEV)가 착실하게 성장한 한편 ICEV(내연기관차)가 여전히 시장의 중심을 이루었다. 기업에 있어서는 다양한 소비자 니즈에 대응하는 전략이 중요하다.\n\n이 기사에서는 최신 데이터를 바탕으로 2024 년의 동향을 되돌아보고, 2025 년에 예상되는 시장 변화를 분석한다.\n\n2024 년 미국 자동차 시장 : 전기차(BEV, HEV)의 판매 동향 [...] ICT/정보통신\n       우주/항공/자동차/로봇\n       에너지/환경\n       신소재/부품\n       바이오/헬스케어/의료\n       화장품/식품\n       기타\n       4차산업\n\n   메일링 서비스\n\n       메일링 구독 신청\n       메일링 구독 취소\n\n   고객센터\n\n       공지사항\n       자료실\n       문의게시판\n       PDF 구매 안내\n\n로그인\n======================================\n\n   로그인\n   회원가입\n   장바구니\n   비회원 배송조회\n\nClose',
  'score': 0.758958,
  'raw_content': '미국 자동차 시장 : 자동차의 성장과 2025년 전망\n\n===============\n\n[![Image 1](https://www.irsglobal.com/img_up/shop_pds/irsglobal1/site_content/top_logo1509604762.png)](https://www.irsglobal.com/main)\n======================================================================================================================================\n\nToggle Left Side Toggle Right Side\n\n*   [고객센터](https://www.irsglobal.com/bbs/board1)\n*   [배송조회](https://www.irsglobal.com/shop_login/jumun_view_login_form.htm)\n*   [장바구니](https://www.irsglobal.com/shop_goods/cart_list.htm)\n*   [회원가입](https://www.irsglobal.com/join)\n*   [로그인](https://www.irsglobal.com/login)\n\n[![Image 2](https://www.irsglobal.com/img_up/shop_pds/irsglobal1/site_content/untitled-11504846769.png)](https://www.irsglobal.com/main)\n========================================================================================================================================\n\n*   [회사소개](https://www.irsglobal.com/shop_info/company.htm)\n\n    *   [회사소개](https://www.irsglobal.com/shop_info/company.htm)\n    *   [조직도](https://www.irsglobal.com/myboard/orgTree)\n    *   [산업조사 실적](https://www.irsglobal.com/myboard/history)\n    *   [주요 고객사](https://www.irsglobal.com/page/page1_3)\n\n*   [시장조사 보고서](https://www.irsglobal.com/shop_goods/goods_list.htm)\n\n    *   [ICT/정보통신](https://www.irsglobal.com/shop_goods/goods_list.htm?list_type=&category=02000000)\n    *   [우주/항공/자동차/로봇](https://www.irsglobal.com/shop_goods/goods_list.htm?list_type=&category=01000000)\n    *   [에너지/환경](https://www.irsglobal.com/shop_goods/goods_list.htm?list_type=&category=04000000)\n    *   [신소재/부품](https://www.irsglobal.com/shop_goods/goods_list.htm?list_type=&category=03000000)\n    *   [바이오/헬스케어/의료](https://www.irsglobal.com/shop_goods/goods_list.htm?list_type=&category=05000000)\n    *   [화장품/식품](https://www.irsglobal.com/shop_goods/goods_list.htm?list_type=&category=09000000)\n    *   [연구개발/기타](https://www.irsglobal.com/shop_goods/goods_list.htm?list_type=&category=06000000)\n    *   [4차산업](https://www.irsglobal.com/shop_goods/goods_list.htm?list_type=&category=0A000000)\n\n*   [산업동향 정보](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30798&board_code=rwdboard)\n\n    *   [ICT/정보통신](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30798&board_code=rwdboard)\n    *   [우주/항공/자동차/로봇](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30797&board_code=rwdboard)\n    *   [에너지/환경](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30800&board_code=rwdboard)\n    *   [신소재/부품](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30799&board_code=rwdboard)\n    *   [바이오/헬스케어/의료](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30801&board_code=rwdboard)\n    *   [화장품/식품](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=31817&board_code=rwdboard)\n    *   [기타](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30802&board_code=rwdboard)\n    *   [4차산업](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=31818&board_code=rwdboard)\n\n*   [메일링 서비스](https://www.irsglobal.com/myreg/etc2)\n\n    *   [메일링 구독 신청](https://www.irsglobal.com/myreg/etc2)\n    *   [메일링 구독 취소](https://www.irsglobal.com/myreg/etc)\n\n*   [고객센터](https://www.irsglobal.com/bbs/board1)\n\n    *   [공지사항](https://www.irsglobal.com/bbs/board1)\n    *   [자료실](https://www.irsglobal.com/bbs/board2)\n    *   [문의게시판](https://www.irsglobal.com/bbs/board4)\n    *   [PDF 구매 안내](https://www.irsglobal.com/page/guide)\n\nHOME 산업동향 정보 4차산업\n\n산업동향 정보\n-------\n\n*   [ICT/정보통신](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30798&board_code=rwdboard)\n*   [우주/항공/자동차/로봇](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30797&board_code=rwdboard)\n*   [에너지/환경](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30800&board_code=rwdboard)\n*   [신소재/부품](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30799&board_code=rwdboard)\n*   [바이오/헬스케어/의료](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30801&board_code=rwdboard)\n*   [화장품/식품](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=31817&board_code=rwdboard)\n*   [기타](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30802&board_code=rwdboard)\n*   [4차산업](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=31818&board_code=rwdboard)\n\n[![Image 3](https://www.irsglobal.com/img_up/shop_pds/irsglobal1/site_content/irs-geul-ro-beol_-bae-neo1510281470.png)](https://www.irsglobal.com/myreg/etc2)\n\n![Image 4: 상품 리스트 상단 아이콘](https://www.irsglobal.com/img_up/shop_pds/irsglobal1/design/img/shop_tit_img.png)*   4차산업\n\n*   [검색](javascript:;)\n\n게시물 검색 검색\n\n자동차/로봇 미국 자동차 시장 : 자동차의 성장과 2025년 전망\n====================================\n\n*   관리자(irsglobal1)\n*   2025-02-25 14:50:00\n*   _hit_ 7090\n*   121.173.47.139\n\n출처 :[https://blueskyinc.co.jp/column/2024-usa-vehicle-market/](https://blueskyinc.co.jp/column/2024-usa-vehicle-market/)\n\n2024 년의 미국 자동차 시장은 전기차(BEV, HEV)가 착실하게 성장한 한편 ICEV(내연기관차)가 여전히 시장의 중심을 이루었다. 기업에 있어서는 다양한 소비자 니즈에 대응하는 전략이 중요하다.\n\n이 기사에서는 최신 데이터를 바탕으로 2024 년의 동향을 되돌아보고, 2025 년에 예상되는 시장 변화를 분석한다.\n\n2024 년 미국 자동차 시장 : 전기차(BEV, HEV)의 판매 동향\n\n2024 년에 BEV(배터리 전기자동차)의 월간 판매 대수는 12 월에 13.0 만 대(전체 차량의 8.5%)가 되어 전년도보다 성장했다.\n\nTesla 의 BEV 판매 점유율은 47.7%로서 BEV 의 압도적인 리더로서의 위치를 유지했다.\n\n한편 Ford, GM, 한국 세력(현대, 기아)도 경쟁이 삼화되었고, 인프라 정비 및 정부 지원금이 성장을 뒷받침했다.\n\n<그림 1> 2021~2024 년 미국 시장에서의 BEV 판매 대수와 비율\n\n(막대 그래프 : 판매 대수(왼쪽 축), 선 그래프 : 비율(오른쪽 축))\n\n[![Image 5](https://www.irsglobal.com/img_up/shop_pds/irsglobal1/bbs/rwdboard/add_img/2025/0011740462819.jpg)](javascript:popview(\'/img_up/shop_pds/irsglobal1/bbs/rwdboard/add_img/2025/0011740462819.jpg\'))\n\n자료 : MARKLINES\n\n<그림 2> 2024 년 미국의 각 자동차 기업ㆍ브랜드의 BEV 판매 대수\n\n[![Image 6](https://www.irsglobal.com/img_up/shop_pds/irsglobal1/bbs/rwdboard/add_img/2025/0021740462828.jpg)](javascript:popview(\'/img_up/shop_pds/irsglobal1/bbs/rwdboard/add_img/2025/0021740462828.jpg\'))\n\n자료 : MARKLINES\n\nHEV(하이브리드차)는 판매 대수가 12 월에 17.1 만 대(전체 차량의 11.1%)로서, 1 년을 통틀어 BEV 를 웃도는 비율을 기록했다.\n\n특히 토요타가 HEV 시장을 이끌어, 전미 점유율의 약 절반을 차지했다. HEV 는 ‘전기차로의 전환에 신중한 소비자에게 현실적인 선택지’로서 지지를 모았다.\n\n<그림 3> 2021~2024 년 미국 시장에서의 HEV 판매 대수와 비율\n\n(막대 그래프 : 판매 대수(왼쪽 축), 선 그래프 : 비율(오른쪽 축))\n\n[![Image 7](https://www.irsglobal.com/img_up/shop_pds/irsglobal1/bbs/rwdboard/add_img/2025/0031740462837.jpg)](javascript:popview(\'/img_up/shop_pds/irsglobal1/bbs/rwdboard/add_img/2025/0031740462837.jpg\'))\n\n자료 : MARKLINES\n\n<그림 4> 2021~2024 년 미국 시장에서의 BEV 와 HEV 의 판매 비율\n\n(막대 그래프 : 판매 대수(왼쪽 축), 선 그래프 : 비율(오른쪽 축))\n\n[![Image 8](https://www.irsglobal.com/img_up/shop_pds/irsglobal1/bbs/rwdboard/add_img/2025/0041740462853.jpg)](javascript:popview(\'/img_up/shop_pds/irsglobal1/bbs/rwdboard/add_img/2025/0041740462853.jpg\'))\n\n자료 : MARKLINES\n\n<그림 5> 2024 년 미국의 각 자동차 기업ㆍ브랜드의 HEV 판매 대수\n\n[![Image 9](https://www.irsglobal.com/img_up/shop_pds/irsglobal1/bbs/rwdboard/add_img/2025/0051740462865.jpg)](javascript:popview(\'/img_up/shop_pds/irsglobal1/bbs/rwdboard/add_img/2025/0051740462865.jpg\'))\n\n자료 : MARKLINES\n\nICEV(내연기관차)의 시장 점유율은 여전히 압도적으로 높음\n\n전기차 시장이 계속해서 성장하고 있지만, 2024 년에도 미국 시장의 약 80%를 차지한 것은 ICEV 였다.\n\n<그림 6> 2021~2024 년 미국에서의 ICEV 판매 대수와 비율\n\n(막대 그래프 : 판매 대수(왼쪽 축), 선 그래프 : 비율(오른쪽 축))\n\n[![Image 10](https://www.irsglobal.com/img_up/shop_pds/irsglobal1/bbs/rwdboard/add_img/2025/0061740462881.jpg)](javascript:popview(\'/img_up/shop_pds/irsglobal1/bbs/rwdboard/add_img/2025/0061740462881.jpg\'))\n\n자료 : MARKLINES\n\n특히 픽업 트럭 및 대형 SUV 등 연비보다 실용성을 중시하는 부문에서의 수요가 뿌리 깊은 상황이다.\n\n대표적인 모델로는 Ford 의 F 시리즈와 GM 의 Silverado 가 있다.\n\n이들은 BEV 버전도 제공하지만, 주력 판매량은 여전히 ICEV 버전이 담당하고 있다.\n\n그 배경에는 미국의 광대한 지리 조건과 라이프스타일에 더하여 일부 지역에서의 충전 인프라 부족이 있다.\n\n[![Image 11](https://www.irsglobal.com/img_up/shop_pds/irsglobal1/bbs/rwdboard/add_img/2025/po-deu-cha1740462743.jpg)](javascript:popview(\'/img_up/shop_pds/irsglobal1/bbs/rwdboard/add_img/2025/po-deu-cha1740462743.jpg\'))\n\n2025 년의 시장 예측 : 트럼프 정권과 일론 머스크의 영향\n\n2025 년에는 트럼프 정권이 탄생함에 따라 BEV 시장을 둘러싼 환경이 변화할 것으로 예측된다.\n\n구체적으로는 다음과 같은 점이 주목받고 있다.\n\n트럼프 정권의 영향\n\nBEV 에 대한 지원금 폐지 및 규제 완화로 인해 석유 산업이 지원을 얻어 휘발유 가격이 낮아질 전망이다.\n\n이러한 움직임은 ICEV 의 수요를 다시 높일 가능성이 있다. 그리고 HEV 수요도 계속해서 꾸준한 추이를 보인다.\n\n일론 머스크의 영향\n\n앞서 언급한 것처럼 BEV 지원금이 폐지되지만, 테슬라는 이미 강한 가격 경쟁력을 보유하고 있어 지원금 폐지의 영향을 받지 않을 것으로 보인다.\n\n한편 ‘정부효율화부’에 참가함으로써 BEV 시장을 어느 정도 보호하는 시책을 내걸 가능성도 있다.\n\n기본적으로 트럼프는 ‘미국 제일주의’를 강조하는 시책을 추진한다.\n\n과거의 정권하에서도 연료 기준을 완화하고 석유 산업을 지원한 실적이 있으며, 이에 근거하여 국내 산업을 보호하면서도 고용을 창출하는 것을 중시할 가능성이 있다.\n\n또한 미국 내에서 많은 고용을 창출하게 된다면, (물론 경제 안전 보장 등 다양한 리스크를 불식하는 것이 전제되어야 하지만) 예를 들어 BYD 의 공장을 미국에 유치하게 될 가능성도 생길지 모른다. 현시점에서는 중국과의 경제 경쟁을 강조하는 트럼프 정권의 방침을 고려하면 적극적으로 추진할 것이라고 보긴 어렵지만, 완전히 부정할 수만은 없다.\n\n기성 개념에 사로잡히지 않고 ‘미국 제일주의’를 축으로 하여, 지금까지 이야기한 정책이 앞으로도 잇따라 만들어질 것으로 보인다.\n\n국내외 자동차 기업 및 투자가가 (물론 우리도) 시장 동향에 주목하고 있다.\n\n**한편, 1 월 30 일에 미국 운수부가 다음의 각서를 발행하겠다고 발표했다.**\n\n요점은 다음과 같다.\n\n1. ‘자동차에 대한 접근성에 관한 규제 장벽을 제거한다’\n\n2. ‘차량을 선택하는 소비자를 위해 공평한 규제 환경을 확보한다’\n\n3. ‘필요에 따라 휘발유차의 판매를 제한하는 기능을 가지는 주의 배출 규제 면제를 종료한다’\n\n4. ‘다른 기술보다 전기자동차(EV)를 우대하여 개인, 민간 기업, 정부 기관에 EV 구입을 사실상 의무화하는 불공정한 지원금이나 시장의 왜곡을 불러일으키는 정책을 배제할 것을 검토한다’\n\n(대통령령 14154 ‘Unleashing American Energy(미국의 에너지 해방)’ 제 2 항으로부터)\n\n즉 미국은 결코 BEV 를 배제할 생각이 없으며, ‘BEV 와 ICEV 를 어디까지나 같은 조건에서 싸우게 할 것’이라는 뜻이다.\n\n일론 머스크의 입장에서는 테슬라는 이미 충분한 경쟁력을 가지고 있으며, 같은 조건에서도 충분히 싸울 만하다고 판단했다고 볼 수 있다.\n\n(애초에 머스크는 이미 자동차에 힘을 쏟고 있지 않으며, xAI 에 힘을 쏟고 있다는 이야기도 있다)\n\n결론 : 전기화의 발전과 다양한 수요에 대한 대응\n\n2024 년의 미국 시장은 BEV 와 HEV 가 계속해서 성장하는 한편 ICEV 가 여전히 시장의 주력 상품으로 자리하는 현실을 보여주었다.\n\n2025 년에는 정책 전환 및 경쟁 환경의 변화로 인해 각 기업이 다양한 전략을 모색할 필요성이 있다.\n\n특히 BEV 의 성장을 내다보는 장기적인 투자와 단기적으로 수요가 높은 HEV 및 ICEV 에 대응하는 유연한 접근방식이 경쟁 우위성을 확보하는 열쇠가 될 것이다.\n\n소비자의 다양한 니즈를 정확하게 간파하면서 제품 및 서비스를 균형 있게 전개해야 한다.\n\n이것은 쉬운 과제는 아니지만, 시장 및 데이터와의 지속적인 대화를 통해 적절한 판단을 내리는 것이 성공을 위한 필수 요소라 할 수 있다.\n\n**[2025년 국내외 미래자동차 관련 유망 기술, 시장 동향과 사업화 전략]보고서 상세 보기**\n\n[https://www.irsglobal.com/shop_goods/goods_view.htm?category=01000000&goods_idx=98166&goods_bu_id=](https://www.irsglobal.com/shop_goods/goods_view.htm?category=01000000&goods_idx=98166&goods_bu_id=)\n\n[![Image 12](https://www.irsglobal.com/img_up/shop_pds/irsglobal1/bbs/rwdboard/add_img/2025/0031740458748.jpg)](javascript:popview(\'/img_up/shop_pds/irsglobal1/bbs/rwdboard/add_img/2025/0031740458748.jpg\'))\n\n**게시글 공유**[URL복사](javascript:;)\n\n[출력](javascript:board_view_print())\n\n[목록](https://www.irsglobal.com/bbs_shop/list.htm?me_popup=&auto_frame=&cate_sub_idx=0&search_first_subject=&list_mode=board&board_code=rwdboard&keyfield=&key=&page=&y=&m=)\n\n[_prev_**이전글**수소 사업에 주력 : SK, 현대자동차, 포스코](javascript:readArticle(\'25716\'))[_next_**다음글**중국 Zeekr가 테슬라・BYD를 추격 : 신흥 EV ‘3가지 강점’](javascript:readArticle(\'25696\'))\n\n*   [검색](javascript:;)\n\n게시물 검색 검색\n\nList of articles| 번호 | 분류 | 제목 | 작성자 | 작성일 | 조회수 |\n| --- | --- | --- | --- | --- | --- |\n| 1006 | 자동차/로봇 | [중국 휴머노이드 로봇 트렌드와 지원 정책 _photo_](https://www.irsglobal.com/bbs_shop/read.htm?me_popup=&auto_frame=&cate_sub_idx=0&search_first_subject=&list_mode=board&board_code=rwdboard&search_key=&key=&page=&idx=27686) | 관리자 | 2025-07-18 | _hit_ 142 |\n| 1005 | ICT/정보통신 | [일본의 재난안전 대응 전략 _photo_](https://www.irsglobal.com/bbs_shop/read.htm?me_popup=&auto_frame=&cate_sub_idx=0&search_first_subject=&list_mode=board&board_code=rwdboard&search_key=&key=&page=&idx=27676) | 관리자 | 2025-07-18 | _hit_ 94 |\n| 1004 | 에너지/환경 | [사용후 배터리 순환 이용 활성화 방안 _photo_](https://www.irsglobal.com/bbs_shop/read.htm?me_popup=&auto_frame=&cate_sub_idx=0&search_first_subject=&list_mode=board&board_code=rwdboard&search_key=&key=&page=&idx=27551) | 관리자 | 2025-07-04 | _hit_ 120 |\n| 1003 | ICT/정보통신 | [전고체전지와 AI 기술 _photo_](https://www.irsglobal.com/bbs_shop/read.htm?me_popup=&auto_frame=&cate_sub_idx=0&search_first_subject=&list_mode=board&board_code=rwdboard&search_key=&key=&page=&idx=27516) | 관리자 | 2025-06-25 | _hit_ 234 |\n| 1002 | 에너지/환경 | [AI 기술을 융합한 "모듈형 축전 시스템", 높은 안전성과 비용 효율성이 강점 _photo_](https://www.irsglobal.com/bbs_shop/read.htm?me_popup=&auto_frame=&cate_sub_idx=0&search_first_subject=&list_mode=board&board_code=rwdboard&search_key=&key=&page=&idx=27506) | 관리자 | 2025-06-25 | _hit_ 173 |\n| 1001 | ICT/정보통신 | [이차전지 소재 분야의 AI 활용 과제 _photo_](https://www.irsglobal.com/bbs_shop/read.htm?me_popup=&auto_frame=&cate_sub_idx=0&search_first_subject=&list_mode=board&board_code=rwdboard&search_key=&key=&page=&idx=27496) | 관리자 | 2025-06-25 | _hit_ 236 |\n| 1000 | 에너지/환경 | [탈탄소화를 위한 효율적인 수소 무역 _photo_](https://www.irsglobal.com/bbs_shop/read.htm?me_popup=&auto_frame=&cate_sub_idx=0&search_first_subject=&list_mode=board&board_code=rwdboard&search_key=&key=&page=&idx=27476) | 관리자 | 2025-06-24 | _hit_ 154 |\n| 999 | 바이오/의료 | [체외진단 의료기기 핵심 기술 : 분자 진단(MDx)의 기술 동향 _photo_](https://www.irsglobal.com/bbs_shop/read.htm?me_popup=&auto_frame=&cate_sub_idx=0&search_first_subject=&list_mode=board&board_code=rwdboard&search_key=&key=&page=&idx=27406) | 관리자 | 2025-06-17 | _hit_ 327 |\n| 998 | 자동차/로봇 | [위성통신(스타링크) 현황과 서비스 _photo_](https://www.irsglobal.com/bbs_shop/read.htm?me_popup=&auto_frame=&cate_sub_idx=0&search_first_subject=&list_mode=board&board_code=rwdboard&search_key=&key=&page=&idx=27356) | 관리자 | 2025-06-07 | _hit_ 662 |\n\n**1**[2](https://www.irsglobal.com/bbs_shop/list.htm?page=2&board_code=rwdboard)[3](https://www.irsglobal.com/bbs_shop/list.htm?page=3&board_code=rwdboard)[4](https://www.irsglobal.com/bbs_shop/list.htm?page=4&board_code=rwdboard)[5](https://www.irsglobal.com/bbs_shop/list.htm?page=5&board_code=rwdboard)[6](https://www.irsglobal.com/bbs_shop/list.htm?page=6&board_code=rwdboard)[7](https://www.irsglobal.com/bbs_shop/list.htm?page=7&board_code=rwdboard)[8](https://www.irsglobal.com/bbs_shop/list.htm?page=8&board_code=rwdboard)[9](https://www.irsglobal.com/bbs_shop/list.htm?page=9&board_code=rwdboard)[10](https://www.irsglobal.com/bbs_shop/list.htm?page=10&board_code=rwdboard)[_다음페이지_](https://www.irsglobal.com/bbs_shop/list.htm?page=2&board_code=rwdboard)[_마지막페이지_](https://www.irsglobal.com/bbs_shop/list.htm?page=11&board_code=rwdboard)\n\n[메일구독 신청](https://www.irsglobal.com/myreg/etc2)\n\n[문의하기](https://www.irsglobal.com/bbs/board4)\n\n*   [개인정보 취급받침](https://www.irsglobal.com/shop_info/privacy.htm)\n*   [이용약관](https://www.irsglobal.com/shop_info/agree.htm)\n\n![Image 13](https://www.irsglobal.com/img_up/shop_pds/irsglobal1/site_content/untitled-11504846803.png)\n\nIRS Global\n\n총괄관리자: 김승훈\n\n인천광역시 계양구 용종동 209-2 강남오피스텔 506호\n\nTEL: 02-786-7710\n\nFAX: 02-6008-0873\n\nMail: admin@irsglobal.com\n\n사업자등록번호: 130-44-20238\n\nCopyright IRS Global. All rights reserved.\n\n4차산업\n====\n\n*   [회사소개](https://www.irsglobal.com/shop_info/company.htm)\n\n    *   [회사소개](https://www.irsglobal.com/shop_info/company.htm)\n    *   [조직도](https://www.irsglobal.com/myboard/orgTree)\n    *   [산업조사 실적](https://www.irsglobal.com/myboard/history)\n    *   [주요 고객사](https://www.irsglobal.com/page/page1_3)\n\n*   [시장조사 보고서](https://www.irsglobal.com/shop_goods/goods_list.htm)\n\n    *   [ICT/정보통신](https://www.irsglobal.com/shop_goods/goods_list.htm?list_type=&category=02000000)\n    *   [우주/항공/자동차/로봇](https://www.irsglobal.com/shop_goods/goods_list.htm?list_type=&category=01000000)\n    *   [에너지/환경](https://www.irsglobal.com/shop_goods/goods_list.htm?list_type=&category=04000000)\n    *   [신소재/부품](https://www.irsglobal.com/shop_goods/goods_list.htm?list_type=&category=03000000)\n    *   [바이오/헬스케어/의료](https://www.irsglobal.com/shop_goods/goods_list.htm?list_type=&category=05000000)\n    *   [화장품/식품](https://www.irsglobal.com/shop_goods/goods_list.htm?list_type=&category=09000000)\n    *   [연구개발/기타](https://www.irsglobal.com/shop_goods/goods_list.htm?list_type=&category=06000000)\n    *   [4차산업](https://www.irsglobal.com/shop_goods/goods_list.htm?list_type=&category=0A000000)\n\n*   [산업동향 정보](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30798&board_code=rwdboard)\n\n    *   [ICT/정보통신](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30798&board_code=rwdboard)\n    *   [우주/항공/자동차/로봇](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30797&board_code=rwdboard)\n    *   [에너지/환경](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30800&board_code=rwdboard)\n    *   [신소재/부품](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30799&board_code=rwdboard)\n    *   [바이오/헬스케어/의료](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30801&board_code=rwdboard)\n    *   [화장품/식품](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=31817&board_code=rwdboard)\n    *   [기타](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=30802&board_code=rwdboard)\n    *   [4차산업](https://www.irsglobal.com/bbs_shop/list.htm?cate_sub_idx=31818&board_code=rwdboard)\n\n*   [메일링 서비스](https://www.irsglobal.com/myreg/etc2)\n\n    *   [메일링 구독 신청](https://www.irsglobal.com/myreg/etc2)\n    *   [메일링 구독 취소](https://www.irsglobal.com/myreg/etc)\n\n*   [고객센터](https://www.irsglobal.com/bbs/board1)\n\n    *   [공지사항](https://www.irsglobal.com/bbs/board1)\n    *   [자료실](https://www.irsglobal.com/bbs/board2)\n    *   [문의게시판](https://www.irsglobal.com/bbs/board4)\n    *   [PDF 구매 안내](https://www.irsglobal.com/page/guide)\n\n[로그인](https://www.irsglobal.com/login)\n======================================\n\n*   [로그인](https://www.irsglobal.com/login)\n*   [회원가입](https://www.irsglobal.com/join)\n*   [장바구니](https://www.irsglobal.com/shop_goods/cart_list.htm)\n*   [비회원 배송조회](https://www.irsglobal.com/shop_login/jumun_view_login_form.htm)\n\nClose\n'}]

In [8]:
# Step 2. 프롬프트 설정
prompt = [{
    "role": "system",
    "content":  (
        "당신은 신문기사를 쓰는 기자 AI입니다.  \n"
        "당신은 주어진 정보를 바탕으로 객관적이고 체계적으로 작성된 기사를 써야 합니다. \n"
    )
}, {
    "role": "user",
    "content": (
        f'정보: """{content}"""\n\n' 
        f'위의 정보를 사용하여, 다음 질문에 대해 자세한 보고서를 한국어로 작성하세요: "{query}" \n'
        '—신문기사 형식을 사용하되, MLA를 준수하는 markdown 문법을 사용해주세요.'
        '—활용한 자료는 출처를 명시하세요.'
    )
    
}]

In [9]:

# Step 3. 오픈AI를 랭체인인으로 실행하고 출력
report = llm.invoke(prompt).content
print(report)

# 현대자동차 미국 시장 2025년 전망

현대자동차는 2025년 미국 시장에서 강력한 성장세를 나타내며 역대 최대 판매 기록을 목표로 하고 있습니다. 이 전망은 현대자동차가 친환경차와 SUV 라인업을 중심으로 시장 점유율을 확장하고, 다양한 전략적 접근을 통해 경쟁력을 강화하고 있기 때문입니다.

## 미국 시장 내 현대자동차의 판매 성과

2025년 1월, 현대자동차는 미국 시장에서 1월 기준 역대 최대 판매량을 기록하며, 전년 동월 대비 15% 증가한 54,503대를 판매했습니다. 이는 친환경차 판매 증가와 SUV 라인업의 강세에 기인합니다. 하이브리드 차량은 74% 증가, 전기차(EV)는 15% 증가를 보였습니다. 특히, 싼타페 하이브리드와 투싼 하이브리드의 판매가 큰 폭으로 증가했습니다 [출처: novelone 블로그](https://novelone.tistory.com/).

2025년 2월에는 현대자동차의 미국 법인이 전년 동월 대비 3% 증가한 62,032대를 판매하며 역대 가장 높은 2월 판매량을 기록했습니다. 아이오닉 6 모델은 12% 증가를 보였으며, 하이브리드 전기차(HEV) 판매량은 57% 증가했습니다 [출처: Savannah Korean Times](https://savannahkoreatimes.com/).

## 현대자동차의 전략적 접근

현대자동차는 미국 시장에서의 성장을 위해 지속적인 신차 출시와 마케팅 전략을 추진하고 있습니다. 전기차와 하이브리드 차량의 혼류 생산 방식을 도입해 제조 효율성을 높이고 시장 변화에 신속히 대응하고 있습니다. 이로 인해 현대차는 소비자에게 더 많은 선택지를 제공할 수 있게 되었으며, 2024년에는 소매 판매 기준으로 165만 대를 넘는 성과를 예상하고 있습니다 [출처: Goover AI Report](https://seo.goover.ai/report/202504/go-public-report-ko-deb4e471-2938-494b-b19c-6eb5e10b1286-0-0.html).

또한, 현대

# 현대자동차 미국 시장 2025년 전망

현대자동차는 2025년 미국 시장에서 강력한 성장세를 나타내며 역대 최대 판매 기록을 목표로 하고 있습니다. 이 전망은 현대자동차가 친환경차와 SUV 라인업을 중심으로 시장 점유율을 확장하고, 다양한 전략적 접근을 통해 경쟁력을 강화하고 있기 때문입니다.

## 미국 시장 내 현대자동차의 판매 성과

2025년 1월, 현대자동차는 미국 시장에서 1월 기준 역대 최대 판매량을 기록하며, 전년 동월 대비 15% 증가한 54,503대를 판매했습니다. 이는 친환경차 판매 증가와 SUV 라인업의 강세에 기인합니다. 하이브리드 차량은 74% 증가, 전기차(EV)는 15% 증가를 보였습니다. 특히, 싼타페 하이브리드와 투싼 하이브리드의 판매가 큰 폭으로 증가했습니다 [출처: novelone 블로그](https://novelone.tistory.com/).

2025년 2월에는 현대자동차의 미국 법인이 전년 동월 대비 3% 증가한 62,032대를 판매하며 역대 가장 높은 2월 판매량을 기록했습니다. 아이오닉 6 모델은 12% 증가를 보였으며, 하이브리드 전기차(HEV) 판매량은 57% 증가했습니다 [출처: Savannah Korean Times](https://savannahkoreatimes.com/).

## 현대자동차의 전략적 접근

현대자동차는 미국 시장에서의 성장을 위해 지속적인 신차 출시와 마케팅 전략을 추진하고 있습니다. 전기차와 하이브리드 차량의 혼류 생산 방식을 도입해 제조 효율성을 높이고 시장 변화에 신속히 대응하고 있습니다. 이로 인해 현대차는 소비자에게 더 많은 선택지를 제공할 수 있게 되었으며, 2024년에는 소매 판매 기준으로 165만 대를 넘는 성과를 예상하고 있습니다 [출처: Goover AI Report](https://seo.goover.ai/report/202504/go-public-report-ko-deb4e471-2938-494b-b19c-6eb5e10b1286-0-0.html).

또한, 현대차는 인플레이션 감축법(IRA) 같은 정책적 변화에도 발 빠르게 대응하여 현지 생산 비율을 늘리며 경쟁력을 유지하고 있습니다. 이러한 전략은 소비자에게 보다 합리적인 가격을 제공하려는 노력의 일환입니다.

## 미래 전망과 도전 과제

현대자동차의 미국 시장 점유율 확장은 다양한 외부 변수에도 직면할 것입니다. 미국의 25% 관세 부과, 원/달러 환율 변동, 주요 원자재 가격 변화 등이 시장 환경에 영향을 미치고 있습니다. 현대차는 이러한 변수들에 대응하여 현지 생산을 확대하고 재고를 효과적으로 활용하여 비용을 절감할 계획입니다 [출처: Goover AI Report](https://seo.goover.ai/report/202506/go-public-report-ko-650e4de3-b7b3-4916-b47d-9293ec9ecd1f-0-0.html).

아울러, 소비자의 친환경차에 대한 선호가 증가함에 따라 현대차는 전기차 및 하이브리드 모델의 경쟁력을 더욱 강화하여 시장에서의 입지를 다질 것입니다. 그러나, 세계 경제의 불확실성과 자동차 시장의 변동성은 여전히 극복해야 할 과제로 남아있습니다.

## 결론

현대자동차는 친환경차와 SUV 전략을 기반으로 미국 시장에서의 성장을 지속하고 있으며, 다양한 외부 위협에도 대처할 수 있는 강력한 경쟁력을 확보하고 있습니다. 앞으로도 현대차는 친환경차 시장에서의 리더십을 강화하고, 새로운 정책 변화에 적응하며, 지속 가능한 성장을 위해 다양한 전략을 구사할 것입니다. 이러한 노력이 결실을 맺어 현대자동차가 미국 시장에서 계속해서 유리한 위치를 점할 것으로 기대됩니다.